# 2.4 Convolutional Nerual Network Hyperparamter Tuning

## Table of Contents
### 1. Import Libraries and Data

## 1. Import Libraries and Data

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import time
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.utils.multiclass import type_of_target
import tensorflow as tf
from numpy import unique
from numpy import reshape
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score
from tensorflow.keras.layers import Input, Conv1D, Dense, Dropout, BatchNormalization, Flatten, MaxPooling1D
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam, SGD, RMSprop, Adadelta, Adagrad, Adamax, Nadam, Ftrl
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from scikeras.wrappers import KerasClassifier  # Use scikeras for scikit-learn compatibility
from math import floor
from bayes_opt import BayesianOptimization
from tensorflow.keras.layers import LeakyReLU  # Use tensorflow.keras instead of keras
LeakyReLU = LeakyReLU(negative_slope=0.1)
import warnings

In [9]:
# Import unscaled weather data
path = r'/Users/daxma/OneDrive/Desktop/Data Analytics/Machine Learning with Python/07-25 ClimateWins Analysis/02 Data'
climate = pd.read_csv(os.path.join(path, 'Prepared Data', 'weather_unscaled_clean.csv'))

# Check output
climate.head()

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.018,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.018,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.018,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.018,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.018,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4

In [11]:
# Import pleasant weather data
weather = pd.read_csv(os.path.join(path, 'Original Data', 'Pleasant_Weather_Answers.csv'))

# Check output 
weather.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 2. Data Cleaning

In [13]:
# Drop date from weather df
weather.drop(columns = 'DATE', inplace = True)

In [15]:
climate.shape

(22950, 135)

In [17]:
weather.shape

(22950, 15)

## 3. Data Reshaping

In [19]:
# Turn X and answers from df to arrays

X = np.array(climate)
y = np.array(weather)

In [21]:
X = X.reshape(-1,15,9)

In [23]:
X.shape

(22950, 15, 9)

In [25]:
# Use argmax to transform y

y =  np.argmax(y, axis = 1)
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
# Reshape X as a 3D object
X = X.reshape(-1,15,9)

In [27]:
# Check shape
y.shape

(22950,)

## 4. Split Data

In [29]:
# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [31]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212,)
(5738, 15, 9) (5738,)

## 5. Bayesian Hyperparameter Optimisation

In [34]:
timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15 # Number of weather stations
# Make scorer accuracy
score_acc = make_scorer(accuracy_score)

In [36]:
# Create function

def bay_area(neurons, activation, kernel, optimizer, learning_rate, batch_size, epochs,
              layers1, layers2, normalization, dropout, dropout_rate): 
    optimizerL = ['SGD', 'Adam', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl','SGD']
    #optimizerD= {'Adam':Adam(lr=learning_rate), 'SGD':SGD(lr=learning_rate),
                 #'RMSprop':RMSprop(lr=learning_rate), 'Adadelta':Adadelta(lr=learning_rate),
                 #'Adagrad':Adagrad(lr=learning_rate), 'Adamax':Adamax(lr=learning_rate),
                 #'Nadam':Nadam(lr=learning_rate), 'Ftrl':Ftrl(lr=learning_rate)}
    activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu',
                   'elu', 'exponential', LeakyReLU,'relu']
    
    neurons = round(neurons)
    kernel = round(kernel)
    activation = activationL[round(activation)]  #optimizerD[optimizerL[round(optimizer)]]
    optimizer = optimizerL[round(optimizer)]
    batch_size = round(batch_size)
    
    epochs = round(epochs)
    layers1 = round(layers1)
    layers2 = round(layers2)
    
    def cnn_model():
        model = Sequential()
        model.add(Conv1D(neurons, kernel_size=kernel,activation=activation, input_shape=(timesteps, input_dim)))
        #model.add(Conv1D(32, kernel_size=1,activation='relu', input_shape=(timesteps, input_dim)))
        
        if normalization > 0.5:
            model.add(BatchNormalization())
        for i in range(layers1):
            model.add(Dense(neurons, activation=activation)) #(neurons, activation=activation))
        if dropout > 0.5:
            model.add(Dropout(dropout_rate, seed=123))
        for i in range(layers2):
            model.add(Dense(neurons, activation=activation))
        model.add(MaxPooling1D())
        model.add(Flatten())
        model.add(Dense(n_classes, activation='softmax')) #sigmoid softmax
        #model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy']) #categorical_crossentropy
        return model
    es = EarlyStopping(monitor='accuracy', mode='max', verbose=2, patience=20)
    nn = KerasClassifier(build_fn=cnn_model, epochs=epochs, batch_size=batch_size, verbose=2)
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
    score = cross_val_score(nn, X_train, y_train, scoring=score_acc, cv=kfold, params={'callbacks':[es]}).mean()
    return score

In [38]:
start = time.time()
params ={
    'neurons': (10, 100),
    'kernel': (1, 3),
    'activation':(0, 9), 
    'optimizer':(0,7),
    'learning_rate':(0.01, 1),
    'batch_size': (200, 1000), 
    'epochs':(20, 50),
    'layers1':(1,3),
    'layers2':(1,3),
    'normalization':(0,1),
    'dropout':(0,1),
    'dropout_rate':(0,0.3)
}
# Run Bayesian Optimization
nn_opt = BayesianOptimization(bay_area, params, random_state=42)
nn_opt.maximize(init_points=15, n_iter=4) 
print('Search took %s minutes' % ((time.time() - start)/60))

|   iter    |  target   |  neurons  |  kernel   | activa... | optimizer | learni... | batch_... |  epochs   |  layers1  |  layers2  | normal... |  dropout  | dropou... |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/22
43/43 - 3s - 65ms/step - accuracy: 0.6435 - loss: nan
Epoch 2/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/22
43/43 - 1s - 12ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
11/11 - 0s - 42ms/step
Epoch 1/22

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

43/43 - 3s - 65ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
11/11 - 0s - 32ms/step
Epoch 1/22

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

43/43 - 3s - 58ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/22
43/43 - 1s - 12ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/22
43/43 - 0s - 11ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/22
43/43 - 0s - 11ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/22
43/43 - 1s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/22
43/43 - 1s - 12ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/22
43/43 - 0s - 11ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
11/11 - 0s - 39ms/step
Epoch 1/22

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

43/43 - 2s - 50ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/22
43/43 - 0s - 11ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/22
43/43 - 1s - 12ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/22
43/43 - 1s - 12ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/22
43/43 - 0s - 9ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/22
43/43 - 0s - 8ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/22
43/43 - 0s - 10ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/22
43/43 - 1s - 13ms/step - accuracy: 0.6440 - loss: nan
11/11 - 0s - 32ms/step
Epoch 1/22

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

43/43 - 2s - 49ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/22
43/43 - 0s - 11ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/22
43/43 - 1s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/22
43/43 - 1s - 12ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/22
43/43 - 0s - 8ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/22
43/43 - 0s - 10ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/22
43/43 - 0s - 11ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/22
43/43 - 0s - 9ms/step - accuracy: 0.6439 - loss: nan
11/11 - 0s - 36ms/step
| 1         | 0.6439693 | 43.708610 | 2.9014286 | 6.5879454 | 4.1906093 | 0.1644584 | 324.79561 | 21.742508 | 2.7323522 | 2.2022300 | 0.7080725 | 0.0205844 | 0.2909729 |
Epoch 1/33

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 - 3s - 140ms/step - accuracy: 0.5655 - loss: 1.4770
Epoch 2/33
23/23 - 1s - 49ms/step - accuracy: 0.6403 - loss: 1.0559
Epoch 3/33
23/23 - 1s - 44ms/step - accuracy: 0.6704 - loss: 0.9814
Epoch 4/33
23/23 - 1s - 38ms/step - accuracy: 0.6906 - loss: 0.9158
Epoch 5/33
23/23 - 1s - 42ms/step - accuracy: 0.7058 - loss: 0.8707
Epoch 6/33
23/23 - 1s - 40ms/step - accuracy: 0.7252 - loss: 0.8113
Epoch 7/33
23/23 - 1s - 40ms/step - accuracy: 0.7377 - loss: 0.7608
Epoch 8/33
23/23 - 1s - 38ms/step - accuracy: 0.7440 - loss: 0.7355
Epoch 9/33
23/23 - 1s - 38ms/step - accuracy: 0.7544 - loss: 0.7060
Epoch 10/33
23/23 - 1s - 39ms/step - accuracy: 0.7621 - loss: 0.6857
Epoch 11/33
23/23 - 1s - 39ms/step - accuracy: 0.7664 - loss: 0.6614
Epoch 12/33
23/23 - 1s - 38ms/step - accuracy: 0.7777 - loss: 0.6321
Epoch 13/33
23/23 - 1s - 40ms/step - accuracy: 0.7786 - loss: 0.6150
Epoch 14/33
23/23 - 1s - 38ms/step - accuracy: 0.7908 - loss: 0.5883
Epoch 15/33
23/23 - 1s - 42ms/step - accuracy: 0.7897 - loss: 0.5838
Epoch 16/33
23/23 - 1s - 40ms/step - accuracy: 0.8005 - loss: 0.5602
Epoch 17/33
23/23 - 1s - 40ms/step - accuracy: 0.8102 - loss: 0.5327
Epoch 18/33
23/23 - 1s - 42ms/step - accuracy: 0.8173 - loss: 0.5213
Epoch 19/33
23/23 - 1s - 41ms/step - accuracy: 0.8287 - loss: 0.4838
Epoch 20/33
23/23 - 1s - 46ms/step - accuracy: 0.8340 - loss: 0.4668
Epoch 21/33
23/23 - 1s - 45ms/step - accuracy: 0.8400 - loss: 0.4474
Epoch 22/33
23/23 - 1s - 59ms/step - accuracy: 0.8450 - loss: 0.4318
Epoch 23/33
23/23 - 1s - 46ms/step - accuracy: 0.8534 - loss: 0.4105
Epoch 24/33
23/23 - 1s - 50ms/step - accuracy: 0.8567 - loss: 0.4018
Epoch 25/33
23/23 - 1s - 52ms/step - accuracy: 0.8592 - loss: 0.3929
Epoch 26/33
23/23 - 1s - 55ms/step - accuracy: 0.8682 - loss: 0.3672
Epoch 27/33
23/23 - 1s - 47ms/step - accuracy: 0.8717 - loss: 0.3628
Epoch 28/33
23/23 - 1s - 41ms/step - accuracy: 0.8715 - loss: 0.3632
Epoch 29/33
23/23 - 1s - 42ms/step - accuracy: 0.8683 - loss: 0.3675
Epoch 30/33
23/23 - 1s - 45ms/step - accuracy: 0.8776 - loss: 0.3400
Epoch 31/33
23/23 - 1s - 42ms/step - accuracy: 0.8876 - loss: 0.3227
Epoch 32/33
23/23 - 1s - 43ms/step - accuracy: 0.8867 - loss: 0.3189
Epoch 33/33
23/23 - 1s - 44ms/step - accuracy: 0.8960 - loss: 0.2993
6/6 - 0s - 71ms/step
Epoch 1/33

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 - 3s - 150ms/step - accuracy: 0.5959 - loss: 1.3296
Epoch 2/33
23/23 - 1s - 42ms/step - accuracy: 0.6562 - loss: 1.0101
Epoch 3/33
23/23 - 1s - 43ms/step - accuracy: 0.6903 - loss: 0.8942
Epoch 4/33
23/23 - 1s - 46ms/step - accuracy: 0.7089 - loss: 0.8381
Epoch 5/33
23/23 - 1s - 41ms/step - accuracy: 0.7217 - loss: 0.8009
Epoch 6/33
23/23 - 1s - 42ms/step - accuracy: 0.7303 - loss: 0.7682
Epoch 7/33
23/23 - 1s - 40ms/step - accuracy: 0.7463 - loss: 0.7333
Epoch 8/33
23/23 - 1s - 42ms/step - accuracy: 0.7592 - loss: 0.6982
Epoch 9/33
23/23 - 1s - 40ms/step - accuracy: 0.7619 - loss: 0.6827
Epoch 10/33
23/23 - 1s - 41ms/step - accuracy: 0.7725 - loss: 0.6562
Epoch 11/33
23/23 - 1s - 41ms/step - accuracy: 0.7814 - loss: 0.6263
Epoch 12/33
23/23 - 1s - 41ms/step - accuracy: 0.7914 - loss: 0.6020
Epoch 13/33
23/23 - 1s - 42ms/step - accuracy: 0.8020 - loss: 0.5751
Epoch 14/33
23/23 - 1s - 42ms/step - accuracy: 0.8087 - loss: 0.5512
Epoch 15/33
23/23 - 1s - 42ms/step - accuracy: 0.8133 - loss: 0.5310
Epoch 16/33
23/23 - 1s - 50ms/step - accuracy: 0.8226 - loss: 0.5019
Epoch 17/33
23/23 - 1s - 40ms/step - accuracy: 0.8287 - loss: 0.4883
Epoch 18/33
23/23 - 1s - 41ms/step - accuracy: 0.8322 - loss: 0.4702
Epoch 19/33
23/23 - 1s - 39ms/step - accuracy: 0.8388 - loss: 0.4460
Epoch 20/33
23/23 - 1s - 44ms/step - accuracy: 0.8519 - loss: 0.4151
Epoch 21/33
23/23 - 1s - 43ms/step - accuracy: 0.8542 - loss: 0.4082
Epoch 22/33
23/23 - 1s - 52ms/step - accuracy: 0.8576 - loss: 0.3922
Epoch 23/33
23/23 - 1s - 50ms/step - accuracy: 0.8624 - loss: 0.3874
Epoch 24/33
23/23 - 1s - 40ms/step - accuracy: 0.8656 - loss: 0.3739
Epoch 25/33
23/23 - 1s - 42ms/step - accuracy: 0.8675 - loss: 0.3622
Epoch 26/33
23/23 - 1s - 42ms/step - accuracy: 0.8775 - loss: 0.3378
Epoch 27/33
23/23 - 1s - 51ms/step - accuracy: 0.8730 - loss: 0.3474
Epoch 28/33
23/23 - 1s - 48ms/step - accuracy: 0.8807 - loss: 0.3337
Epoch 29/33
23/23 - 1s - 42ms/step - accuracy: 0.8819 - loss: 0.3279
Epoch 30/33
23/23 - 1s - 45ms/step - accuracy: 0.8872 - loss: 0.3157
Epoch 31/33
23/23 - 1s - 42ms/step - accuracy: 0.8953 - loss: 0.2917
Epoch 32/33
23/23 - 1s - 56ms/step - accuracy: 0.8945 - loss: 0.2985
Epoch 33/33
23/23 - 1s - 63ms/step - accuracy: 0.8937 - loss: 0.2968
WARNING:tensorflow:5 out of the last 18 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000024377961A80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 - 0s - 77ms/step
Epoch 1/33

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 - 4s - 183ms/step - accuracy: 0.6129 - loss: 1.3091
Epoch 2/33
23/23 - 1s - 47ms/step - accuracy: 0.6455 - loss: 1.0379
Epoch 3/33
23/23 - 1s - 42ms/step - accuracy: 0.6717 - loss: 0.9529
Epoch 4/33
23/23 - 1s - 44ms/step - accuracy: 0.7052 - loss: 0.8657
Epoch 5/33
23/23 - 1s - 46ms/step - accuracy: 0.7235 - loss: 0.8115
Epoch 6/33
23/23 - 1s - 39ms/step - accuracy: 0.7378 - loss: 0.7759
Epoch 7/33
23/23 - 1s - 41ms/step - accuracy: 0.7484 - loss: 0.7431
Epoch 8/33
23/23 - 1s - 41ms/step - accuracy: 0.7466 - loss: 0.7352
Epoch 9/33
23/23 - 1s - 40ms/step - accuracy: 0.7584 - loss: 0.6961
Epoch 10/33
23/23 - 1s - 43ms/step - accuracy: 0.7676 - loss: 0.6822
Epoch 11/33
23/23 - 1s - 50ms/step - accuracy: 0.7704 - loss: 0.6607
Epoch 12/33
23/23 - 1s - 52ms/step - accuracy: 0.7769 - loss: 0.6371
Epoch 13/33
23/23 - 1s - 47ms/step - accuracy: 0.7860 - loss: 0.6100
Epoch 14/33
23/23 - 1s - 47ms/step - accuracy: 0.7924 - loss: 0.5942
Epoch 15/33
23/23 - 1s - 48ms/step - accuracy: 0.7996 - loss: 0.5727
Epoch 16/33
23/23 - 1s - 40ms/step - accuracy: 0.8051 - loss: 0.5474
Epoch 17/33
23/23 - 1s - 42ms/step - accuracy: 0.8079 - loss: 0.5308
Epoch 18/33
23/23 - 1s - 48ms/step - accuracy: 0.8237 - loss: 0.4968
Epoch 19/33
23/23 - 1s - 43ms/step - accuracy: 0.8284 - loss: 0.4861
Epoch 20/33
23/23 - 1s - 47ms/step - accuracy: 0.8398 - loss: 0.4521
Epoch 21/33
23/23 - 1s - 47ms/step - accuracy: 0.8410 - loss: 0.4369
Epoch 22/33
23/23 - 1s - 46ms/step - accuracy: 0.8491 - loss: 0.4176
Epoch 23/33
23/23 - 1s - 43ms/step - accuracy: 0.8573 - loss: 0.3986
Epoch 24/33
23/23 - 1s - 44ms/step - accuracy: 0.8579 - loss: 0.4022
Epoch 25/33
23/23 - 1s - 39ms/step - accuracy: 0.8641 - loss: 0.3722
Epoch 26/33
23/23 - 1s - 45ms/step - accuracy: 0.8703 - loss: 0.3626
Epoch 27/33
23/23 - 1s - 44ms/step - accuracy: 0.8753 - loss: 0.3498
Epoch 28/33
23/23 - 1s - 47ms/step - accuracy: 0.8616 - loss: 0.3794
Epoch 29/33
23/23 - 1s - 45ms/step - accuracy: 0.8715 - loss: 0.3537
Epoch 30/33
23/23 - 1s - 45ms/step - accuracy: 0.8791 - loss: 0.3386
Epoch 31/33
23/23 - 1s - 42ms/step - accuracy: 0.8830 - loss: 0.3257
Epoch 32/33
23/23 - 1s - 45ms/step - accuracy: 0.8922 - loss: 0.3050
Epoch 33/33
23/23 - 1s - 42ms/step - accuracy: 0.8957 - loss: 0.2945
WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002437441B880> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
6/6 - 0s - 74ms/step
Epoch 1/33

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 - 3s - 133ms/step - accuracy: 0.5642 - loss: 1.4736
Epoch 2/33
23/23 - 1s - 39ms/step - accuracy: 0.6329 - loss: 1.0603
Epoch 3/33
23/23 - 1s - 40ms/step - accuracy: 0.6692 - loss: 0.9806
Epoch 4/33
23/23 - 1s - 39ms/step - accuracy: 0.6916 - loss: 0.8977
Epoch 5/33
23/23 - 1s - 41ms/step - accuracy: 0.7084 - loss: 0.8404
Epoch 6/33
23/23 - 1s - 40ms/step - accuracy: 0.7228 - loss: 0.7885
Epoch 7/33
23/23 - 1s - 41ms/step - accuracy: 0.7393 - loss: 0.7442
Epoch 8/33
23/23 - 1s - 42ms/step - accuracy: 0.7516 - loss: 0.7098
Epoch 9/33
23/23 - 1s - 40ms/step - accuracy: 0.7585 - loss: 0.6862
Epoch 10/33
23/23 - 1s - 40ms/step - accuracy: 0.7628 - loss: 0.6630
Epoch 11/33
23/23 - 1s - 39ms/step - accuracy: 0.7709 - loss: 0.6533
Epoch 12/33
23/23 - 1s - 42ms/step - accuracy: 0.7794 - loss: 0.6216
Epoch 13/33
23/23 - 1s - 47ms/step - accuracy: 0.7866 - loss: 0.6009
Epoch 14/33
23/23 - 1s - 39ms/step - accuracy: 0.7871 - loss: 0.5872
Epoch 15/33
23/23 - 1s - 38ms/step - accuracy: 0.7939 - loss: 0.5741
Epoch 16/33
23/23 - 1s - 38ms/step - accuracy: 0.8091 - loss: 0.5388
Epoch 17/33
23/23 - 1s - 39ms/step - accuracy: 0.8160 - loss: 0.5151
Epoch 18/33
23/23 - 1s - 41ms/step - accuracy: 0.8182 - loss: 0.5091
Epoch 19/33
23/23 - 1s - 40ms/step - accuracy: 0.8250 - loss: 0.4835
Epoch 20/33
23/23 - 1s - 40ms/step - accuracy: 0.8397 - loss: 0.4529
Epoch 21/33
23/23 - 1s - 40ms/step - accuracy: 0.8446 - loss: 0.4308
Epoch 22/33
23/23 - 1s - 40ms/step - accuracy: 0.8528 - loss: 0.4146
Epoch 23/33
23/23 - 1s - 38ms/step - accuracy: 0.8520 - loss: 0.4150
Epoch 24/33
23/23 - 1s - 41ms/step - accuracy: 0.8600 - loss: 0.3933
Epoch 25/33
23/23 - 1s - 38ms/step - accuracy: 0.8585 - loss: 0.3898
Epoch 26/33
23/23 - 1s - 38ms/step - accuracy: 0.8585 - loss: 0.3967
Epoch 27/33
23/23 - 1s - 43ms/step - accuracy: 0.8707 - loss: 0.3552
Epoch 28/33
23/23 - 1s - 39ms/step - accuracy: 0.8770 - loss: 0.3446
Epoch 29/33
23/23 - 1s - 40ms/step - accuracy: 0.8796 - loss: 0.3375
Epoch 30/33
23/23 - 1s - 45ms/step - accuracy: 0.8644 - loss: 0.3782
Epoch 31/33
23/23 - 1s - 41ms/step - accuracy: 0.8833 - loss: 0.3310
Epoch 32/33
23/23 - 1s - 39ms/step - accuracy: 0.8914 - loss: 0.3085
Epoch 33/33
23/23 - 1s - 42ms/step - accuracy: 0.8837 - loss: 0.3208
6/6 - 0s - 66ms/step
Epoch 1/33

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

23/23 - 3s - 141ms/step - accuracy: 0.5833 - loss: 1.4142
Epoch 2/33
23/23 - 1s - 38ms/step - accuracy: 0.6353 - loss: 1.0496
Epoch 3/33
23/23 - 1s - 38ms/step - accuracy: 0.6617 - loss: 0.9659
Epoch 4/33
23/23 - 1s - 39ms/step - accuracy: 0.6952 - loss: 0.8787
Epoch 5/33
23/23 - 1s - 39ms/step - accuracy: 0.7171 - loss: 0.8228
Epoch 6/33
23/23 - 1s - 37ms/step - accuracy: 0.7263 - loss: 0.7825
Epoch 7/33
23/23 - 1s - 39ms/step - accuracy: 0.7371 - loss: 0.7495
Epoch 8/33
23/23 - 1s - 38ms/step - accuracy: 0.7492 - loss: 0.7247
Epoch 9/33
23/23 - 1s - 39ms/step - accuracy: 0.7574 - loss: 0.7041
Epoch 10/33
23/23 - 1s - 39ms/step - accuracy: 0.7582 - loss: 0.6902
Epoch 11/33
23/23 - 1s - 39ms/step - accuracy: 0.7722 - loss: 0.6542
Epoch 12/33
23/23 - 1s - 38ms/step - accuracy: 0.7763 - loss: 0.6345
Epoch 13/33
23/23 - 1s - 38ms/step - accuracy: 0.7884 - loss: 0.6043
Epoch 14/33
23/23 - 1s - 39ms/step - accuracy: 0.7983 - loss: 0.5784
Epoch 15/33
23/23 - 1s - 38ms/step - accuracy: 0.8004 - loss: 0.5629
Epoch 16/33
23/23 - 1s - 38ms/step - accuracy: 0.8025 - loss: 0.5476
Epoch 17/33
23/23 - 1s - 39ms/step - accuracy: 0.8213 - loss: 0.5069
Epoch 18/33
23/23 - 1s - 38ms/step - accuracy: 0.8206 - loss: 0.5150
Epoch 19/33
23/23 - 1s - 38ms/step - accuracy: 0.8291 - loss: 0.4742
Epoch 20/33
23/23 - 1s - 38ms/step - accuracy: 0.8322 - loss: 0.4618
Epoch 21/33
23/23 - 1s - 38ms/step - accuracy: 0.8326 - loss: 0.4557
Epoch 22/33
23/23 - 1s - 41ms/step - accuracy: 0.8482 - loss: 0.4292
Epoch 23/33
23/23 - 1s - 39ms/step - accuracy: 0.8532 - loss: 0.4074
Epoch 24/33
23/23 - 1s - 37ms/step - accuracy: 0.8624 - loss: 0.3851
Epoch 25/33
23/23 - 1s - 41ms/step - accuracy: 0.8640 - loss: 0.3748
Epoch 26/33
23/23 - 1s - 37ms/step - accuracy: 0.8665 - loss: 0.3744
Epoch 27/33
23/23 - 1s - 39ms/step - accuracy: 0.8749 - loss: 0.3481
Epoch 28/33
23/23 - 1s - 41ms/step - accuracy: 0.8809 - loss: 0.3345
Epoch 29/33
23/23 - 1s - 39ms/step - accuracy: 0.8767 - loss: 0.3400
Epoch 30/33
23/23 - 1s - 39ms/step - accuracy: 0.8822 - loss: 0.3294
Epoch 31/33
23/23 - 1s - 40ms/step - accuracy: 0.8874 - loss: 0.3202
Epoch 32/33
23/23 - 1s - 38ms/step - accuracy: 0.8745 - loss: 0.3479
Epoch 33/33
23/23 - 1s - 39ms/step - accuracy: 0.8874 - loss: 0.3164
6/6 - 0s - 63ms/step
| 2         | 0.8685220 | 84.919837 | 1.4246782 | 1.6364247 | 1.2838315 | 0.3111998 | 619.80514 | 32.958350 | 1.5824582 | 2.2237057 | 0.1394938 | 0.2921446 | 0.1099085 |
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

59/59 - 2s - 38ms/step - accuracy: 0.4511 - loss: 1.9592
Epoch 2/38
59/59 - 1s - 10ms/step - accuracy: 0.6462 - loss: 1.1862
Epoch 3/38
59/59 - 1s - 13ms/step - accuracy: 0.6504 - loss: 1.1213
Epoch 4/38
59/59 - 1s - 9ms/step - accuracy: 0.6504 - loss: 1.0945
Epoch 5/38
59/59 - 1s - 12ms/step - accuracy: 0.6536 - loss: 1.0751
Epoch 6/38
59/59 - 1s - 11ms/step - accuracy: 0.6571 - loss: 1.0593
Epoch 7/38
59/59 - 1s - 10ms/step - accuracy: 0.6589 - loss: 1.0569
Epoch 8/38
59/59 - 0s - 7ms/step - accuracy: 0.6576 - loss: 1.0481
Epoch 9/38
59/59 - 0s - 7ms/step - accuracy: 0.6624 - loss: 1.0356
Epoch 10/38
59/59 - 0s - 7ms/step - accuracy: 0.6646 - loss: 1.0295
Epoch 11/38
59/59 - 0s - 8ms/step - accuracy: 0.6683 - loss: 1.0230
Epoch 12/38
59/59 - 0s - 7ms/step - accuracy: 0.6695 - loss: 1.0177
Epoch 13/38
59/59 - 1s - 10ms/step - accuracy: 0.6733 - loss: 1.0091
Epoch 14/38
59/59 - 1s - 11ms/step - accuracy: 0.6684 - loss: 1.0037
Epoch 15/38
59/59 - 1s - 12ms/step - accuracy: 0.6761 - loss: 1.0015
Epoch 16/38
59/59 - 1s - 10ms/step - accuracy: 0.6727 - loss: 1.0008
Epoch 17/38
59/59 - 1s - 13ms/step - accuracy: 0.6799 - loss: 0.9903
Epoch 18/38
59/59 - 1s - 11ms/step - accuracy: 0.6785 - loss: 0.9894
Epoch 19/38
59/59 - 1s - 13ms/step - accuracy: 0.6812 - loss: 0.9861
Epoch 20/38
59/59 - 1s - 13ms/step - accuracy: 0.6798 - loss: 0.9843
Epoch 21/38
59/59 - 1s - 12ms/step - accuracy: 0.6859 - loss: 0.9740
Epoch 22/38
59/59 - 1s - 13ms/step - accuracy: 0.6833 - loss: 0.9732
Epoch 23/38
59/59 - 1s - 10ms/step - accuracy: 0.6841 - loss: 0.9783
Epoch 24/38
59/59 - 1s - 12ms/step - accuracy: 0.6831 - loss: 0.9698
Epoch 25/38
59/59 - 1s - 11ms/step - accuracy: 0.6856 - loss: 0.9700
Epoch 26/38
59/59 - 1s - 10ms/step - accuracy: 0.6893 - loss: 0.9624
Epoch 27/38
59/59 - 1s - 11ms/step - accuracy: 0.6897 - loss: 0.9612
Epoch 28/38
59/59 - 1s - 11ms/step - accuracy: 0.6867 - loss: 0.9591
Epoch 29/38
59/59 - 1s - 12ms/step - accuracy: 0.6905 - loss: 0.9534
Epoch 30/38
59/59 - 1s - 11ms/step - accuracy: 0.6861 - loss: 0.9499
Epoch 31/38
59/59 - 1s - 13ms/step - accuracy: 0.6905 - loss: 0.9487
Epoch 32/38
59/59 - 1s - 13ms/step - accuracy: 0.6873 - loss: 0.9469
Epoch 33/38
59/59 - 0s - 7ms/step - accuracy: 0.6871 - loss: 0.9466
Epoch 34/38
59/59 - 0s - 8ms/step - accuracy: 0.6903 - loss: 0.9456
Epoch 35/38
59/59 - 0s - 7ms/step - accuracy: 0.6922 - loss: 0.9417
Epoch 36/38
59/59 - 0s - 7ms/step - accuracy: 0.6943 - loss: 0.9364
Epoch 37/38
59/59 - 0s - 7ms/step - accuracy: 0.6902 - loss: 0.9370
Epoch 38/38
59/59 - 1s - 9ms/step - accuracy: 0.6940 - loss: 0.9374
15/15 - 0s - 23ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

59/59 - 2s - 37ms/step - accuracy: 0.5465 - loss: 1.5386
Epoch 2/38
59/59 - 1s - 10ms/step - accuracy: 0.6436 - loss: 1.1557
Epoch 3/38
59/59 - 1s - 11ms/step - accuracy: 0.6467 - loss: 1.1066
Epoch 4/38
59/59 - 1s - 11ms/step - accuracy: 0.6456 - loss: 1.0852
Epoch 5/38
59/59 - 1s - 12ms/step - accuracy: 0.6475 - loss: 1.0694
Epoch 6/38
59/59 - 1s - 11ms/step - accuracy: 0.6486 - loss: 1.0561
Epoch 7/38
59/59 - 1s - 11ms/step - accuracy: 0.6524 - loss: 1.0455
Epoch 8/38
59/59 - 1s - 13ms/step - accuracy: 0.6579 - loss: 1.0350
Epoch 9/38
59/59 - 0s - 8ms/step - accuracy: 0.6592 - loss: 1.0246
Epoch 10/38
59/59 - 0s - 7ms/step - accuracy: 0.6595 - loss: 1.0210
Epoch 11/38
59/59 - 0s - 7ms/step - accuracy: 0.6581 - loss: 1.0151
Epoch 12/38
59/59 - 0s - 7ms/step - accuracy: 0.6645 - loss: 1.0061
Epoch 13/38
59/59 - 0s - 7ms/step - accuracy: 0.6669 - loss: 0.9977
Epoch 14/38
59/59 - 0s - 7ms/step - accuracy: 0.6687 - loss: 0.9926
Epoch 15/38
59/59 - 1s - 11ms/step - accuracy: 0.6690 - loss: 0.9873
Epoch 16/38
59/59 - 1s - 13ms/step - accuracy: 0.6722 - loss: 0.9834
Epoch 17/38
59/59 - 1s - 11ms/step - accuracy: 0.6674 - loss: 0.9799
Epoch 18/38
59/59 - 1s - 12ms/step - accuracy: 0.6748 - loss: 0.9723
Epoch 19/38
59/59 - 1s - 10ms/step - accuracy: 0.6739 - loss: 0.9731
Epoch 20/38
59/59 - 0s - 7ms/step - accuracy: 0.6738 - loss: 0.9682
Epoch 21/38
59/59 - 0s - 7ms/step - accuracy: 0.6768 - loss: 0.9656
Epoch 22/38
59/59 - 0s - 7ms/step - accuracy: 0.6727 - loss: 0.9638
Epoch 23/38
59/59 - 0s - 7ms/step - accuracy: 0.6758 - loss: 0.9607
Epoch 24/38
59/59 - 0s - 7ms/step - accuracy: 0.6775 - loss: 0.9550
Epoch 25/38
59/59 - 0s - 7ms/step - accuracy: 0.6774 - loss: 0.9516
Epoch 26/38
59/59 - 1s - 11ms/step - accuracy: 0.6777 - loss: 0.9516
Epoch 27/38
59/59 - 1s - 10ms/step - accuracy: 0.6805 - loss: 0.9450
Epoch 28/38
59/59 - 1s - 11ms/step - accuracy: 0.6819 - loss: 0.9455
Epoch 29/38
59/59 - 1s - 11ms/step - accuracy: 0.6815 - loss: 0.9402
Epoch 30/38
59/59 - 1s - 13ms/step - accuracy: 0.6845 - loss: 0.9389
Epoch 31/38
59/59 - 1s - 13ms/step - accuracy: 0.6824 - loss: 0.9357
Epoch 32/38
59/59 - 1s - 13ms/step - accuracy: 0.6811 - loss: 0.9378
Epoch 33/38
59/59 - 1s - 14ms/step - accuracy: 0.6829 - loss: 0.9284
Epoch 34/38
59/59 - 1s - 12ms/step - accuracy: 0.6840 - loss: 0.9287
Epoch 35/38
59/59 - 1s - 11ms/step - accuracy: 0.6842 - loss: 0.9323
Epoch 36/38
59/59 - 1s - 10ms/step - accuracy: 0.6877 - loss: 0.9240
Epoch 37/38
59/59 - 1s - 12ms/step - accuracy: 0.6876 - loss: 0.9179
Epoch 38/38
59/59 - 1s - 10ms/step - accuracy: 0.6859 - loss: 0.9216
15/15 - 0s - 20ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

59/59 - 2s - 39ms/step - accuracy: 0.6335 - loss: 1.3839
Epoch 2/38
59/59 - 1s - 10ms/step - accuracy: 0.6394 - loss: 1.1337
Epoch 3/38
59/59 - 1s - 11ms/step - accuracy: 0.6418 - loss: 1.0971
Epoch 4/38
59/59 - 1s - 9ms/step - accuracy: 0.6454 - loss: 1.0704
Epoch 5/38
59/59 - 0s - 7ms/step - accuracy: 0.6477 - loss: 1.0558
Epoch 6/38
59/59 - 0s - 6ms/step - accuracy: 0.6521 - loss: 1.0425
Epoch 7/38
59/59 - 0s - 7ms/step - accuracy: 0.6520 - loss: 1.0309
Epoch 8/38
59/59 - 0s - 7ms/step - accuracy: 0.6558 - loss: 1.0214
Epoch 9/38
59/59 - 0s - 7ms/step - accuracy: 0.6584 - loss: 1.0137
Epoch 10/38
59/59 - 1s - 11ms/step - accuracy: 0.6628 - loss: 1.0051
Epoch 11/38
59/59 - 1s - 10ms/step - accuracy: 0.6643 - loss: 0.9999
Epoch 12/38
59/59 - 1s - 12ms/step - accuracy: 0.6653 - loss: 0.9949
Epoch 13/38
59/59 - 1s - 10ms/step - accuracy: 0.6654 - loss: 0.9915
Epoch 14/38
59/59 - 1s - 11ms/step - accuracy: 0.6661 - loss: 0.9901
Epoch 15/38
59/59 - 1s - 13ms/step - accuracy: 0.6710 - loss: 0.9761
Epoch 16/38
59/59 - 1s - 10ms/step - accuracy: 0.6725 - loss: 0.9716
Epoch 17/38
59/59 - 1s - 10ms/step - accuracy: 0.6738 - loss: 0.9721
Epoch 18/38
59/59 - 1s - 12ms/step - accuracy: 0.6723 - loss: 0.9663
Epoch 19/38
59/59 - 1s - 10ms/step - accuracy: 0.6744 - loss: 0.9660
Epoch 20/38
59/59 - 1s - 12ms/step - accuracy: 0.6752 - loss: 0.9617
Epoch 21/38
59/59 - 1s - 12ms/step - accuracy: 0.6781 - loss: 0.9548
Epoch 22/38
59/59 - 1s - 13ms/step - accuracy: 0.6805 - loss: 0.9494
Epoch 23/38
59/59 - 1s - 10ms/step - accuracy: 0.6796 - loss: 0.9478
Epoch 24/38
59/59 - 1s - 12ms/step - accuracy: 0.6832 - loss: 0.9469
Epoch 25/38
59/59 - 1s - 12ms/step - accuracy: 0.6832 - loss: 0.9404
Epoch 26/38
59/59 - 1s - 11ms/step - accuracy: 0.6784 - loss: 0.9397
Epoch 27/38
59/59 - 1s - 12ms/step - accuracy: 0.6820 - loss: 0.9328
Epoch 28/38
59/59 - 1s - 11ms/step - accuracy: 0.6829 - loss: 0.9337
Epoch 29/38
59/59 - 1s - 9ms/step - accuracy: 0.6858 - loss: 0.9312
Epoch 30/38
59/59 - 1s - 11ms/step - accuracy: 0.6876 - loss: 0.9274
Epoch 31/38
59/59 - 0s - 7ms/step - accuracy: 0.6849 - loss: 0.9277
Epoch 32/38
59/59 - 0s - 7ms/step - accuracy: 0.6871 - loss: 0.9253
Epoch 33/38
59/59 - 0s - 7ms/step - accuracy: 0.6891 - loss: 0.9196
Epoch 34/38
59/59 - 0s - 7ms/step - accuracy: 0.6873 - loss: 0.9234
Epoch 35/38
59/59 - 0s - 7ms/step - accuracy: 0.6866 - loss: 0.9154
Epoch 36/38
59/59 - 1s - 10ms/step - accuracy: 0.6882 - loss: 0.9182
Epoch 37/38
59/59 - 1s - 12ms/step - accuracy: 0.6878 - loss: 0.9165
Epoch 38/38
59/59 - 1s - 12ms/step - accuracy: 0.6928 - loss: 0.9082
15/15 - 0s - 22ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

59/59 - 2s - 37ms/step - accuracy: 0.5986 - loss: 1.3864
Epoch 2/38
59/59 - 1s - 11ms/step - accuracy: 0.6359 - loss: 1.1414
Epoch 3/38
59/59 - 1s - 11ms/step - accuracy: 0.6438 - loss: 1.0952
Epoch 4/38
59/59 - 1s - 13ms/step - accuracy: 0.6435 - loss: 1.0686
Epoch 5/38
59/59 - 1s - 11ms/step - accuracy: 0.6447 - loss: 1.0577
Epoch 6/38
59/59 - 1s - 12ms/step - accuracy: 0.6510 - loss: 1.0365
Epoch 7/38
59/59 - 1s - 10ms/step - accuracy: 0.6527 - loss: 1.0337
Epoch 8/38
59/59 - 1s - 11ms/step - accuracy: 0.6519 - loss: 1.0245
Epoch 9/38
59/59 - 1s - 12ms/step - accuracy: 0.6569 - loss: 1.0165
Epoch 10/38
59/59 - 1s - 13ms/step - accuracy: 0.6556 - loss: 1.0119
Epoch 11/38
59/59 - 1s - 10ms/step - accuracy: 0.6585 - loss: 1.0071
Epoch 12/38
59/59 - 1s - 12ms/step - accuracy: 0.6595 - loss: 1.0059
Epoch 13/38
59/59 - 1s - 12ms/step - accuracy: 0.6632 - loss: 0.9938
Epoch 14/38
59/59 - 1s - 12ms/step - accuracy: 0.6611 - loss: 0.9954
Epoch 15/38
59/59 - 0s - 7ms/step - accuracy: 0.6641 - loss: 0.9862
Epoch 16/38
59/59 - 0s - 7ms/step - accuracy: 0.6643 - loss: 0.9866
Epoch 17/38
59/59 - 0s - 7ms/step - accuracy: 0.6641 - loss: 0.9838
Epoch 18/38
59/59 - 0s - 7ms/step - accuracy: 0.6684 - loss: 0.9771
Epoch 19/38
59/59 - 0s - 7ms/step - accuracy: 0.6675 - loss: 0.9730
Epoch 20/38
59/59 - 0s - 7ms/step - accuracy: 0.6704 - loss: 0.9724
Epoch 21/38
59/59 - 1s - 10ms/step - accuracy: 0.6736 - loss: 0.9628
Epoch 22/38
59/59 - 1s - 13ms/step - accuracy: 0.6709 - loss: 0.9610
Epoch 23/38
59/59 - 1s - 10ms/step - accuracy: 0.6720 - loss: 0.9585
Epoch 24/38
59/59 - 1s - 12ms/step - accuracy: 0.6728 - loss: 0.9583
Epoch 25/38
59/59 - 1s - 10ms/step - accuracy: 0.6728 - loss: 0.9530
Epoch 26/38
59/59 - 1s - 11ms/step - accuracy: 0.6775 - loss: 0.9517
Epoch 27/38
59/59 - 1s - 11ms/step - accuracy: 0.6738 - loss: 0.9489
Epoch 28/38
59/59 - 1s - 11ms/step - accuracy: 0.6757 - loss: 0.9471
Epoch 29/38
59/59 - 1s - 12ms/step - accuracy: 0.6740 - loss: 0.9434
Epoch 30/38
59/59 - 1s - 12ms/step - accuracy: 0.6796 - loss: 0.9417
Epoch 31/38
59/59 - 1s - 12ms/step - accuracy: 0.6774 - loss: 0.9427
Epoch 32/38
59/59 - 1s - 13ms/step - accuracy: 0.6796 - loss: 0.9369
Epoch 33/38
59/59 - 1s - 13ms/step - accuracy: 0.6812 - loss: 0.9360
Epoch 34/38
59/59 - 1s - 11ms/step - accuracy: 0.6798 - loss: 0.9334
Epoch 35/38
59/59 - 1s - 10ms/step - accuracy: 0.6788 - loss: 0.9301
Epoch 36/38
59/59 - 1s - 11ms/step - accuracy: 0.6841 - loss: 0.9303
Epoch 37/38
59/59 - 1s - 13ms/step - accuracy: 0.6816 - loss: 0.9248
Epoch 38/38
59/59 - 1s - 11ms/step - accuracy: 0.6843 - loss: 0.9214
15/15 - 0s - 22ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

59/59 - 2s - 35ms/step - accuracy: 0.5001 - loss: 1.6250
Epoch 2/38
59/59 - 1s - 11ms/step - accuracy: 0.6324 - loss: 1.1945
Epoch 3/38
59/59 - 1s - 11ms/step - accuracy: 0.6320 - loss: 1.1462
Epoch 4/38
59/59 - 1s - 11ms/step - accuracy: 0.6325 - loss: 1.1203
Epoch 5/38
59/59 - 1s - 10ms/step - accuracy: 0.6320 - loss: 1.1065
Epoch 6/38
59/59 - 1s - 12ms/step - accuracy: 0.6342 - loss: 1.0913
Epoch 7/38
59/59 - 1s - 11ms/step - accuracy: 0.6344 - loss: 1.0806
Epoch 8/38
59/59 - 1s - 12ms/step - accuracy: 0.6376 - loss: 1.0697
Epoch 9/38
59/59 - 1s - 11ms/step - accuracy: 0.6362 - loss: 1.0658
Epoch 10/38
59/59 - 1s - 12ms/step - accuracy: 0.6438 - loss: 1.0533
Epoch 11/38
59/59 - 1s - 12ms/step - accuracy: 0.6457 - loss: 1.0485
Epoch 12/38
59/59 - 1s - 12ms/step - accuracy: 0.6457 - loss: 1.0406
Epoch 13/38
59/59 - 1s - 10ms/step - accuracy: 0.6477 - loss: 1.0349
Epoch 14/38
59/59 - 1s - 11ms/step - accuracy: 0.6461 - loss: 1.0291
Epoch 15/38
59/59 - 1s - 12ms/step - accuracy: 0.6511 - loss: 1.0186
Epoch 16/38
59/59 - 1s - 10ms/step - accuracy: 0.6506 - loss: 1.0176
Epoch 17/38
59/59 - 1s - 11ms/step - accuracy: 0.6513 - loss: 1.0151
Epoch 18/38
59/59 - 1s - 12ms/step - accuracy: 0.6553 - loss: 1.0094
Epoch 19/38
59/59 - 1s - 11ms/step - accuracy: 0.6550 - loss: 1.0030
Epoch 20/38
59/59 - 1s - 12ms/step - accuracy: 0.6527 - loss: 1.0046
Epoch 21/38
59/59 - 1s - 9ms/step - accuracy: 0.6584 - loss: 0.9994
Epoch 22/38
59/59 - 0s - 8ms/step - accuracy: 0.6614 - loss: 0.9966
Epoch 23/38
59/59 - 1s - 10ms/step - accuracy: 0.6633 - loss: 0.9889
Epoch 24/38
59/59 - 0s - 8ms/step - accuracy: 0.6630 - loss: 0.9885
Epoch 25/38
59/59 - 0s - 8ms/step - accuracy: 0.6619 - loss: 0.9836
Epoch 26/38
59/59 - 0s - 8ms/step - accuracy: 0.6637 - loss: 0.9787
Epoch 27/38
59/59 - 0s - 7ms/step - accuracy: 0.6649 - loss: 0.9743
Epoch 28/38
59/59 - 0s - 7ms/step - accuracy: 0.6637 - loss: 0.9775
Epoch 29/38
59/59 - 0s - 8ms/step - accuracy: 0.6646 - loss: 0.9725
Epoch 30/38
59/59 - 0s - 7ms/step - accuracy: 0.6682 - loss: 0.9702
Epoch 31/38
59/59 - 1s - 9ms/step - accuracy: 0.6677 - loss: 0.9644
Epoch 32/38
59/59 - 0s - 8ms/step - accuracy: 0.6706 - loss: 0.9620
Epoch 33/38
59/59 - 1s - 11ms/step - accuracy: 0.6712 - loss: 0.9588
Epoch 34/38
59/59 - 1s - 9ms/step - accuracy: 0.6710 - loss: 0.9564
Epoch 35/38
59/59 - 1s - 11ms/step - accuracy: 0.6718 - loss: 0.9550
Epoch 36/38
59/59 - 1s - 11ms/step - accuracy: 0.6732 - loss: 0.9485
Epoch 37/38
59/59 - 1s - 13ms/step - accuracy: 0.6717 - loss: 0.9500
Epoch 38/38
59/59 - 1s - 10ms/step - accuracy: 0.6750 - loss: 0.9461
15/15 - 0s - 21ms/step
| 3         | 0.6991045 | 51.046298 | 2.5703519 | 1.7970640 | 3.5996410 | 0.5964904 | 237.16033 | 38.226345 | 1.3410482 | 1.1301031 | 0.9488855 | 0.9656320 | 0.2425192 |

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/21
24/24 - 4s - 155ms/step - accuracy: 0.5686 - loss: 2.1727
Epoch 2/21
24/24 - 0s - 15ms/step - accuracy: 0.5735 - loss: 2.1637
Epoch 3/21
24/24 - 0s - 14ms/step - accuracy: 0.5757 - loss: 2.1543
Epoch 4/21
24/24 - 0s - 16ms/step - accuracy: 0.5812 - loss: 2.1472
Epoch 5/21
24/24 - 0s - 14ms/step - accuracy: 0.5846 - loss: 2.1365
Epoch 6/21
24/24 - 0s - 16ms/step - accuracy: 0.5870 - loss: 2.1277
Epoch 7/21
24/24 - 0s - 14ms/step - accuracy: 0.5913 - loss: 2.1177
Epoch 8/21
24/24 - 0s - 15ms/step - accuracy: 0.5952 - loss: 2.1084
Epoch 9/21
24/24 - 0s - 13ms/step - accuracy: 0.5965 - loss: 2.0991
Epoch 10/21
24/24 - 0s - 13ms/step - accuracy: 0.6002 - loss: 2.0899
Epoch 11/21
24/24 - 0s - 13ms/step - accuracy: 0.6021 - loss: 2.0796
Epoch 12/21
24/24 - 0s - 18ms/step - accuracy: 0.6050 - loss: 2.0691
Epoch 13/21
24/24 - 0s - 15ms/step - accuracy: 0.6058 - loss: 2.0602
Epoch 14/21
24/24 - 0s - 14ms/step - accuracy: 0.6085 - loss: 2.0497
Epoch 15/21
24/24 - 0s - 14ms/step - accuracy: 0.6120 - loss: 2.0396
Epoch 16/21
24/24 - 0s - 14ms/step - accuracy: 0.6133 - loss: 2.0294
Epoch 17/21
24/24 - 0s - 15ms/step - accuracy: 0.6159 - loss: 2.0189
Epoch 18/21
24/24 - 0s - 12ms/step - accuracy: 0.6183 - loss: 2.0090
Epoch 19/21
24/24 - 0s - 14ms/step - accuracy: 0.6198 - loss: 1.9985
Epoch 20/21
24/24 - 0s - 13ms/step - accuracy: 0.6210 - loss: 1.9888
Epoch 21/21
24/24 - 0s - 14ms/step - accuracy: 0.6228 - loss: 1.9767
6/6 - 0s - 63ms/step
Epoch 1/21

C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 3s - 136ms/step - accuracy: 0.0227 - loss: 3.0891
Epoch 2/21
24/24 - 0s - 13ms/step - accuracy: 0.0228 - loss: 3.0805
Epoch 3/21
24/24 - 0s - 13ms/step - accuracy: 0.0235 - loss: 3.0716
Epoch 4/21
24/24 - 0s - 15ms/step - accuracy: 0.0247 - loss: 3.0625
Epoch 5/21
24/24 - 0s - 16ms/step - accuracy: 0.0255 - loss: 3.0532
Epoch 6/21
24/24 - 0s - 14ms/step - accuracy: 0.0262 - loss: 3.0439
Epoch 7/21
24/24 - 0s - 18ms/step - accuracy: 0.0274 - loss: 3.0340
Epoch 8/21
24/24 - 0s - 17ms/step - accuracy: 0.0281 - loss: 3.0251
Epoch 9/21
24/24 - 0s - 18ms/step - accuracy: 0.0291 - loss: 3.0148
Epoch 10/21
24/24 - 0s - 15ms/step - accuracy: 0.0306 - loss: 3.0051
Epoch 11/21
24/24 - 0s - 17ms/step - accuracy: 0.0309 - loss: 2.9948
Epoch 12/21
24/24 - 0s - 12ms/step - accuracy: 0.0321 - loss: 2.9841
Epoch 13/21
24/24 - 0s - 12ms/step - accuracy: 0.0338 - loss: 2.9741
Epoch 14/21
24/24 - 0s - 12ms/step - accuracy: 0.0349 - loss: 2.9643
Epoch 15/21
24/24 - 0s - 12ms/step - accuracy: 0.0365 - loss: 2.9534
Epoch 16/21
24/24 - 0s - 11ms/step - accuracy: 0.0390 - loss: 2.9426
Epoch 17/21
24/24 - 0s - 13ms/step - accuracy: 0.0401 - loss: 2.9324
Epoch 18/21
24/24 - 0s - 12ms/step - accuracy: 0.0426 - loss: 2.9215
Epoch 19/21
24/24 - 0s - 13ms/step - accuracy: 0.0450 - loss: 2.9101
Epoch 20/21
24/24 - 0s - 13ms/step - accuracy: 0.0465 - loss: 2.8993
Epoch 21/21
24/24 - 0s - 13ms/step - accuracy: 0.0500 - loss: 2.8881
6/6 - 0s - 54ms/step
Epoch 1/21

C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 3s - 111ms/step - accuracy: 0.0918 - loss: 2.7142
Epoch 2/21
24/24 - 0s - 16ms/step - accuracy: 0.0965 - loss: 2.7033
Epoch 3/21
24/24 - 0s - 16ms/step - accuracy: 0.1004 - loss: 2.6926
Epoch 4/21
24/24 - 0s - 11ms/step - accuracy: 0.1044 - loss: 2.6814
Epoch 5/21
24/24 - 0s - 12ms/step - accuracy: 0.1092 - loss: 2.6698
Epoch 6/21
24/24 - 0s - 13ms/step - accuracy: 0.1130 - loss: 2.6587
Epoch 7/21
24/24 - 0s - 16ms/step - accuracy: 0.1172 - loss: 2.6474
Epoch 8/21
24/24 - 0s - 15ms/step - accuracy: 0.1232 - loss: 2.6353
Epoch 9/21
24/24 - 0s - 12ms/step - accuracy: 0.1298 - loss: 2.6232
Epoch 10/21
24/24 - 0s - 12ms/step - accuracy: 0.1335 - loss: 2.6113
Epoch 11/21
24/24 - 0s - 13ms/step - accuracy: 0.1396 - loss: 2.5989
Epoch 12/21
24/24 - 0s - 15ms/step - accuracy: 0.1463 - loss: 2.5866
Epoch 13/21
24/24 - 0s - 12ms/step - accuracy: 0.1517 - loss: 2.5742
Epoch 14/21
24/24 - 0s - 15ms/step - accuracy: 0.1602 - loss: 2.5620
Epoch 15/21
24/24 - 0s - 13ms/step - accuracy: 0.1654 - loss: 2.5497
Epoch 16/21
24/24 - 0s - 13ms/step - accuracy: 0.1727 - loss: 2.5370
Epoch 17/21
24/24 - 0s - 13ms/step - accuracy: 0.1784 - loss: 2.5237
Epoch 18/21
24/24 - 0s - 15ms/step - accuracy: 0.1853 - loss: 2.5105
Epoch 19/21
24/24 - 0s - 13ms/step - accuracy: 0.1918 - loss: 2.4976
Epoch 20/21
24/24 - 0s - 13ms/step - accuracy: 0.1993 - loss: 2.4848
Epoch 21/21
24/24 - 0s - 14ms/step - accuracy: 0.2065 - loss: 2.4717
6/6 - 0s - 53ms/step
Epoch 1/21

C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 3s - 125ms/step - accuracy: 0.0272 - loss: 2.8271
Epoch 2/21
24/24 - 0s - 16ms/step - accuracy: 0.0282 - loss: 2.8184
Epoch 3/21
24/24 - 0s - 16ms/step - accuracy: 0.0293 - loss: 2.8098
Epoch 4/21
24/24 - 0s - 13ms/step - accuracy: 0.0301 - loss: 2.8009
Epoch 5/21
24/24 - 0s - 15ms/step - accuracy: 0.0315 - loss: 2.7916
Epoch 6/21
24/24 - 0s - 14ms/step - accuracy: 0.0320 - loss: 2.7824
Epoch 7/21
24/24 - 0s - 14ms/step - accuracy: 0.0333 - loss: 2.7729
Epoch 8/21
24/24 - 0s - 15ms/step - accuracy: 0.0344 - loss: 2.7633
Epoch 9/21
24/24 - 0s - 17ms/step - accuracy: 0.0360 - loss: 2.7535
Epoch 10/21
24/24 - 0s - 13ms/step - accuracy: 0.0371 - loss: 2.7437
Epoch 11/21
24/24 - 0s - 13ms/step - accuracy: 0.0391 - loss: 2.7339
Epoch 12/21
24/24 - 0s - 13ms/step - accuracy: 0.0397 - loss: 2.7233
Epoch 13/21
24/24 - 0s - 14ms/step - accuracy: 0.0416 - loss: 2.7132
Epoch 14/21
24/24 - 0s - 17ms/step - accuracy: 0.0439 - loss: 2.7026
Epoch 15/21
24/24 - 0s - 13ms/step - accuracy: 0.0466 - loss: 2.6922
Epoch 16/21
24/24 - 0s - 14ms/step - accuracy: 0.0480 - loss: 2.6815
Epoch 17/21
24/24 - 0s - 13ms/step - accuracy: 0.0502 - loss: 2.6706
Epoch 18/21
24/24 - 0s - 13ms/step - accuracy: 0.0534 - loss: 2.6596
Epoch 19/21
24/24 - 0s - 12ms/step - accuracy: 0.0553 - loss: 2.6484
Epoch 20/21
24/24 - 0s - 12ms/step - accuracy: 0.0581 - loss: 2.6372
Epoch 21/21
24/24 - 0s - 14ms/step - accuracy: 0.0606 - loss: 2.6255
6/6 - 0s - 68ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/21
24/24 - 3s - 141ms/step - accuracy: 0.0898 - loss: 2.7414
Epoch 2/21
24/24 - 0s - 17ms/step - accuracy: 0.0919 - loss: 2.7337
Epoch 3/21
24/24 - 1s - 29ms/step - accuracy: 0.0973 - loss: 2.7259
Epoch 4/21
24/24 - 0s - 17ms/step - accuracy: 0.1012 - loss: 2.7173
Epoch 5/21
24/24 - 0s - 13ms/step - accuracy: 0.1062 - loss: 2.7090
Epoch 6/21
24/24 - 0s - 19ms/step - accuracy: 0.1098 - loss: 2.7003
Epoch 7/21
24/24 - 0s - 18ms/step - accuracy: 0.1143 - loss: 2.6919
Epoch 8/21
24/24 - 0s - 18ms/step - accuracy: 0.1204 - loss: 2.6833
Epoch 9/21
24/24 - 0s - 17ms/step - accuracy: 0.1233 - loss: 2.6742
Epoch 10/21
24/24 - 0s - 18ms/step - accuracy: 0.1295 - loss: 2.6653
Epoch 11/21
24/24 - 0s - 18ms/step - accuracy: 0.1351 - loss: 2.6564
Epoch 12/21
24/24 - 0s - 17ms/step - accuracy: 0.1403 - loss: 2.6474
Epoch 13/21
24/24 - 0s - 17ms/step - accuracy: 0.1461 - loss: 2.6379
Epoch 14/21
24/24 - 0s - 18ms/step - accuracy: 0.1524 - loss: 2.6286
Epoch 15/21
24/24 - 0s - 15ms/step - accuracy: 0.1590 - loss: 2.6189
Epoch 16/21
24/24 - 0s - 20ms/step - accuracy: 0.1643 - loss: 2.6098
Epoch 17/21
24/24 - 0s - 20ms/step - accuracy: 0.1704 - loss: 2.5998
Epoch 18/21
24/24 - 0s - 15ms/step - accuracy: 0.1789 - loss: 2.5902
Epoch 19/21
24/24 - 0s - 16ms/step - accuracy: 0.1845 - loss: 2.5801
Epoch 20/21
24/24 - 0s - 16ms/step - accuracy: 0.1909 - loss: 2.5703
Epoch 21/21
24/24 - 0s - 14ms/step - accuracy: 0.1988 - loss: 2.5603
6/6 - 0s - 71ms/step
| 4         | nan       | 37.415239 | 1.1953442 | 6.1580972 | 3.0810674 | 0.1308178 | 596.14152 | 21.031655 | 2.8186408 | 1.5175599 | 0.6625222 | 0.3117110 | 0.1560204 |

C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 139, in __call__
    score = scorer._score(
            ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 371, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 89, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\utils\_response.py", line 211, in _get_response_values
    y_pred = prediction_method(X)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py", line 1061, in predict
    y_pred = self.target_encoder_.inverse_transform(y_pred)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\utils\transformers.py", line 264, in inverse_transform
    class_predictions = self._final_encoder.inverse_transform(class_predictions)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\pipeline.py", line 957, in inverse_transform
    X = transform.inverse_transform(X, **routed_params[name].inverse_transform)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daxma\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py", line 1665, in inverse_transform
    X_tr[rows_to_update, i] = categories[labels_int]
                              ~~~~~~~~~~^^^^^^^^^^^^
IndexError: index 14 is out of bounds for axis 0 with size 14

  warnings.warn(
C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/38
16/16 - 3s - 158ms/step - accuracy: 0.5047 - loss: 1.7455
Epoch 2/38
16/16 - 0s - 24ms/step - accuracy: 0.6447 - loss: 1.0866
Epoch 3/38
16/16 - 0s - 23ms/step - accuracy: 0.6636 - loss: 1.0252
Epoch 4/38
16/16 - 0s - 25ms/step - accuracy: 0.6728 - loss: 0.9836
Epoch 5/38
16/16 - 0s - 24ms/step - accuracy: 0.6780 - loss: 0.9569
Epoch 6/38
16/16 - 0s - 23ms/step - accuracy: 0.6835 - loss: 0.9340
Epoch 7/38
16/16 - 0s - 24ms/step - accuracy: 0.6914 - loss: 0.9128
Epoch 8/38
16/16 - 0s - 22ms/step - accuracy: 0.6973 - loss: 0.8913
Epoch 9/38
16/16 - 0s - 26ms/step - accuracy: 0.7033 - loss: 0.8737
Epoch 10/38
16/16 - 0s - 23ms/step - accuracy: 0.7094 - loss: 0.8589
Epoch 11/38
16/16 - 0s - 25ms/step - accuracy: 0.7148 - loss: 0.8460
Epoch 12/38
16/16 - 0s - 24ms/step - accuracy: 0.7182 - loss: 0.8344
Epoch 13/38
16/16 - 0s - 24ms/step - accuracy: 0.7205 - loss: 0.8233
Epoch 14/38
16/16 - 0s - 23ms/step - accuracy: 0.7263 - loss: 0.8122
Epoch 15/38
16/16 - 0s - 24ms/step - accuracy: 0.7274 - loss: 0.8043
Epoch 16/38
16/16 - 0s - 23ms/step - accuracy: 0.7304 - loss: 0.7947
Epoch 17/38
16/16 - 0s - 23ms/step - accuracy: 0.7309 - loss: 0.7875
Epoch 18/38
16/16 - 0s - 22ms/step - accuracy: 0.7372 - loss: 0.7812
Epoch 19/38
16/16 - 0s - 23ms/step - accuracy: 0.7393 - loss: 0.7731
Epoch 20/38
16/16 - 0s - 25ms/step - accuracy: 0.7399 - loss: 0.7678
Epoch 21/38
16/16 - 0s - 22ms/step - accuracy: 0.7419 - loss: 0.7607
Epoch 22/38
16/16 - 0s - 24ms/step - accuracy: 0.7440 - loss: 0.7570
Epoch 23/38
16/16 - 0s - 22ms/step - accuracy: 0.7457 - loss: 0.7523
Epoch 24/38
16/16 - 0s - 25ms/step - accuracy: 0.7458 - loss: 0.7510
Epoch 25/38
16/16 - 0s - 25ms/step - accuracy: 0.7447 - loss: 0.7461
Epoch 26/38
16/16 - 0s - 22ms/step - accuracy: 0.7454 - loss: 0.7432
Epoch 27/38
16/16 - 0s - 23ms/step - accuracy: 0.7502 - loss: 0.7344
Epoch 28/38
16/16 - 0s - 24ms/step - accuracy: 0.7463 - loss: 0.7363
Epoch 29/38
16/16 - 0s - 22ms/step - accuracy: 0.7504 - loss: 0.7285
Epoch 30/38
16/16 - 0s - 24ms/step - accuracy: 0.7534 - loss: 0.7247
Epoch 31/38
16/16 - 0s - 25ms/step - accuracy: 0.7488 - loss: 0.7252
Epoch 32/38
16/16 - 0s - 25ms/step - accuracy: 0.7546 - loss: 0.7208
Epoch 33/38
16/16 - 0s - 26ms/step - accuracy: 0.7517 - loss: 0.7218
Epoch 34/38
16/16 - 0s - 21ms/step - accuracy: 0.7549 - loss: 0.7158
Epoch 35/38
16/16 - 0s - 22ms/step - accuracy: 0.7580 - loss: 0.7122
Epoch 36/38
16/16 - 0s - 23ms/step - accuracy: 0.7568 - loss: 0.7096
Epoch 37/38
16/16 - 0s - 24ms/step - accuracy: 0.7560 - loss: 0.7089
Epoch 38/38
16/16 - 0s - 23ms/step - accuracy: 0.7589 - loss: 0.7028
4/4 - 0s - 63ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 217ms/step - accuracy: 0.5621 - loss: 1.5436
Epoch 2/38
16/16 - 0s - 22ms/step - accuracy: 0.6438 - loss: 1.0746
Epoch 3/38
16/16 - 0s - 23ms/step - accuracy: 0.6739 - loss: 1.0291
Epoch 4/38
16/16 - 0s - 23ms/step - accuracy: 0.6698 - loss: 1.0017
Epoch 5/38
16/16 - 0s - 23ms/step - accuracy: 0.6799 - loss: 0.9797
Epoch 6/38
16/16 - 0s - 24ms/step - accuracy: 0.6836 - loss: 0.9598
Epoch 7/38
16/16 - 0s - 22ms/step - accuracy: 0.6884 - loss: 0.9397
Epoch 8/38
16/16 - 0s - 25ms/step - accuracy: 0.6891 - loss: 0.9194
Epoch 9/38
16/16 - 0s - 25ms/step - accuracy: 0.6952 - loss: 0.8997
Epoch 10/38
16/16 - 0s - 23ms/step - accuracy: 0.6979 - loss: 0.8826
Epoch 11/38
16/16 - 0s - 23ms/step - accuracy: 0.7008 - loss: 0.8652
Epoch 12/38
16/16 - 0s - 23ms/step - accuracy: 0.7052 - loss: 0.8517
Epoch 13/38
16/16 - 0s - 25ms/step - accuracy: 0.7119 - loss: 0.8402
Epoch 14/38
16/16 - 0s - 23ms/step - accuracy: 0.7141 - loss: 0.8278
Epoch 15/38
16/16 - 0s - 26ms/step - accuracy: 0.7186 - loss: 0.8189
Epoch 16/38
16/16 - 0s - 24ms/step - accuracy: 0.7234 - loss: 0.8130
Epoch 17/38
16/16 - 0s - 23ms/step - accuracy: 0.7218 - loss: 0.8081
Epoch 18/38
16/16 - 0s - 23ms/step - accuracy: 0.7215 - loss: 0.8005
Epoch 19/38
16/16 - 0s - 26ms/step - accuracy: 0.7275 - loss: 0.7895
Epoch 20/38
16/16 - 0s - 25ms/step - accuracy: 0.7335 - loss: 0.7817
Epoch 21/38
16/16 - 0s - 23ms/step - accuracy: 0.7352 - loss: 0.7765
Epoch 22/38
16/16 - 0s - 26ms/step - accuracy: 0.7345 - loss: 0.7709
Epoch 23/38
16/16 - 0s - 25ms/step - accuracy: 0.7364 - loss: 0.7652
Epoch 24/38
16/16 - 0s - 26ms/step - accuracy: 0.7382 - loss: 0.7619
Epoch 25/38
16/16 - 0s - 24ms/step - accuracy: 0.7404 - loss: 0.7565
Epoch 26/38
16/16 - 0s - 22ms/step - accuracy: 0.7385 - loss: 0.7520
Epoch 27/38
16/16 - 0s - 22ms/step - accuracy: 0.7429 - loss: 0.7471
Epoch 28/38
16/16 - 0s - 22ms/step - accuracy: 0.7437 - loss: 0.7444
Epoch 29/38
16/16 - 0s - 24ms/step - accuracy: 0.7450 - loss: 0.7397
Epoch 30/38
16/16 - 0s - 25ms/step - accuracy: 0.7463 - loss: 0.7345
Epoch 31/38
16/16 - 0s - 23ms/step - accuracy: 0.7457 - loss: 0.7292
Epoch 32/38
16/16 - 0s - 24ms/step - accuracy: 0.7500 - loss: 0.7266
Epoch 33/38
16/16 - 0s - 24ms/step - accuracy: 0.7502 - loss: 0.7245
Epoch 34/38
16/16 - 0s - 22ms/step - accuracy: 0.7512 - loss: 0.7187
Epoch 35/38
16/16 - 0s - 22ms/step - accuracy: 0.7489 - loss: 0.7181
Epoch 36/38
16/16 - 0s - 22ms/step - accuracy: 0.7521 - loss: 0.7147
Epoch 37/38
16/16 - 0s - 23ms/step - accuracy: 0.7528 - loss: 0.7122
Epoch 38/38
16/16 - 0s - 24ms/step - accuracy: 0.7548 - loss: 0.7077
4/4 - 0s - 84ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/38
16/16 - 3s - 175ms/step - accuracy: 0.5670 - loss: 1.6126
Epoch 2/38
16/16 - 0s - 24ms/step - accuracy: 0.6668 - loss: 1.1016
Epoch 3/38
16/16 - 0s - 24ms/step - accuracy: 0.6773 - loss: 1.0121
Epoch 4/38
16/16 - 0s - 23ms/step - accuracy: 0.6817 - loss: 0.9681
Epoch 5/38
16/16 - 0s - 24ms/step - accuracy: 0.6860 - loss: 0.9360
Epoch 6/38
16/16 - 0s - 25ms/step - accuracy: 0.6885 - loss: 0.9089
Epoch 7/38
16/16 - 0s - 25ms/step - accuracy: 0.6931 - loss: 0.8889
Epoch 8/38
16/16 - 0s - 27ms/step - accuracy: 0.6948 - loss: 0.8719
Epoch 9/38
16/16 - 0s - 23ms/step - accuracy: 0.6974 - loss: 0.8607
Epoch 10/38
16/16 - 0s - 25ms/step - accuracy: 0.7071 - loss: 0.8436
Epoch 11/38
16/16 - 0s - 25ms/step - accuracy: 0.7138 - loss: 0.8301
Epoch 12/38
16/16 - 0s - 23ms/step - accuracy: 0.7156 - loss: 0.8197
Epoch 13/38
16/16 - 0s - 23ms/step - accuracy: 0.7211 - loss: 0.8093
Epoch 14/38
16/16 - 0s - 26ms/step - accuracy: 0.7198 - loss: 0.8037
Epoch 15/38
16/16 - 0s - 24ms/step - accuracy: 0.7242 - loss: 0.7970
Epoch 16/38
16/16 - 0s - 26ms/step - accuracy: 0.7273 - loss: 0.7883
Epoch 17/38
16/16 - 0s - 24ms/step - accuracy: 0.7285 - loss: 0.7821
Epoch 18/38
16/16 - 0s - 23ms/step - accuracy: 0.7309 - loss: 0.7768
Epoch 19/38
16/16 - 0s - 24ms/step - accuracy: 0.7325 - loss: 0.7690
Epoch 20/38
16/16 - 0s - 27ms/step - accuracy: 0.7353 - loss: 0.7641
Epoch 21/38
16/16 - 0s - 24ms/step - accuracy: 0.7362 - loss: 0.7609
Epoch 22/38
16/16 - 0s - 25ms/step - accuracy: 0.7365 - loss: 0.7557
Epoch 23/38
16/16 - 0s - 24ms/step - accuracy: 0.7356 - loss: 0.7531
Epoch 24/38
16/16 - 0s - 25ms/step - accuracy: 0.7446 - loss: 0.7447
Epoch 25/38
16/16 - 0s - 22ms/step - accuracy: 0.7439 - loss: 0.7410
Epoch 26/38
16/16 - 0s - 22ms/step - accuracy: 0.7454 - loss: 0.7360
Epoch 27/38
16/16 - 0s - 23ms/step - accuracy: 0.7473 - loss: 0.7322
Epoch 28/38
16/16 - 0s - 26ms/step - accuracy: 0.7489 - loss: 0.7286
Epoch 29/38
16/16 - 0s - 23ms/step - accuracy: 0.7490 - loss: 0.7247
Epoch 30/38
16/16 - 0s - 22ms/step - accuracy: 0.7514 - loss: 0.7212
Epoch 31/38
16/16 - 0s - 22ms/step - accuracy: 0.7531 - loss: 0.7223
Epoch 32/38
16/16 - 0s - 23ms/step - accuracy: 0.7529 - loss: 0.7159
Epoch 33/38
16/16 - 0s - 22ms/step - accuracy: 0.7513 - loss: 0.7122
Epoch 34/38
16/16 - 0s - 24ms/step - accuracy: 0.7553 - loss: 0.7103
Epoch 35/38
16/16 - 0s - 23ms/step - accuracy: 0.7573 - loss: 0.7063
Epoch 36/38
16/16 - 0s - 22ms/step - accuracy: 0.7561 - loss: 0.7034
Epoch 37/38
16/16 - 0s - 23ms/step - accuracy: 0.7581 - loss: 0.6988
Epoch 38/38
16/16 - 0s - 23ms/step - accuracy: 0.7595 - loss: 0.6962
4/4 - 0s - 77ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 176ms/step - accuracy: 0.5442 - loss: 1.6032
Epoch 2/38
16/16 - 0s - 24ms/step - accuracy: 0.6367 - loss: 1.0831
Epoch 3/38
16/16 - 0s - 25ms/step - accuracy: 0.6534 - loss: 1.0229
Epoch 4/38
16/16 - 0s - 24ms/step - accuracy: 0.6654 - loss: 0.9856
Epoch 5/38
16/16 - 0s - 25ms/step - accuracy: 0.6757 - loss: 0.9591
Epoch 6/38
16/16 - 0s - 24ms/step - accuracy: 0.6793 - loss: 0.9361
Epoch 7/38
16/16 - 0s - 24ms/step - accuracy: 0.6871 - loss: 0.9160
Epoch 8/38
16/16 - 0s - 27ms/step - accuracy: 0.6940 - loss: 0.9014
Epoch 9/38
16/16 - 0s - 25ms/step - accuracy: 0.7023 - loss: 0.8801
Epoch 10/38
16/16 - 0s - 24ms/step - accuracy: 0.7083 - loss: 0.8659
Epoch 11/38
16/16 - 0s - 23ms/step - accuracy: 0.7118 - loss: 0.8520
Epoch 12/38
16/16 - 0s - 24ms/step - accuracy: 0.7181 - loss: 0.8400
Epoch 13/38
16/16 - 0s - 23ms/step - accuracy: 0.7229 - loss: 0.8279
Epoch 14/38
16/16 - 0s - 24ms/step - accuracy: 0.7266 - loss: 0.8163
Epoch 15/38
16/16 - 0s - 29ms/step - accuracy: 0.7257 - loss: 0.8098
Epoch 16/38
16/16 - 0s - 25ms/step - accuracy: 0.7287 - loss: 0.8006
Epoch 17/38
16/16 - 0s - 27ms/step - accuracy: 0.7314 - loss: 0.7952
Epoch 18/38
16/16 - 0s - 27ms/step - accuracy: 0.7298 - loss: 0.7935
Epoch 19/38
16/16 - 1s - 34ms/step - accuracy: 0.7340 - loss: 0.7862
Epoch 20/38
16/16 - 0s - 30ms/step - accuracy: 0.7352 - loss: 0.7770
Epoch 21/38
16/16 - 0s - 26ms/step - accuracy: 0.7398 - loss: 0.7702
Epoch 22/38
16/16 - 1s - 37ms/step - accuracy: 0.7416 - loss: 0.7649
Epoch 23/38
16/16 - 0s - 29ms/step - accuracy: 0.7421 - loss: 0.7604
Epoch 24/38
16/16 - 0s - 28ms/step - accuracy: 0.7418 - loss: 0.7557
Epoch 25/38
16/16 - 1s - 37ms/step - accuracy: 0.7447 - loss: 0.7518
Epoch 26/38
16/16 - 1s - 34ms/step - accuracy: 0.7476 - loss: 0.7454
Epoch 27/38
16/16 - 0s - 31ms/step - accuracy: 0.7463 - loss: 0.7432
Epoch 28/38
16/16 - 0s - 28ms/step - accuracy: 0.7528 - loss: 0.7397
Epoch 29/38
16/16 - 0s - 26ms/step - accuracy: 0.7470 - loss: 0.7368
Epoch 30/38
16/16 - 0s - 30ms/step - accuracy: 0.7519 - loss: 0.7315
Epoch 31/38
16/16 - 0s - 29ms/step - accuracy: 0.7539 - loss: 0.7259
Epoch 32/38
16/16 - 0s - 26ms/step - accuracy: 0.7548 - loss: 0.7227
Epoch 33/38
16/16 - 0s - 24ms/step - accuracy: 0.7556 - loss: 0.7223
Epoch 34/38
16/16 - 0s - 30ms/step - accuracy: 0.7564 - loss: 0.7187
Epoch 35/38
16/16 - 0s - 29ms/step - accuracy: 0.7553 - loss: 0.7163
Epoch 36/38
16/16 - 0s - 30ms/step - accuracy: 0.7585 - loss: 0.7142
Epoch 37/38
16/16 - 0s - 29ms/step - accuracy: 0.7560 - loss: 0.7139
Epoch 38/38
16/16 - 0s - 30ms/step - accuracy: 0.7572 - loss: 0.7075
4/4 - 0s - 75ms/step
Epoch 1/38

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

16/16 - 3s - 165ms/step - accuracy: 0.5548 - loss: 1.6802
Epoch 2/38
16/16 - 0s - 29ms/step - accuracy: 0.6399 - loss: 1.1179
Epoch 3/38
16/16 - 0s - 29ms/step - accuracy: 0.6531 - loss: 1.0247
Epoch 4/38
16/16 - 0s - 29ms/step - accuracy: 0.6605 - loss: 0.9915
Epoch 5/38
16/16 - 0s - 25ms/step - accuracy: 0.6611 - loss: 0.9689
Epoch 6/38
16/16 - 0s - 23ms/step - accuracy: 0.6684 - loss: 0.9492
Epoch 7/38
16/16 - 0s - 23ms/step - accuracy: 0.6726 - loss: 0.9297
Epoch 8/38
16/16 - 0s - 24ms/step - accuracy: 0.6763 - loss: 0.9161
Epoch 9/38
16/16 - 1s - 31ms/step - accuracy: 0.6817 - loss: 0.9028
Epoch 10/38
16/16 - 0s - 25ms/step - accuracy: 0.6867 - loss: 0.8897
Epoch 11/38
16/16 - 0s - 30ms/step - accuracy: 0.6919 - loss: 0.8784
Epoch 12/38
16/16 - 0s - 29ms/step - accuracy: 0.6935 - loss: 0.8701
Epoch 13/38
16/16 - 0s - 24ms/step - accuracy: 0.7006 - loss: 0.8592
Epoch 14/38
16/16 - 0s - 27ms/step - accuracy: 0.7020 - loss: 0.8521
Epoch 15/38
16/16 - 0s - 26ms/step - accuracy: 0.7031 - loss: 0.8443
Epoch 16/38
16/16 - 0s - 26ms/step - accuracy: 0.7099 - loss: 0.8364
Epoch 17/38
16/16 - 0s - 27ms/step - accuracy: 0.7089 - loss: 0.8304
Epoch 18/38
16/16 - 0s - 25ms/step - accuracy: 0.7112 - loss: 0.8250
Epoch 19/38
16/16 - 0s - 26ms/step - accuracy: 0.7154 - loss: 0.8181
Epoch 20/38
16/16 - 0s - 26ms/step - accuracy: 0.7159 - loss: 0.8124
Epoch 21/38
16/16 - 0s - 26ms/step - accuracy: 0.7168 - loss: 0.8084
Epoch 22/38
16/16 - 0s - 25ms/step - accuracy: 0.7203 - loss: 0.8013
Epoch 23/38
16/16 - 0s - 26ms/step - accuracy: 0.7201 - loss: 0.8019
Epoch 24/38
16/16 - 0s - 24ms/step - accuracy: 0.7219 - loss: 0.7943
Epoch 25/38
16/16 - 0s - 23ms/step - accuracy: 0.7248 - loss: 0.7920
Epoch 26/38
16/16 - 0s - 24ms/step - accuracy: 0.7244 - loss: 0.7848
Epoch 27/38
16/16 - 0s - 26ms/step - accuracy: 0.7286 - loss: 0.7802
Epoch 28/38
16/16 - 0s - 29ms/step - accuracy: 0.7283 - loss: 0.7755
Epoch 29/38
16/16 - 0s - 27ms/step - accuracy: 0.7315 - loss: 0.7734
Epoch 30/38
16/16 - 1s - 34ms/step - accuracy: 0.7314 - loss: 0.7685
Epoch 31/38
16/16 - 1s - 48ms/step - accuracy: 0.7300 - loss: 0.7677
Epoch 32/38
16/16 - 0s - 24ms/step - accuracy: 0.7317 - loss: 0.7675
Epoch 33/38
16/16 - 0s - 25ms/step - accuracy: 0.7331 - loss: 0.7626
Epoch 34/38
16/16 - 1s - 33ms/step - accuracy: 0.7354 - loss: 0.7564
Epoch 35/38
16/16 - 1s - 32ms/step - accuracy: 0.7341 - loss: 0.7549
Epoch 36/38
16/16 - 1s - 32ms/step - accuracy: 0.7346 - loss: 0.7539
Epoch 37/38
16/16 - 0s - 28ms/step - accuracy: 0.7322 - loss: 0.7570
Epoch 38/38
16/16 - 1s - 34ms/step - accuracy: 0.7389 - loss: 0.7438
4/4 - 0s - 74ms/step
| 5         | 0.7519170 | 59.203925 | 1.3697089 | 8.7262616 | 5.4259297 | 0.9401039 | 915.86188 | 37.936999 | 2.8437484 | 1.1769850 | 0.1959828 | 0.0452272 | 0.0975990 |
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 2s - 113ms/step - accuracy: 0.6423 - loss: nan
Epoch 2/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/24
22/22 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/24
22/22 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/24
22/22 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/24
22/22 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/24
22/22 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
6/6 - 0s - 51ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 2s - 104ms/step - accuracy: 0.6297 - loss: nan
Epoch 2/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/24
22/22 - 1s - 24ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/24
22/22 - 1s - 31ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
6/6 - 0s - 57ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 3s - 115ms/step - accuracy: 0.6246 - loss: nan
Epoch 2/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/24
22/22 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/24
22/22 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/24
22/22 - 0s - 21ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/24
22/22 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/24
22/22 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
6/6 - 0s - 57ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 2s - 113ms/step - accuracy: 0.6359 - loss: nan
Epoch 2/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/24
22/22 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/24
22/22 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/24
22/22 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/24
22/22 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/24
22/22 - 0s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/24
22/22 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/24
22/22 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/24
22/22 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/24
22/22 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
6/6 - 0s - 71ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

22/22 - 2s - 110ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/24
22/22 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/24
22/22 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/24
22/22 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/24
22/22 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/24
22/22 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/24
22/22 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/24
22/22 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/24
22/22 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/24
22/22 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/24
22/22 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/24
22/22 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/24
22/22 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/24
22/22 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
6/6 - 0s - 44ms/step
| 6         | 0.6439693 | 44.980956 | 1.5426980 | 7.4586375 | 2.4972732 | 0.2881251 | 634.15686 | 24.227726 | 2.6043939 | 1.1491012 | 0.9868869 | 0.7722447 | 0.0596147 |
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

54/54 - 3s - 55ms/step - accuracy: 0.5424 - loss: 1.7630
Epoch 2/31
54/54 - 1s - 10ms/step - accuracy: 0.6470 - loss: 1.1175
Epoch 3/31
54/54 - 0s - 7ms/step - accuracy: 0.6669 - loss: 1.0278
Epoch 4/31
54/54 - 0s - 8ms/step - accuracy: 0.6773 - loss: 0.9882
Epoch 5/31
54/54 - 0s - 9ms/step - accuracy: 0.6837 - loss: 0.9591
Epoch 6/31
54/54 - 0s - 9ms/step - accuracy: 0.6894 - loss: 0.9344
Epoch 7/31
54/54 - 0s - 9ms/step - accuracy: 0.6952 - loss: 0.9135
Epoch 8/31
54/54 - 0s - 4ms/step - accuracy: 0.7008 - loss: 0.8952
Epoch 9/31
54/54 - 0s - 5ms/step - accuracy: 0.7052 - loss: 0.8807
Epoch 10/31
54/54 - 0s - 7ms/step - accuracy: 0.7106 - loss: 0.8672
Epoch 11/31
54/54 - 0s - 6ms/step - accuracy: 0.7144 - loss: 0.8548
Epoch 12/31
54/54 - 0s - 6ms/step - accuracy: 0.7170 - loss: 0.8451
Epoch 13/31
54/54 - 0s - 6ms/step - accuracy: 0.7162 - loss: 0.8368
Epoch 14/31
54/54 - 0s - 6ms/step - accuracy: 0.7200 - loss: 0.8288
Epoch 15/31
54/54 - 0s - 5ms/step - accuracy: 0.7223 - loss: 0.8220
Epoch 16/31
54/54 - 0s - 9ms/step - accuracy: 0.7235 - loss: 0.8126
Epoch 17/31
54/54 - 0s - 5ms/step - accuracy: 0.7253 - loss: 0.8056
Epoch 18/31
54/54 - 1s - 9ms/step - accuracy: 0.7283 - loss: 0.7972
Epoch 19/31
54/54 - 0s - 8ms/step - accuracy: 0.7312 - loss: 0.7912
Epoch 20/31
54/54 - 0s - 5ms/step - accuracy: 0.7314 - loss: 0.7840
Epoch 21/31
54/54 - 0s - 4ms/step - accuracy: 0.7324 - loss: 0.7778
Epoch 22/31
54/54 - 0s - 4ms/step - accuracy: 0.7359 - loss: 0.7708
Epoch 23/31
54/54 - 0s - 9ms/step - accuracy: 0.7374 - loss: 0.7629
Epoch 24/31
54/54 - 0s - 9ms/step - accuracy: 0.7399 - loss: 0.7574
Epoch 25/31
54/54 - 0s - 7ms/step - accuracy: 0.7416 - loss: 0.7506
Epoch 26/31
54/54 - 0s - 4ms/step - accuracy: 0.7452 - loss: 0.7443
Epoch 27/31
54/54 - 0s - 4ms/step - accuracy: 0.7474 - loss: 0.7383
Epoch 28/31
54/54 - 0s - 6ms/step - accuracy: 0.7488 - loss: 0.7326
Epoch 29/31
54/54 - 0s - 8ms/step - accuracy: 0.7529 - loss: 0.7286
Epoch 30/31
54/54 - 0s - 6ms/step - accuracy: 0.7521 - loss: 0.7221
Epoch 31/31
54/54 - 0s - 5ms/step - accuracy: 0.7532 - loss: 0.7188
14/14 - 0s - 23ms/step
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

54/54 - 4s - 68ms/step - accuracy: 0.3128 - loss: 2.3019
Epoch 2/31
54/54 - 0s - 8ms/step - accuracy: 0.6144 - loss: 1.2384
Epoch 3/31
54/54 - 0s - 6ms/step - accuracy: 0.6601 - loss: 1.0011
Epoch 4/31
54/54 - 0s - 9ms/step - accuracy: 0.6701 - loss: 0.9472
Epoch 5/31
54/54 - 0s - 7ms/step - accuracy: 0.6803 - loss: 0.9072
Epoch 6/31
54/54 - 0s - 5ms/step - accuracy: 0.6861 - loss: 0.8737
Epoch 7/31
54/54 - 0s - 6ms/step - accuracy: 0.6985 - loss: 0.8443
Epoch 8/31
54/54 - 0s - 6ms/step - accuracy: 0.7094 - loss: 0.8163
Epoch 9/31
54/54 - 0s - 6ms/step - accuracy: 0.7206 - loss: 0.7941
Epoch 10/31
54/54 - 0s - 5ms/step - accuracy: 0.7289 - loss: 0.7752
Epoch 11/31
54/54 - 0s - 5ms/step - accuracy: 0.7319 - loss: 0.7624
Epoch 12/31
54/54 - 0s - 4ms/step - accuracy: 0.7378 - loss: 0.7490
Epoch 13/31
54/54 - 0s - 8ms/step - accuracy: 0.7414 - loss: 0.7392
Epoch 14/31
54/54 - 0s - 6ms/step - accuracy: 0.7463 - loss: 0.7282
Epoch 15/31
54/54 - 0s - 5ms/step - accuracy: 0.7478 - loss: 0.7199
Epoch 16/31
54/54 - 0s - 5ms/step - accuracy: 0.7497 - loss: 0.7094
Epoch 17/31
54/54 - 0s - 6ms/step - accuracy: 0.7528 - loss: 0.7030
Epoch 18/31
54/54 - 0s - 6ms/step - accuracy: 0.7545 - loss: 0.6946
Epoch 19/31
54/54 - 0s - 5ms/step - accuracy: 0.7592 - loss: 0.6894
Epoch 20/31
54/54 - 0s - 5ms/step - accuracy: 0.7611 - loss: 0.6815
Epoch 21/31
54/54 - 0s - 4ms/step - accuracy: 0.7635 - loss: 0.6753
Epoch 22/31
54/54 - 0s - 6ms/step - accuracy: 0.7651 - loss: 0.6691
Epoch 23/31
54/54 - 0s - 9ms/step - accuracy: 0.7680 - loss: 0.6629
Epoch 24/31
54/54 - 0s - 5ms/step - accuracy: 0.7704 - loss: 0.6587
Epoch 25/31
54/54 - 0s - 5ms/step - accuracy: 0.7731 - loss: 0.6509
Epoch 26/31
54/54 - 0s - 4ms/step - accuracy: 0.7725 - loss: 0.6484
Epoch 27/31
54/54 - 0s - 4ms/step - accuracy: 0.7759 - loss: 0.6408
Epoch 28/31
54/54 - 0s - 4ms/step - accuracy: 0.7767 - loss: 0.6393
Epoch 29/31
54/54 - 0s - 9ms/step - accuracy: 0.7770 - loss: 0.6355
Epoch 30/31
54/54 - 0s - 4ms/step - accuracy: 0.7814 - loss: 0.6270
Epoch 31/31
54/54 - 0s - 4ms/step - accuracy: 0.7826 - loss: 0.6235
14/14 - 0s - 27ms/step
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

54/54 - 3s - 54ms/step - accuracy: 0.4409 - loss: 1.9702
Epoch 2/31
54/54 - 0s - 4ms/step - accuracy: 0.6479 - loss: 1.1853
Epoch 3/31
54/54 - 0s - 6ms/step - accuracy: 0.6614 - loss: 1.0690
Epoch 4/31
54/54 - 0s - 6ms/step - accuracy: 0.6673 - loss: 1.0209
Epoch 5/31
54/54 - 0s - 5ms/step - accuracy: 0.6757 - loss: 0.9837
Epoch 6/31
54/54 - 0s - 5ms/step - accuracy: 0.6801 - loss: 0.9523
Epoch 7/31
54/54 - 0s - 6ms/step - accuracy: 0.6854 - loss: 0.9252
Epoch 8/31
54/54 - 0s - 6ms/step - accuracy: 0.6883 - loss: 0.8992
Epoch 9/31
54/54 - 0s - 6ms/step - accuracy: 0.6948 - loss: 0.8765
Epoch 10/31
54/54 - 0s - 6ms/step - accuracy: 0.6980 - loss: 0.8569
Epoch 11/31
54/54 - 0s - 5ms/step - accuracy: 0.7024 - loss: 0.8406
Epoch 12/31
54/54 - 0s - 6ms/step - accuracy: 0.7100 - loss: 0.8255
Epoch 13/31
54/54 - 0s - 6ms/step - accuracy: 0.7168 - loss: 0.8118
Epoch 14/31
54/54 - 0s - 5ms/step - accuracy: 0.7199 - loss: 0.7989
Epoch 15/31
54/54 - 0s - 6ms/step - accuracy: 0.7240 - loss: 0.7854
Epoch 16/31
54/54 - 0s - 6ms/step - accuracy: 0.7269 - loss: 0.7757
Epoch 17/31
54/54 - 0s - 5ms/step - accuracy: 0.7302 - loss: 0.7630
Epoch 18/31
54/54 - 0s - 5ms/step - accuracy: 0.7353 - loss: 0.7528
Epoch 19/31
54/54 - 0s - 5ms/step - accuracy: 0.7397 - loss: 0.7408
Epoch 20/31
54/54 - 0s - 7ms/step - accuracy: 0.7420 - loss: 0.7315
Epoch 21/31
54/54 - 0s - 7ms/step - accuracy: 0.7450 - loss: 0.7215
Epoch 22/31
54/54 - 0s - 8ms/step - accuracy: 0.7505 - loss: 0.7106
Epoch 23/31
54/54 - 0s - 7ms/step - accuracy: 0.7529 - loss: 0.7008
Epoch 24/31
54/54 - 0s - 6ms/step - accuracy: 0.7552 - loss: 0.6925
Epoch 25/31
54/54 - 0s - 5ms/step - accuracy: 0.7635 - loss: 0.6829
Epoch 26/31
54/54 - 0s - 5ms/step - accuracy: 0.7660 - loss: 0.6741
Epoch 27/31
54/54 - 0s - 6ms/step - accuracy: 0.7694 - loss: 0.6663
Epoch 28/31
54/54 - 0s - 6ms/step - accuracy: 0.7710 - loss: 0.6584
Epoch 29/31
54/54 - 0s - 5ms/step - accuracy: 0.7737 - loss: 0.6513
Epoch 30/31
54/54 - 0s - 5ms/step - accuracy: 0.7753 - loss: 0.6441
Epoch 31/31
54/54 - 0s - 6ms/step - accuracy: 0.7758 - loss: 0.6395
14/14 - 0s - 27ms/step
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

54/54 - 3s - 56ms/step - accuracy: 0.4806 - loss: 1.7961
Epoch 2/31
54/54 - 0s - 8ms/step - accuracy: 0.6606 - loss: 1.1149
Epoch 3/31
54/54 - 0s - 9ms/step - accuracy: 0.6679 - loss: 1.0468
Epoch 4/31
54/54 - 1s - 10ms/step - accuracy: 0.6701 - loss: 1.0143
Epoch 5/31
54/54 - 0s - 8ms/step - accuracy: 0.6741 - loss: 0.9883
Epoch 6/31
54/54 - 1s - 9ms/step - accuracy: 0.6765 - loss: 0.9642
Epoch 7/31
54/54 - 0s - 8ms/step - accuracy: 0.6816 - loss: 0.9375
Epoch 8/31
54/54 - 0s - 7ms/step - accuracy: 0.6864 - loss: 0.9090
Epoch 9/31
54/54 - 0s - 9ms/step - accuracy: 0.6927 - loss: 0.8788
Epoch 10/31
54/54 - 0s - 8ms/step - accuracy: 0.7009 - loss: 0.8514
Epoch 11/31
54/54 - 0s - 6ms/step - accuracy: 0.7088 - loss: 0.8287
Epoch 12/31
54/54 - 0s - 5ms/step - accuracy: 0.7149 - loss: 0.8108
Epoch 13/31
54/54 - 1s - 10ms/step - accuracy: 0.7179 - loss: 0.7943
Epoch 14/31
54/54 - 0s - 9ms/step - accuracy: 0.7210 - loss: 0.7802
Epoch 15/31
54/54 - 0s - 5ms/step - accuracy: 0.7277 - loss: 0.7672
Epoch 16/31
54/54 - 0s - 8ms/step - accuracy: 0.7297 - loss: 0.7555
Epoch 17/31
54/54 - 0s - 6ms/step - accuracy: 0.7350 - loss: 0.7433
Epoch 18/31
54/54 - 0s - 7ms/step - accuracy: 0.7398 - loss: 0.7321
Epoch 19/31
54/54 - 1s - 11ms/step - accuracy: 0.7436 - loss: 0.7233
Epoch 20/31
54/54 - 1s - 10ms/step - accuracy: 0.7481 - loss: 0.7132
Epoch 21/31
54/54 - 0s - 9ms/step - accuracy: 0.7494 - loss: 0.7059
Epoch 22/31
54/54 - 1s - 10ms/step - accuracy: 0.7550 - loss: 0.6971
Epoch 23/31
54/54 - 0s - 9ms/step - accuracy: 0.7554 - loss: 0.6905
Epoch 24/31
54/54 - 0s - 6ms/step - accuracy: 0.7582 - loss: 0.6829
Epoch 25/31
54/54 - 0s - 5ms/step - accuracy: 0.7617 - loss: 0.6755
Epoch 26/31
54/54 - 0s - 6ms/step - accuracy: 0.7638 - loss: 0.6704
Epoch 27/31
54/54 - 0s - 5ms/step - accuracy: 0.7620 - loss: 0.6669
Epoch 28/31
54/54 - 0s - 5ms/step - accuracy: 0.7659 - loss: 0.6601
Epoch 29/31
54/54 - 0s - 5ms/step - accuracy: 0.7686 - loss: 0.6550
Epoch 30/31
54/54 - 0s - 5ms/step - accuracy: 0.7704 - loss: 0.6513
Epoch 31/31
54/54 - 0s - 6ms/step - accuracy: 0.7725 - loss: 0.6450
14/14 - 0s - 27ms/step
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

54/54 - 3s - 59ms/step - accuracy: 0.5871 - loss: 1.6957
Epoch 2/31
54/54 - 0s - 5ms/step - accuracy: 0.6577 - loss: 1.1201
Epoch 3/31
54/54 - 0s - 5ms/step - accuracy: 0.6730 - loss: 1.0291
Epoch 4/31
54/54 - 0s - 5ms/step - accuracy: 0.6822 - loss: 0.9783
Epoch 5/31
54/54 - 0s - 5ms/step - accuracy: 0.6919 - loss: 0.9422
Epoch 6/31
54/54 - 0s - 7ms/step - accuracy: 0.7008 - loss: 0.9137
Epoch 7/31
54/54 - 0s - 5ms/step - accuracy: 0.7065 - loss: 0.8899
Epoch 8/31
54/54 - 0s - 5ms/step - accuracy: 0.7118 - loss: 0.8701
Epoch 9/31
54/54 - 0s - 6ms/step - accuracy: 0.7192 - loss: 0.8523
Epoch 10/31
54/54 - 0s - 7ms/step - accuracy: 0.7232 - loss: 0.8365
Epoch 11/31
54/54 - 0s - 7ms/step - accuracy: 0.7288 - loss: 0.8221
Epoch 12/31
54/54 - 0s - 9ms/step - accuracy: 0.7322 - loss: 0.8098
Epoch 13/31
54/54 - 1s - 11ms/step - accuracy: 0.7347 - loss: 0.7978
Epoch 14/31
54/54 - 0s - 6ms/step - accuracy: 0.7359 - loss: 0.7863
Epoch 15/31
54/54 - 0s - 9ms/step - accuracy: 0.7381 - loss: 0.7768
Epoch 16/31
54/54 - 1s - 11ms/step - accuracy: 0.7433 - loss: 0.7670
Epoch 17/31
54/54 - 1s - 11ms/step - accuracy: 0.7435 - loss: 0.7572
Epoch 18/31
54/54 - 1s - 10ms/step - accuracy: 0.7458 - loss: 0.7484
Epoch 19/31
54/54 - 0s - 8ms/step - accuracy: 0.7485 - loss: 0.7393
Epoch 20/31
54/54 - 0s - 8ms/step - accuracy: 0.7502 - loss: 0.7316
Epoch 21/31
54/54 - 1s - 10ms/step - accuracy: 0.7542 - loss: 0.7234
Epoch 22/31
54/54 - 1s - 9ms/step - accuracy: 0.7564 - loss: 0.7157
Epoch 23/31
54/54 - 1s - 10ms/step - accuracy: 0.7573 - loss: 0.7094
Epoch 24/31
54/54 - 0s - 9ms/step - accuracy: 0.7603 - loss: 0.7028
Epoch 25/31
54/54 - 0s - 8ms/step - accuracy: 0.7606 - loss: 0.6960
Epoch 26/31
54/54 - 0s - 7ms/step - accuracy: 0.7626 - loss: 0.6901
Epoch 27/31
54/54 - 0s - 7ms/step - accuracy: 0.7647 - loss: 0.6833
Epoch 28/31
54/54 - 0s - 5ms/step - accuracy: 0.7677 - loss: 0.6771
Epoch 29/31
54/54 - 0s - 6ms/step - accuracy: 0.7680 - loss: 0.6721
Epoch 30/31
54/54 - 0s - 5ms/step - accuracy: 0.7715 - loss: 0.6659
Epoch 31/31
54/54 - 0s - 6ms/step - accuracy: 0.7738 - loss: 0.6611
14/14 - 0s - 25ms/step
| 7         | 0.7671974 | 10.496990 | 2.6309228 | 6.3617160 | 5.1030501 | 0.7735576 | 259.23572 | 30.753971 | 1.2317381 | 2.7262068 | 0.6232981 | 0.3308980 | 0.0190675 |
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 2s - 94ms/step - accuracy: 0.6437 - loss: nan
Epoch 2/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/24
24/24 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/24
24/24 - 1s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/24
24/24 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/24
24/24 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/24
24/24 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
6/6 - 0s - 77ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/24
24/24 - 2s - 88ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/24
24/24 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/24
24/24 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/24
24/24 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/24
24/24 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/24
24/24 - 1s - 21ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/24
24/24 - 0s - 19ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/24
24/24 - 0s - 20ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
6/6 - 0s - 63ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 2s - 94ms/step - accuracy: 0.6440 - loss: nan
Epoch 2/24
24/24 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/24
24/24 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/24
24/24 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/24
24/24 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/24
24/24 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/24
24/24 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/24
24/24 - 0s - 19ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/24
24/24 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/24
24/24 - 0s - 20ms/step - accuracy: 0.6439 - loss: nan
6/6 - 0s - 55ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 2s - 97ms/step - accuracy: 0.6441 - loss: nan
Epoch 2/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 3/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
Epoch 4/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 5/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 6/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 7/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 8/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 9/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 10/24
24/24 - 0s - 18ms/step - accuracy: 0.6440 - loss: nan
Epoch 11/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 12/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 13/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 14/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 15/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 16/24
24/24 - 0s - 16ms/step - accuracy: 0.6440 - loss: nan
Epoch 17/24
24/24 - 0s - 17ms/step - accuracy: 0.6440 - loss: nan
Epoch 18/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 19/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 20/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 21/24
24/24 - 0s - 15ms/step - accuracy: 0.6440 - loss: nan
Epoch 22/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 23/24
24/24 - 0s - 14ms/step - accuracy: 0.6440 - loss: nan
Epoch 24/24
24/24 - 0s - 13ms/step - accuracy: 0.6440 - loss: nan
6/6 - 0s - 81ms/step
Epoch 1/24

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

24/24 - 2s - 101ms/step - accuracy: 0.6439 - loss: nan
Epoch 2/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 3/24
24/24 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 4/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 5/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 6/24
24/24 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 7/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 8/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 9/24
24/24 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 10/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 11/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 12/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 13/24
24/24 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 14/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 15/24
24/24 - 0s - 15ms/step - accuracy: 0.6439 - loss: nan
Epoch 16/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 17/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 18/24
24/24 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 19/24
24/24 - 0s - 17ms/step - accuracy: 0.6439 - loss: nan
Epoch 20/24
24/24 - 0s - 18ms/step - accuracy: 0.6439 - loss: nan
Epoch 21/24
24/24 - 0s - 14ms/step - accuracy: 0.6439 - loss: nan
Epoch 22/24
24/24 - 0s - 16ms/step - accuracy: 0.6439 - loss: nan
Epoch 23/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
Epoch 24/24
24/24 - 0s - 13ms/step - accuracy: 0.6439 - loss: nan
6/6 - 0s - 55ms/step
| 8         | 0.6439693 | 37.988408 | 1.6503666 | 6.5664556 | 4.4629022 | 0.8883406 | 577.77194 | 23.587827 | 2.4264895 | 2.5215700 | 0.5612771 | 0.7709671 | 0.1481386 |

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/29
20/20 - 3s - 164ms/step - accuracy: 0.5439 - loss: 1.5681
Epoch 2/29
20/20 - 0s - 19ms/step - accuracy: 0.6626 - loss: 1.0117
Epoch 3/29
20/20 - 0s - 20ms/step - accuracy: 0.6766 - loss: 0.9364
Epoch 4/29
20/20 - 0s - 20ms/step - accuracy: 0.6963 - loss: 0.8735
Epoch 5/29
20/20 - 0s - 22ms/step - accuracy: 0.7130 - loss: 0.8249
Epoch 6/29
20/20 - 0s - 21ms/step - accuracy: 0.7213 - loss: 0.7879
Epoch 7/29
20/20 - 0s - 22ms/step - accuracy: 0.7344 - loss: 0.7553
Epoch 8/29
20/20 - 0s - 22ms/step - accuracy: 0.7433 - loss: 0.7289
Epoch 9/29
20/20 - 0s - 21ms/step - accuracy: 0.7486 - loss: 0.6999
Epoch 10/29
20/20 - 1s - 38ms/step - accuracy: 0.7591 - loss: 0.6773
Epoch 11/29
20/20 - 0s - 20ms/step - accuracy: 0.7659 - loss: 0.6551
Epoch 12/29
20/20 - 0s - 22ms/step - accuracy: 0.7664 - loss: 0.6457
Epoch 13/29
20/20 - 0s - 22ms/step - accuracy: 0.7791 - loss: 0.6218
Epoch 14/29
20/20 - 0s - 23ms/step - accuracy: 0.7911 - loss: 0.5937
Epoch 15/29
20/20 - 0s - 20ms/step - accuracy: 0.7968 - loss: 0.5787
Epoch 16/29
20/20 - 0s - 22ms/step - accuracy: 0.8030 - loss: 0.5619
Epoch 17/29
20/20 - 0s - 21ms/step - accuracy: 0.8059 - loss: 0.5491
Epoch 18/29
20/20 - 0s - 21ms/step - accuracy: 0.8099 - loss: 0.5399
Epoch 19/29
20/20 - 1s - 27ms/step - accuracy: 0.8171 - loss: 0.5208
Epoch 20/29
20/20 - 0s - 21ms/step - accuracy: 0.8213 - loss: 0.5042
Epoch 21/29
20/20 - 0s - 23ms/step - accuracy: 0.8271 - loss: 0.4908
Epoch 22/29
20/20 - 0s - 21ms/step - accuracy: 0.8324 - loss: 0.4749
Epoch 23/29
20/20 - 0s - 20ms/step - accuracy: 0.8314 - loss: 0.4755
Epoch 24/29
20/20 - 0s - 24ms/step - accuracy: 0.8322 - loss: 0.4650
Epoch 25/29
20/20 - 0s - 23ms/step - accuracy: 0.8415 - loss: 0.4417
Epoch 26/29
20/20 - 0s - 21ms/step - accuracy: 0.8483 - loss: 0.4223
Epoch 27/29
20/20 - 0s - 21ms/step - accuracy: 0.8542 - loss: 0.4083
Epoch 28/29
20/20 - 0s - 22ms/step - accuracy: 0.8571 - loss: 0.3956
Epoch 29/29
20/20 - 0s - 21ms/step - accuracy: 0.8572 - loss: 0.3923
5/5 - 0s - 69ms/step
Epoch 1/29

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 4s - 198ms/step - accuracy: 0.5452 - loss: 1.5091
Epoch 2/29
20/20 - 0s - 20ms/step - accuracy: 0.6612 - loss: 0.9929
Epoch 3/29
20/20 - 0s - 21ms/step - accuracy: 0.6849 - loss: 0.9154
Epoch 4/29
20/20 - 0s - 22ms/step - accuracy: 0.7080 - loss: 0.8503
Epoch 5/29
20/20 - 0s - 23ms/step - accuracy: 0.7307 - loss: 0.7939
Epoch 6/29
20/20 - 0s - 22ms/step - accuracy: 0.7441 - loss: 0.7449
Epoch 7/29
20/20 - 0s - 22ms/step - accuracy: 0.7579 - loss: 0.7110
Epoch 8/29
20/20 - 0s - 22ms/step - accuracy: 0.7635 - loss: 0.6864
Epoch 9/29
20/20 - 0s - 20ms/step - accuracy: 0.7666 - loss: 0.6745
Epoch 10/29
20/20 - 0s - 19ms/step - accuracy: 0.7721 - loss: 0.6528
Epoch 11/29
20/20 - 0s - 20ms/step - accuracy: 0.7796 - loss: 0.6352
Epoch 12/29
20/20 - 0s - 22ms/step - accuracy: 0.7834 - loss: 0.6170
Epoch 13/29
20/20 - 0s - 21ms/step - accuracy: 0.7905 - loss: 0.5998
Epoch 14/29
20/20 - 1s - 25ms/step - accuracy: 0.7933 - loss: 0.5829
Epoch 15/29
20/20 - 0s - 21ms/step - accuracy: 0.7995 - loss: 0.5696
Epoch 16/29
20/20 - 0s - 21ms/step - accuracy: 0.8022 - loss: 0.5536
Epoch 17/29
20/20 - 0s - 21ms/step - accuracy: 0.8081 - loss: 0.5411
Epoch 18/29
20/20 - 0s - 19ms/step - accuracy: 0.8118 - loss: 0.5330
Epoch 19/29
20/20 - 0s - 20ms/step - accuracy: 0.8168 - loss: 0.5125
Epoch 20/29
20/20 - 0s - 21ms/step - accuracy: 0.8217 - loss: 0.5066
Epoch 21/29
20/20 - 0s - 21ms/step - accuracy: 0.8259 - loss: 0.4816
Epoch 22/29
20/20 - 0s - 22ms/step - accuracy: 0.8343 - loss: 0.4657
Epoch 23/29
20/20 - 0s - 23ms/step - accuracy: 0.8290 - loss: 0.4709
Epoch 24/29
20/20 - 0s - 20ms/step - accuracy: 0.8333 - loss: 0.4572
Epoch 25/29
20/20 - 0s - 20ms/step - accuracy: 0.8468 - loss: 0.4263
Epoch 26/29
20/20 - 0s - 20ms/step - accuracy: 0.8492 - loss: 0.4158
Epoch 27/29
20/20 - 0s - 21ms/step - accuracy: 0.8496 - loss: 0.4088
Epoch 28/29
20/20 - 0s - 21ms/step - accuracy: 0.8534 - loss: 0.4052
Epoch 29/29
20/20 - 0s - 19ms/step - accuracy: 0.8591 - loss: 0.3898
5/5 - 0s - 60ms/step
Epoch 1/29

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 172ms/step - accuracy: 0.5752 - loss: 1.4386
Epoch 2/29
20/20 - 0s - 20ms/step - accuracy: 0.6627 - loss: 1.0078
Epoch 3/29
20/20 - 0s - 21ms/step - accuracy: 0.6891 - loss: 0.9138
Epoch 4/29
20/20 - 0s - 23ms/step - accuracy: 0.7158 - loss: 0.8310
Epoch 5/29
20/20 - 0s - 23ms/step - accuracy: 0.7367 - loss: 0.7663
Epoch 6/29
20/20 - 1s - 30ms/step - accuracy: 0.7510 - loss: 0.7230
Epoch 7/29
20/20 - 0s - 21ms/step - accuracy: 0.7656 - loss: 0.6864
Epoch 8/29
20/20 - 0s - 22ms/step - accuracy: 0.7746 - loss: 0.6573
Epoch 9/29
20/20 - 0s - 23ms/step - accuracy: 0.7808 - loss: 0.6292
Epoch 10/29
20/20 - 0s - 20ms/step - accuracy: 0.7832 - loss: 0.6140
Epoch 11/29
20/20 - 0s - 21ms/step - accuracy: 0.7869 - loss: 0.6006
Epoch 12/29
20/20 - 0s - 22ms/step - accuracy: 0.7898 - loss: 0.5845
Epoch 13/29
20/20 - 0s - 21ms/step - accuracy: 0.7947 - loss: 0.5678
Epoch 14/29
20/20 - 1s - 32ms/step - accuracy: 0.7964 - loss: 0.5614
Epoch 15/29
20/20 - 1s - 26ms/step - accuracy: 0.8031 - loss: 0.5483
Epoch 16/29
20/20 - 1s - 28ms/step - accuracy: 0.8070 - loss: 0.5364
Epoch 17/29
20/20 - 0s - 25ms/step - accuracy: 0.8099 - loss: 0.5251
Epoch 18/29
20/20 - 1s - 26ms/step - accuracy: 0.8121 - loss: 0.5221
Epoch 19/29
20/20 - 0s - 23ms/step - accuracy: 0.8189 - loss: 0.4999
Epoch 20/29
20/20 - 0s - 20ms/step - accuracy: 0.8151 - loss: 0.4997
Epoch 21/29
20/20 - 1s - 25ms/step - accuracy: 0.8235 - loss: 0.4905
Epoch 22/29
20/20 - 0s - 25ms/step - accuracy: 0.8279 - loss: 0.4775
Epoch 23/29
20/20 - 0s - 25ms/step - accuracy: 0.8297 - loss: 0.4647
Epoch 24/29
20/20 - 0s - 25ms/step - accuracy: 0.8324 - loss: 0.4609
Epoch 25/29
20/20 - 0s - 22ms/step - accuracy: 0.8317 - loss: 0.4537
Epoch 26/29
20/20 - 0s - 24ms/step - accuracy: 0.8375 - loss: 0.4470
Epoch 27/29
20/20 - 0s - 21ms/step - accuracy: 0.8415 - loss: 0.4357
Epoch 28/29
20/20 - 1s - 26ms/step - accuracy: 0.8414 - loss: 0.4345
Epoch 29/29
20/20 - 1s - 28ms/step - accuracy: 0.8476 - loss: 0.4140
5/5 - 0s - 64ms/step
Epoch 1/29

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 159ms/step - accuracy: 0.4707 - loss: 1.8070
Epoch 2/29
20/20 - 0s - 23ms/step - accuracy: 0.6519 - loss: 1.0349
Epoch 3/29
20/20 - 0s - 21ms/step - accuracy: 0.6889 - loss: 0.9333
Epoch 4/29
20/20 - 0s - 21ms/step - accuracy: 0.7187 - loss: 0.8418
Epoch 5/29
20/20 - 0s - 20ms/step - accuracy: 0.7427 - loss: 0.7707
Epoch 6/29
20/20 - 0s - 22ms/step - accuracy: 0.7569 - loss: 0.7214
Epoch 7/29
20/20 - 1s - 26ms/step - accuracy: 0.7662 - loss: 0.6868
Epoch 8/29
20/20 - 0s - 24ms/step - accuracy: 0.7721 - loss: 0.6617
Epoch 9/29
20/20 - 0s - 24ms/step - accuracy: 0.7773 - loss: 0.6420
Epoch 10/29
20/20 - 0s - 21ms/step - accuracy: 0.7872 - loss: 0.6161
Epoch 11/29
20/20 - 0s - 21ms/step - accuracy: 0.7921 - loss: 0.5984
Epoch 12/29
20/20 - 0s - 21ms/step - accuracy: 0.7983 - loss: 0.5785
Epoch 13/29
20/20 - 0s - 21ms/step - accuracy: 0.8020 - loss: 0.5646
Epoch 14/29
20/20 - 0s - 24ms/step - accuracy: 0.8055 - loss: 0.5499
Epoch 15/29
20/20 - 1s - 32ms/step - accuracy: 0.8110 - loss: 0.5375
Epoch 16/29
20/20 - 0s - 20ms/step - accuracy: 0.8140 - loss: 0.5226
Epoch 17/29
20/20 - 0s - 21ms/step - accuracy: 0.8179 - loss: 0.5114
Epoch 18/29
20/20 - 0s - 21ms/step - accuracy: 0.8197 - loss: 0.5027
Epoch 19/29
20/20 - 0s - 21ms/step - accuracy: 0.8240 - loss: 0.4884
Epoch 20/29
20/20 - 0s - 23ms/step - accuracy: 0.8311 - loss: 0.4739
Epoch 21/29
20/20 - 0s - 22ms/step - accuracy: 0.8354 - loss: 0.4624
Epoch 22/29
20/20 - 0s - 22ms/step - accuracy: 0.8406 - loss: 0.4533
Epoch 23/29
20/20 - 0s - 22ms/step - accuracy: 0.8420 - loss: 0.4405
Epoch 24/29
20/20 - 0s - 21ms/step - accuracy: 0.8458 - loss: 0.4328
Epoch 25/29
20/20 - 0s - 23ms/step - accuracy: 0.8500 - loss: 0.4183
Epoch 26/29
20/20 - 0s - 23ms/step - accuracy: 0.8582 - loss: 0.4026
Epoch 27/29
20/20 - 1s - 29ms/step - accuracy: 0.8620 - loss: 0.3879
Epoch 28/29
20/20 - 0s - 22ms/step - accuracy: 0.8641 - loss: 0.3792
Epoch 29/29
20/20 - 0s - 21ms/step - accuracy: 0.8643 - loss: 0.3731
5/5 - 0s - 67ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/29
20/20 - 3s - 157ms/step - accuracy: 0.5823 - loss: 1.4807
Epoch 2/29
20/20 - 1s - 25ms/step - accuracy: 0.6673 - loss: 0.9946
Epoch 3/29
20/20 - 0s - 25ms/step - accuracy: 0.6845 - loss: 0.9007
Epoch 4/29
20/20 - 0s - 25ms/step - accuracy: 0.7080 - loss: 0.8347
Epoch 5/29
20/20 - 1s - 27ms/step - accuracy: 0.7253 - loss: 0.7863
Epoch 6/29
20/20 - 1s - 28ms/step - accuracy: 0.7397 - loss: 0.7462
Epoch 7/29
20/20 - 1s - 29ms/step - accuracy: 0.7532 - loss: 0.7101
Epoch 8/29
20/20 - 1s - 28ms/step - accuracy: 0.7562 - loss: 0.6962
Epoch 9/29
20/20 - 1s - 27ms/step - accuracy: 0.7638 - loss: 0.6708
Epoch 10/29
20/20 - 1s - 29ms/step - accuracy: 0.7736 - loss: 0.6488
Epoch 11/29
20/20 - 1s - 30ms/step - accuracy: 0.7823 - loss: 0.6210
Epoch 12/29
20/20 - 1s - 31ms/step - accuracy: 0.7877 - loss: 0.6006
Epoch 13/29
20/20 - 1s - 28ms/step - accuracy: 0.7945 - loss: 0.5834
Epoch 14/29
20/20 - 1s - 27ms/step - accuracy: 0.7948 - loss: 0.5730
Epoch 15/29
20/20 - 1s - 28ms/step - accuracy: 0.8005 - loss: 0.5606
Epoch 16/29
20/20 - 1s - 27ms/step - accuracy: 0.8045 - loss: 0.5539
Epoch 17/29
20/20 - 1s - 28ms/step - accuracy: 0.8081 - loss: 0.5324
Epoch 18/29
20/20 - 1s - 36ms/step - accuracy: 0.8153 - loss: 0.5195
Epoch 19/29
20/20 - 1s - 29ms/step - accuracy: 0.8204 - loss: 0.5055
Epoch 20/29
20/20 - 1s - 31ms/step - accuracy: 0.8253 - loss: 0.4896
Epoch 21/29
20/20 - 1s - 29ms/step - accuracy: 0.8334 - loss: 0.4738
Epoch 22/29
20/20 - 1s - 30ms/step - accuracy: 0.8328 - loss: 0.4665
Epoch 23/29
20/20 - 1s - 29ms/step - accuracy: 0.8367 - loss: 0.4574
Epoch 24/29
20/20 - 1s - 30ms/step - accuracy: 0.8402 - loss: 0.4498
Epoch 25/29
20/20 - 1s - 29ms/step - accuracy: 0.8464 - loss: 0.4298
Epoch 26/29
20/20 - 1s - 29ms/step - accuracy: 0.8486 - loss: 0.4251
Epoch 27/29
20/20 - 1s - 29ms/step - accuracy: 0.8415 - loss: 0.4422
Epoch 28/29
20/20 - 1s - 28ms/step - accuracy: 0.8493 - loss: 0.4129
Epoch 29/29
20/20 - 1s - 29ms/step - accuracy: 0.8572 - loss: 0.3948
5/5 - 0s - 79ms/step
| 9         | 0.8402851 | 57.045954 | 1.8550820 | 0.2287721 | 0.7552399 | 0.0411148 | 709.12832 | 29.430679 | 2.0171413 | 2.8151329 | 0.2492922 | 0.4103829 | 0.2266653 |

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/39
17/17 - 4s - 227ms/step - accuracy: 0.5564 - loss: 2.1165
Epoch 2/39
17/17 - 0s - 18ms/step - accuracy: 0.6426 - loss: 1.2664
Epoch 3/39
17/17 - 0s - 18ms/step - accuracy: 0.6440 - loss: 1.1263
Epoch 4/39
17/17 - 0s - 19ms/step - accuracy: 0.6440 - loss: 1.0828
Epoch 5/39
17/17 - 0s - 19ms/step - accuracy: 0.6438 - loss: 1.0558
Epoch 6/39
17/17 - 0s - 19ms/step - accuracy: 0.6450 - loss: 1.0388
Epoch 7/39
17/17 - 0s - 18ms/step - accuracy: 0.6449 - loss: 1.0278
Epoch 8/39
17/17 - 0s - 17ms/step - accuracy: 0.6449 - loss: 1.0183
Epoch 9/39
17/17 - 0s - 18ms/step - accuracy: 0.6463 - loss: 1.0120
Epoch 10/39
17/17 - 0s - 18ms/step - accuracy: 0.6495 - loss: 0.9995
Epoch 11/39
17/17 - 0s - 20ms/step - accuracy: 0.6607 - loss: 0.9828
Epoch 12/39
17/17 - 0s - 20ms/step - accuracy: 0.6625 - loss: 0.9748
Epoch 13/39
17/17 - 0s - 21ms/step - accuracy: 0.6725 - loss: 0.9564
Epoch 14/39
17/17 - 0s - 23ms/step - accuracy: 0.6774 - loss: 0.9428
Epoch 15/39
17/17 - 0s - 21ms/step - accuracy: 0.6804 - loss: 0.9325
Epoch 16/39
17/17 - 0s - 25ms/step - accuracy: 0.6873 - loss: 0.9195
Epoch 17/39
17/17 - 0s - 23ms/step - accuracy: 0.6895 - loss: 0.9094
Epoch 18/39
17/17 - 0s - 22ms/step - accuracy: 0.6926 - loss: 0.9018
Epoch 19/39
17/17 - 0s - 23ms/step - accuracy: 0.6977 - loss: 0.8920
Epoch 20/39
17/17 - 0s - 23ms/step - accuracy: 0.7037 - loss: 0.8812
Epoch 21/39
17/17 - 0s - 22ms/step - accuracy: 0.7066 - loss: 0.8733
Epoch 22/39
17/17 - 0s - 24ms/step - accuracy: 0.7113 - loss: 0.8598
Epoch 23/39
17/17 - 0s - 23ms/step - accuracy: 0.7167 - loss: 0.8522
Epoch 24/39
17/17 - 0s - 23ms/step - accuracy: 0.7180 - loss: 0.8449
Epoch 25/39
17/17 - 0s - 21ms/step - accuracy: 0.7194 - loss: 0.8375
Epoch 26/39
17/17 - 0s - 24ms/step - accuracy: 0.7244 - loss: 0.8260
Epoch 27/39
17/17 - 0s - 23ms/step - accuracy: 0.7297 - loss: 0.8152
Epoch 28/39
17/17 - 0s - 21ms/step - accuracy: 0.7333 - loss: 0.8086
Epoch 29/39
17/17 - 0s - 23ms/step - accuracy: 0.7363 - loss: 0.7997
Epoch 30/39
17/17 - 0s - 22ms/step - accuracy: 0.7385 - loss: 0.7942
Epoch 31/39
17/17 - 0s - 23ms/step - accuracy: 0.7436 - loss: 0.7820
Epoch 32/39
17/17 - 0s - 27ms/step - accuracy: 0.7428 - loss: 0.7774
Epoch 33/39
17/17 - 0s - 22ms/step - accuracy: 0.7515 - loss: 0.7660
Epoch 34/39
17/17 - 0s - 24ms/step - accuracy: 0.7509 - loss: 0.7575
Epoch 35/39
17/17 - 0s - 23ms/step - accuracy: 0.7529 - loss: 0.7507
Epoch 36/39
17/17 - 0s - 23ms/step - accuracy: 0.7550 - loss: 0.7449
Epoch 37/39
17/17 - 0s - 22ms/step - accuracy: 0.7587 - loss: 0.7377
Epoch 38/39
17/17 - 0s - 22ms/step - accuracy: 0.7643 - loss: 0.7234
Epoch 39/39
17/17 - 0s - 23ms/step - accuracy: 0.7679 - loss: 0.7111
5/5 - 0s - 99ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/39
17/17 - 4s - 222ms/step - accuracy: 0.5061 - loss: 2.2594
Epoch 2/39
17/17 - 0s - 19ms/step - accuracy: 0.6438 - loss: 1.3329
Epoch 3/39
17/17 - 0s - 18ms/step - accuracy: 0.6440 - loss: 1.1555
Epoch 4/39
17/17 - 0s - 18ms/step - accuracy: 0.6439 - loss: 1.1125
Epoch 5/39
17/17 - 0s - 19ms/step - accuracy: 0.6438 - loss: 1.0820
Epoch 6/39
17/17 - 0s - 16ms/step - accuracy: 0.6439 - loss: 1.0600
Epoch 7/39
17/17 - 0s - 18ms/step - accuracy: 0.6439 - loss: 1.0442
Epoch 8/39
17/17 - 0s - 19ms/step - accuracy: 0.6440 - loss: 1.0322
Epoch 9/39
17/17 - 0s - 19ms/step - accuracy: 0.6433 - loss: 1.0231
Epoch 10/39
17/17 - 0s - 21ms/step - accuracy: 0.6456 - loss: 1.0108
Epoch 11/39
17/17 - 0s - 23ms/step - accuracy: 0.6552 - loss: 0.9937
Epoch 12/39
17/17 - 0s - 22ms/step - accuracy: 0.6565 - loss: 0.9797
Epoch 13/39
17/17 - 0s - 24ms/step - accuracy: 0.6618 - loss: 0.9586
Epoch 14/39
17/17 - 0s - 22ms/step - accuracy: 0.6705 - loss: 0.9383
Epoch 15/39
17/17 - 0s - 23ms/step - accuracy: 0.6780 - loss: 0.9217
Epoch 16/39
17/17 - 0s - 22ms/step - accuracy: 0.6852 - loss: 0.9052
Epoch 17/39
17/17 - 0s - 23ms/step - accuracy: 0.6936 - loss: 0.8925
Epoch 18/39
17/17 - 0s - 22ms/step - accuracy: 0.6997 - loss: 0.8767
Epoch 19/39
17/17 - 0s - 23ms/step - accuracy: 0.7115 - loss: 0.8624
Epoch 20/39
17/17 - 0s - 23ms/step - accuracy: 0.7210 - loss: 0.8465
Epoch 21/39
17/17 - 0s - 25ms/step - accuracy: 0.7247 - loss: 0.8363
Epoch 22/39
17/17 - 0s - 27ms/step - accuracy: 0.7303 - loss: 0.8210
Epoch 23/39
17/17 - 0s - 24ms/step - accuracy: 0.7366 - loss: 0.8067
Epoch 24/39
17/17 - 0s - 23ms/step - accuracy: 0.7422 - loss: 0.7941
Epoch 25/39
17/17 - 0s - 25ms/step - accuracy: 0.7437 - loss: 0.7862
Epoch 26/39
17/17 - 0s - 25ms/step - accuracy: 0.7507 - loss: 0.7704
Epoch 27/39
17/17 - 0s - 21ms/step - accuracy: 0.7546 - loss: 0.7609
Epoch 28/39
17/17 - 0s - 23ms/step - accuracy: 0.7549 - loss: 0.7525
Epoch 29/39
17/17 - 0s - 24ms/step - accuracy: 0.7577 - loss: 0.7443
Epoch 30/39
17/17 - 0s - 22ms/step - accuracy: 0.7605 - loss: 0.7347
Epoch 31/39
17/17 - 0s - 22ms/step - accuracy: 0.7621 - loss: 0.7284
Epoch 32/39
17/17 - 0s - 22ms/step - accuracy: 0.7634 - loss: 0.7182
Epoch 33/39
17/17 - 0s - 22ms/step - accuracy: 0.7649 - loss: 0.7088
Epoch 34/39
17/17 - 0s - 22ms/step - accuracy: 0.7659 - loss: 0.7077
Epoch 35/39
17/17 - 0s - 22ms/step - accuracy: 0.7738 - loss: 0.6866
Epoch 36/39
17/17 - 0s - 22ms/step - accuracy: 0.7748 - loss: 0.6797
Epoch 37/39
17/17 - 0s - 24ms/step - accuracy: 0.7767 - loss: 0.6722
Epoch 38/39
17/17 - 0s - 23ms/step - accuracy: 0.7784 - loss: 0.6639
Epoch 39/39
17/17 - 0s - 24ms/step - accuracy: 0.7807 - loss: 0.6514
5/5 - 0s - 84ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 4s - 213ms/step - accuracy: 0.5482 - loss: 2.1856
Epoch 2/39
17/17 - 0s - 19ms/step - accuracy: 0.6439 - loss: 1.2671
Epoch 3/39
17/17 - 0s - 18ms/step - accuracy: 0.6439 - loss: 1.1569
Epoch 4/39
17/17 - 0s - 17ms/step - accuracy: 0.6439 - loss: 1.1077
Epoch 5/39
17/17 - 0s - 18ms/step - accuracy: 0.6451 - loss: 1.0698
Epoch 6/39
17/17 - 0s - 18ms/step - accuracy: 0.6492 - loss: 1.0424
Epoch 7/39
17/17 - 0s - 20ms/step - accuracy: 0.6546 - loss: 1.0216
Epoch 8/39
17/17 - 0s - 21ms/step - accuracy: 0.6583 - loss: 1.0020
Epoch 9/39
17/17 - 0s - 27ms/step - accuracy: 0.6583 - loss: 0.9803
Epoch 10/39
17/17 - 0s - 23ms/step - accuracy: 0.6588 - loss: 0.9601
Epoch 11/39
17/17 - 0s - 22ms/step - accuracy: 0.6678 - loss: 0.9417
Epoch 12/39
17/17 - 1s - 42ms/step - accuracy: 0.6752 - loss: 0.9196
Epoch 13/39
17/17 - 0s - 24ms/step - accuracy: 0.6814 - loss: 0.9056
Epoch 14/39
17/17 - 0s - 23ms/step - accuracy: 0.6882 - loss: 0.8918
Epoch 15/39
17/17 - 0s - 23ms/step - accuracy: 0.6986 - loss: 0.8737
Epoch 16/39
17/17 - 0s - 21ms/step - accuracy: 0.7026 - loss: 0.8621
Epoch 17/39
17/17 - 0s - 22ms/step - accuracy: 0.7061 - loss: 0.8525
Epoch 18/39
17/17 - 0s - 23ms/step - accuracy: 0.7148 - loss: 0.8400
Epoch 19/39
17/17 - 0s - 24ms/step - accuracy: 0.7219 - loss: 0.8297
Epoch 20/39
17/17 - 0s - 22ms/step - accuracy: 0.7242 - loss: 0.8193
Epoch 21/39
17/17 - 0s - 22ms/step - accuracy: 0.7318 - loss: 0.8067
Epoch 22/39
17/17 - 0s - 22ms/step - accuracy: 0.7365 - loss: 0.7959
Epoch 23/39
17/17 - 0s - 20ms/step - accuracy: 0.7391 - loss: 0.7869
Epoch 24/39
17/17 - 0s - 22ms/step - accuracy: 0.7422 - loss: 0.7806
Epoch 25/39
17/17 - 0s - 21ms/step - accuracy: 0.7491 - loss: 0.7647
Epoch 26/39
17/17 - 0s - 22ms/step - accuracy: 0.7525 - loss: 0.7536
Epoch 27/39
17/17 - 0s - 21ms/step - accuracy: 0.7527 - loss: 0.7496
Epoch 28/39
17/17 - 0s - 22ms/step - accuracy: 0.7534 - loss: 0.7431
Epoch 29/39
17/17 - 0s - 24ms/step - accuracy: 0.7561 - loss: 0.7328
Epoch 30/39
17/17 - 0s - 21ms/step - accuracy: 0.7633 - loss: 0.7187
Epoch 31/39
17/17 - 0s - 20ms/step - accuracy: 0.7640 - loss: 0.7085
Epoch 32/39
17/17 - 0s - 22ms/step - accuracy: 0.7646 - loss: 0.6961
Epoch 33/39
17/17 - 0s - 21ms/step - accuracy: 0.7678 - loss: 0.6868
Epoch 34/39
17/17 - 0s - 21ms/step - accuracy: 0.7713 - loss: 0.6747
Epoch 35/39
17/17 - 0s - 22ms/step - accuracy: 0.7758 - loss: 0.6633
Epoch 36/39
17/17 - 0s - 20ms/step - accuracy: 0.7785 - loss: 0.6502
Epoch 37/39
17/17 - 0s - 21ms/step - accuracy: 0.7808 - loss: 0.6339
Epoch 38/39
17/17 - 0s - 19ms/step - accuracy: 0.7894 - loss: 0.6219
Epoch 39/39
17/17 - 0s - 21ms/step - accuracy: 0.7930 - loss: 0.6043
5/5 - 0s - 83ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 4s - 232ms/step - accuracy: 0.5609 - loss: 2.1223
Epoch 2/39
17/17 - 0s - 15ms/step - accuracy: 0.6440 - loss: 1.2705
Epoch 3/39
17/17 - 0s - 18ms/step - accuracy: 0.6440 - loss: 1.1548
Epoch 4/39
17/17 - 0s - 16ms/step - accuracy: 0.6440 - loss: 1.1081
Epoch 5/39
17/17 - 0s - 17ms/step - accuracy: 0.6442 - loss: 1.0702
Epoch 6/39
17/17 - 0s - 15ms/step - accuracy: 0.6514 - loss: 1.0444
Epoch 7/39
17/17 - 0s - 16ms/step - accuracy: 0.6550 - loss: 1.0280
Epoch 8/39
17/17 - 0s - 21ms/step - accuracy: 0.6545 - loss: 1.0140
Epoch 9/39
17/17 - 0s - 22ms/step - accuracy: 0.6601 - loss: 0.9979
Epoch 10/39
17/17 - 0s - 20ms/step - accuracy: 0.6608 - loss: 0.9814
Epoch 11/39
17/17 - 0s - 19ms/step - accuracy: 0.6611 - loss: 0.9690
Epoch 12/39
17/17 - 0s - 20ms/step - accuracy: 0.6664 - loss: 0.9446
Epoch 13/39
17/17 - 0s - 18ms/step - accuracy: 0.6712 - loss: 0.9230
Epoch 14/39
17/17 - 0s - 18ms/step - accuracy: 0.6799 - loss: 0.9074
Epoch 15/39
17/17 - 0s - 19ms/step - accuracy: 0.6871 - loss: 0.8890
Epoch 16/39
17/17 - 0s - 18ms/step - accuracy: 0.6998 - loss: 0.8693
Epoch 17/39
17/17 - 0s - 19ms/step - accuracy: 0.7083 - loss: 0.8501
Epoch 18/39
17/17 - 0s - 15ms/step - accuracy: 0.7134 - loss: 0.8377
Epoch 19/39
17/17 - 0s - 15ms/step - accuracy: 0.7223 - loss: 0.8222
Epoch 20/39
17/17 - 0s - 18ms/step - accuracy: 0.7279 - loss: 0.8068
Epoch 21/39
17/17 - 0s - 16ms/step - accuracy: 0.7350 - loss: 0.7910
Epoch 22/39
17/17 - 0s - 17ms/step - accuracy: 0.7415 - loss: 0.7794
Epoch 23/39
17/17 - 0s - 17ms/step - accuracy: 0.7477 - loss: 0.7570
Epoch 24/39
17/17 - 0s - 15ms/step - accuracy: 0.7487 - loss: 0.7475
Epoch 25/39
17/17 - 0s - 19ms/step - accuracy: 0.7564 - loss: 0.7253
Epoch 26/39
17/17 - 0s - 19ms/step - accuracy: 0.7600 - loss: 0.7060
Epoch 27/39
17/17 - 0s - 19ms/step - accuracy: 0.7636 - loss: 0.6934
Epoch 28/39
17/17 - 0s - 19ms/step - accuracy: 0.7719 - loss: 0.6688
Epoch 29/39
17/17 - 0s - 17ms/step - accuracy: 0.7741 - loss: 0.6573
Epoch 30/39
17/17 - 0s - 16ms/step - accuracy: 0.7800 - loss: 0.6381
Epoch 31/39
17/17 - 0s - 19ms/step - accuracy: 0.7853 - loss: 0.6197
Epoch 32/39
17/17 - 0s - 19ms/step - accuracy: 0.7935 - loss: 0.6014
Epoch 33/39
17/17 - 0s - 19ms/step - accuracy: 0.7930 - loss: 0.5972
Epoch 34/39
17/17 - 0s - 18ms/step - accuracy: 0.7974 - loss: 0.5815
Epoch 35/39
17/17 - 0s - 19ms/step - accuracy: 0.8020 - loss: 0.5698
Epoch 36/39
17/17 - 0s - 16ms/step - accuracy: 0.8041 - loss: 0.5594
Epoch 37/39
17/17 - 0s - 18ms/step - accuracy: 0.8077 - loss: 0.5491
Epoch 38/39
17/17 - 0s - 18ms/step - accuracy: 0.8131 - loss: 0.5378
Epoch 39/39
17/17 - 0s - 16ms/step - accuracy: 0.8150 - loss: 0.5343
5/5 - 0s - 62ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

17/17 - 3s - 164ms/step - accuracy: 0.5505 - loss: 2.1753
Epoch 2/39
17/17 - 0s - 20ms/step - accuracy: 0.6427 - loss: 1.3090
Epoch 3/39
17/17 - 0s - 16ms/step - accuracy: 0.6439 - loss: 1.1348
Epoch 4/39
17/17 - 0s - 16ms/step - accuracy: 0.6439 - loss: 1.0876
Epoch 5/39
17/17 - 0s - 15ms/step - accuracy: 0.6443 - loss: 1.0591
Epoch 6/39
17/17 - 0s - 16ms/step - accuracy: 0.6458 - loss: 1.0370
Epoch 7/39
17/17 - 0s - 15ms/step - accuracy: 0.6496 - loss: 1.0173
Epoch 8/39
17/17 - 0s - 15ms/step - accuracy: 0.6523 - loss: 0.9947
Epoch 9/39
17/17 - 0s - 16ms/step - accuracy: 0.6517 - loss: 0.9785
Epoch 10/39
17/17 - 0s - 16ms/step - accuracy: 0.6561 - loss: 0.9549
Epoch 11/39
17/17 - 0s - 17ms/step - accuracy: 0.6607 - loss: 0.9288
Epoch 12/39
17/17 - 0s - 16ms/step - accuracy: 0.6748 - loss: 0.9083
Epoch 13/39
17/17 - 0s - 18ms/step - accuracy: 0.6890 - loss: 0.8869
Epoch 14/39
17/17 - 0s - 16ms/step - accuracy: 0.6967 - loss: 0.8713
Epoch 15/39
17/17 - 0s - 18ms/step - accuracy: 0.7049 - loss: 0.8521
Epoch 16/39
17/17 - 0s - 17ms/step - accuracy: 0.7112 - loss: 0.8366
Epoch 17/39
17/17 - 0s - 17ms/step - accuracy: 0.7204 - loss: 0.8237
Epoch 18/39
17/17 - 0s - 16ms/step - accuracy: 0.7246 - loss: 0.8166
Epoch 19/39
17/17 - 0s - 17ms/step - accuracy: 0.7323 - loss: 0.8042
Epoch 20/39
17/17 - 0s - 20ms/step - accuracy: 0.7365 - loss: 0.7901
Epoch 21/39
17/17 - 0s - 17ms/step - accuracy: 0.7402 - loss: 0.7821
Epoch 22/39
17/17 - 0s - 17ms/step - accuracy: 0.7450 - loss: 0.7719
Epoch 23/39
17/17 - 0s - 19ms/step - accuracy: 0.7493 - loss: 0.7612
Epoch 24/39
17/17 - 0s - 18ms/step - accuracy: 0.7524 - loss: 0.7479
Epoch 25/39
17/17 - 0s - 18ms/step - accuracy: 0.7574 - loss: 0.7378
Epoch 26/39
17/17 - 0s - 16ms/step - accuracy: 0.7591 - loss: 0.7239
Epoch 27/39
17/17 - 0s - 18ms/step - accuracy: 0.7626 - loss: 0.7080
Epoch 28/39
17/17 - 0s - 21ms/step - accuracy: 0.7646 - loss: 0.6991
Epoch 29/39
17/17 - 0s - 16ms/step - accuracy: 0.7707 - loss: 0.6842
Epoch 30/39
17/17 - 0s - 18ms/step - accuracy: 0.7713 - loss: 0.6777
Epoch 31/39
17/17 - 0s - 18ms/step - accuracy: 0.7792 - loss: 0.6526
Epoch 32/39
17/17 - 0s - 17ms/step - accuracy: 0.7834 - loss: 0.6364
Epoch 33/39
17/17 - 0s - 18ms/step - accuracy: 0.7821 - loss: 0.6391
Epoch 34/39
17/17 - 0s - 17ms/step - accuracy: 0.7892 - loss: 0.6129
Epoch 35/39
17/17 - 0s - 16ms/step - accuracy: 0.7939 - loss: 0.5925
Epoch 36/39
17/17 - 0s - 16ms/step - accuracy: 0.7979 - loss: 0.5859
Epoch 37/39
17/17 - 0s - 19ms/step - accuracy: 0.8005 - loss: 0.5738
Epoch 38/39
17/17 - 0s - 18ms/step - accuracy: 0.8057 - loss: 0.5621
Epoch 39/39
17/17 - 0s - 17ms/step - accuracy: 0.8069 - loss: 0.5577
5/5 - 0s - 87ms/step
| 10        | 0.7913105 | 30.591834 | 1.1539598 | 2.6077630 | 1.1285490 | 0.9304006 | 846.49630 | 39.002112 | 2.7429211 | 2.6073441 | 0.1865700 | 0.8925589 | 0.1618026 |
Epoch 1/45

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 4s - 137ms/step - accuracy: 0.6215 - loss: 1.4452
Epoch 2/45
26/26 - 1s - 32ms/step - accuracy: 0.6930 - loss: 0.9123
Epoch 3/45
26/26 - 1s - 28ms/step - accuracy: 0.7163 - loss: 0.8102
Epoch 4/45
26/26 - 1s - 28ms/step - accuracy: 0.7375 - loss: 0.7426
Epoch 5/45
26/26 - 1s - 28ms/step - accuracy: 0.7582 - loss: 0.6936
Epoch 6/45
26/26 - 1s - 29ms/step - accuracy: 0.7706 - loss: 0.6529
Epoch 7/45
26/26 - 1s - 29ms/step - accuracy: 0.7833 - loss: 0.6210
Epoch 8/45
26/26 - 1s - 29ms/step - accuracy: 0.7946 - loss: 0.5832
Epoch 9/45
26/26 - 1s - 30ms/step - accuracy: 0.8045 - loss: 0.5595
Epoch 10/45
26/26 - 1s - 28ms/step - accuracy: 0.8115 - loss: 0.5359
Epoch 11/45
26/26 - 1s - 27ms/step - accuracy: 0.8178 - loss: 0.5185
Epoch 12/45
26/26 - 1s - 28ms/step - accuracy: 0.8176 - loss: 0.5116
Epoch 13/45
26/26 - 1s - 30ms/step - accuracy: 0.8320 - loss: 0.4755
Epoch 14/45
26/26 - 1s - 28ms/step - accuracy: 0.8364 - loss: 0.4599
Epoch 15/45
26/26 - 1s - 28ms/step - accuracy: 0.8393 - loss: 0.4443
Epoch 16/45
26/26 - 1s - 29ms/step - accuracy: 0.8486 - loss: 0.4281
Epoch 17/45
26/26 - 1s - 27ms/step - accuracy: 0.8574 - loss: 0.4062
Epoch 18/45
26/26 - 1s - 29ms/step - accuracy: 0.8524 - loss: 0.4125
Epoch 19/45
26/26 - 1s - 27ms/step - accuracy: 0.8639 - loss: 0.3913
Epoch 20/45
26/26 - 1s - 27ms/step - accuracy: 0.8702 - loss: 0.3735
Epoch 21/45
26/26 - 1s - 29ms/step - accuracy: 0.8779 - loss: 0.3546
Epoch 22/45
26/26 - 1s - 27ms/step - accuracy: 0.8831 - loss: 0.3432
Epoch 23/45
26/26 - 1s - 30ms/step - accuracy: 0.8857 - loss: 0.3295
Epoch 24/45
26/26 - 1s - 29ms/step - accuracy: 0.8855 - loss: 0.3326
Epoch 25/45
26/26 - 1s - 29ms/step - accuracy: 0.8837 - loss: 0.3330
Epoch 26/45
26/26 - 1s - 30ms/step - accuracy: 0.8963 - loss: 0.3019
Epoch 27/45
26/26 - 1s - 30ms/step - accuracy: 0.8953 - loss: 0.3043
Epoch 28/45
26/26 - 1s - 30ms/step - accuracy: 0.8965 - loss: 0.2981
Epoch 29/45
26/26 - 1s - 34ms/step - accuracy: 0.9062 - loss: 0.2762
Epoch 30/45
26/26 - 1s - 29ms/step - accuracy: 0.9034 - loss: 0.2832
Epoch 31/45
26/26 - 1s - 30ms/step - accuracy: 0.9102 - loss: 0.2658
Epoch 32/45
26/26 - 1s - 28ms/step - accuracy: 0.9126 - loss: 0.2591
Epoch 33/45
26/26 - 1s - 31ms/step - accuracy: 0.9136 - loss: 0.2552
Epoch 34/45
26/26 - 1s - 28ms/step - accuracy: 0.9135 - loss: 0.2573
Epoch 35/45
26/26 - 1s - 29ms/step - accuracy: 0.9115 - loss: 0.2559
Epoch 36/45
26/26 - 1s - 31ms/step - accuracy: 0.9173 - loss: 0.2443
Epoch 37/45
26/26 - 1s - 30ms/step - accuracy: 0.9167 - loss: 0.2394
Epoch 38/45
26/26 - 1s - 30ms/step - accuracy: 0.9285 - loss: 0.2139
Epoch 39/45
26/26 - 1s - 28ms/step - accuracy: 0.9228 - loss: 0.2254
Epoch 40/45
26/26 - 1s - 32ms/step - accuracy: 0.9234 - loss: 0.2265
Epoch 41/45
26/26 - 1s - 29ms/step - accuracy: 0.9299 - loss: 0.2104
Epoch 42/45
26/26 - 1s - 29ms/step - accuracy: 0.9287 - loss: 0.2180
Epoch 43/45
26/26 - 1s - 30ms/step - accuracy: 0.9224 - loss: 0.2268
Epoch 44/45
26/26 - 1s - 32ms/step - accuracy: 0.9349 - loss: 0.1953
Epoch 45/45
26/26 - 1s - 33ms/step - accuracy: 0.9380 - loss: 0.1891
7/7 - 0s - 59ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/45
26/26 - 4s - 138ms/step - accuracy: 0.5916 - loss: 1.5003
Epoch 2/45
26/26 - 1s - 27ms/step - accuracy: 0.6980 - loss: 0.8987
Epoch 3/45
26/26 - 1s - 28ms/step - accuracy: 0.7244 - loss: 0.7953
Epoch 4/45
26/26 - 1s - 31ms/step - accuracy: 0.7455 - loss: 0.7347
Epoch 5/45
26/26 - 1s - 28ms/step - accuracy: 0.7605 - loss: 0.6884
Epoch 6/45
26/26 - 1s - 29ms/step - accuracy: 0.7739 - loss: 0.6466
Epoch 7/45
26/26 - 1s - 31ms/step - accuracy: 0.7854 - loss: 0.6133
Epoch 8/45
26/26 - 1s - 33ms/step - accuracy: 0.7926 - loss: 0.5835
Epoch 9/45
26/26 - 1s - 30ms/step - accuracy: 0.8043 - loss: 0.5579
Epoch 10/45
26/26 - 1s - 31ms/step - accuracy: 0.8117 - loss: 0.5311
Epoch 11/45
26/26 - 1s - 30ms/step - accuracy: 0.8232 - loss: 0.5023
Epoch 12/45
26/26 - 1s - 31ms/step - accuracy: 0.8276 - loss: 0.4953
Epoch 13/45
26/26 - 1s - 31ms/step - accuracy: 0.8365 - loss: 0.4633
Epoch 14/45
26/26 - 1s - 30ms/step - accuracy: 0.8407 - loss: 0.4480
Epoch 15/45
26/26 - 1s - 29ms/step - accuracy: 0.8531 - loss: 0.4190
Epoch 16/45
26/26 - 1s - 30ms/step - accuracy: 0.8569 - loss: 0.4024
Epoch 17/45
26/26 - 1s - 30ms/step - accuracy: 0.8587 - loss: 0.3984
Epoch 18/45
26/26 - 1s - 32ms/step - accuracy: 0.8670 - loss: 0.3721
Epoch 19/45
26/26 - 1s - 32ms/step - accuracy: 0.8742 - loss: 0.3603
Epoch 20/45
26/26 - 1s - 31ms/step - accuracy: 0.8751 - loss: 0.3530
Epoch 21/45
26/26 - 1s - 30ms/step - accuracy: 0.8821 - loss: 0.3335
Epoch 22/45
26/26 - 1s - 31ms/step - accuracy: 0.8858 - loss: 0.3218
Epoch 23/45
26/26 - 1s - 30ms/step - accuracy: 0.8900 - loss: 0.3156
Epoch 24/45
26/26 - 1s - 29ms/step - accuracy: 0.8940 - loss: 0.3066
Epoch 25/45
26/26 - 1s - 30ms/step - accuracy: 0.8913 - loss: 0.3064
Epoch 26/45
26/26 - 1s - 30ms/step - accuracy: 0.8991 - loss: 0.2882
Epoch 27/45
26/26 - 1s - 34ms/step - accuracy: 0.9014 - loss: 0.2828
Epoch 28/45
26/26 - 1s - 30ms/step - accuracy: 0.9033 - loss: 0.2765
Epoch 29/45
26/26 - 1s - 32ms/step - accuracy: 0.9083 - loss: 0.2643
Epoch 30/45
26/26 - 1s - 30ms/step - accuracy: 0.9028 - loss: 0.2774
Epoch 31/45
26/26 - 1s - 30ms/step - accuracy: 0.9105 - loss: 0.2582
Epoch 32/45
26/26 - 1s - 29ms/step - accuracy: 0.9074 - loss: 0.2622
Epoch 33/45
26/26 - 1s - 31ms/step - accuracy: 0.9127 - loss: 0.2490
Epoch 34/45
26/26 - 1s - 33ms/step - accuracy: 0.9184 - loss: 0.2360
Epoch 35/45
26/26 - 1s - 33ms/step - accuracy: 0.9205 - loss: 0.2260
Epoch 36/45
26/26 - 1s - 33ms/step - accuracy: 0.9241 - loss: 0.2155
Epoch 37/45
26/26 - 1s - 33ms/step - accuracy: 0.9053 - loss: 0.2708
Epoch 38/45
26/26 - 1s - 33ms/step - accuracy: 0.9180 - loss: 0.2285
Epoch 39/45
26/26 - 1s - 31ms/step - accuracy: 0.9266 - loss: 0.2068
Epoch 40/45
26/26 - 1s - 30ms/step - accuracy: 0.9317 - loss: 0.1989
Epoch 41/45
26/26 - 1s - 31ms/step - accuracy: 0.9271 - loss: 0.2077
Epoch 42/45
26/26 - 1s - 30ms/step - accuracy: 0.9244 - loss: 0.2185
Epoch 43/45
26/26 - 1s - 33ms/step - accuracy: 0.9314 - loss: 0.1931
Epoch 44/45
26/26 - 1s - 32ms/step - accuracy: 0.9341 - loss: 0.1897
Epoch 45/45
26/26 - 1s - 36ms/step - accuracy: 0.9341 - loss: 0.1888
7/7 - 0s - 61ms/step
Epoch 1/45

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 3s - 129ms/step - accuracy: 0.5788 - loss: 1.5466
Epoch 2/45
26/26 - 1s - 30ms/step - accuracy: 0.7028 - loss: 0.9025
Epoch 3/45
26/26 - 1s - 32ms/step - accuracy: 0.7345 - loss: 0.7827
Epoch 4/45
26/26 - 1s - 32ms/step - accuracy: 0.7557 - loss: 0.7183
Epoch 5/45
26/26 - 1s - 34ms/step - accuracy: 0.7702 - loss: 0.6747
Epoch 6/45
26/26 - 1s - 31ms/step - accuracy: 0.7786 - loss: 0.6405
Epoch 7/45
26/26 - 1s - 29ms/step - accuracy: 0.7860 - loss: 0.6118
Epoch 8/45
26/26 - 1s - 31ms/step - accuracy: 0.7941 - loss: 0.5909
Epoch 9/45
26/26 - 1s - 31ms/step - accuracy: 0.7991 - loss: 0.5656
Epoch 10/45
26/26 - 1s - 28ms/step - accuracy: 0.8085 - loss: 0.5418
Epoch 11/45
26/26 - 1s - 29ms/step - accuracy: 0.8175 - loss: 0.5202
Epoch 12/45
26/26 - 1s - 29ms/step - accuracy: 0.8181 - loss: 0.5130
Epoch 13/45
26/26 - 1s - 37ms/step - accuracy: 0.8280 - loss: 0.4867
Epoch 14/45
26/26 - 1s - 36ms/step - accuracy: 0.8319 - loss: 0.4711
Epoch 15/45
26/26 - 1s - 34ms/step - accuracy: 0.8396 - loss: 0.4551
Epoch 16/45
26/26 - 1s - 34ms/step - accuracy: 0.8415 - loss: 0.4453
Epoch 17/45
26/26 - 1s - 32ms/step - accuracy: 0.8476 - loss: 0.4246
Epoch 18/45
26/26 - 1s - 31ms/step - accuracy: 0.8563 - loss: 0.4080
Epoch 19/45
26/26 - 1s - 29ms/step - accuracy: 0.8602 - loss: 0.3914
Epoch 20/45
26/26 - 1s - 28ms/step - accuracy: 0.8612 - loss: 0.3908
Epoch 21/45
26/26 - 1s - 28ms/step - accuracy: 0.8652 - loss: 0.3781
Epoch 22/45
26/26 - 1s - 27ms/step - accuracy: 0.8739 - loss: 0.3607
Epoch 23/45
26/26 - 1s - 32ms/step - accuracy: 0.8767 - loss: 0.3550
Epoch 24/45
26/26 - 1s - 31ms/step - accuracy: 0.8794 - loss: 0.3450
Epoch 25/45
26/26 - 1s - 31ms/step - accuracy: 0.8820 - loss: 0.3334
Epoch 26/45
26/26 - 1s - 31ms/step - accuracy: 0.8873 - loss: 0.3189
Epoch 27/45
26/26 - 1s - 38ms/step - accuracy: 0.8916 - loss: 0.3143
Epoch 28/45
26/26 - 1s - 36ms/step - accuracy: 0.8924 - loss: 0.3054
Epoch 29/45
26/26 - 1s - 32ms/step - accuracy: 0.8970 - loss: 0.2924
Epoch 30/45
26/26 - 1s - 31ms/step - accuracy: 0.8988 - loss: 0.2932
Epoch 31/45
26/26 - 1s - 32ms/step - accuracy: 0.9016 - loss: 0.2829
Epoch 32/45
26/26 - 1s - 31ms/step - accuracy: 0.8935 - loss: 0.2944
Epoch 33/45
26/26 - 1s - 32ms/step - accuracy: 0.9072 - loss: 0.2688
Epoch 34/45
26/26 - 1s - 31ms/step - accuracy: 0.9094 - loss: 0.2567
Epoch 35/45
26/26 - 1s - 30ms/step - accuracy: 0.9073 - loss: 0.2656
Epoch 36/45
26/26 - 1s - 32ms/step - accuracy: 0.9089 - loss: 0.2538
Epoch 37/45
26/26 - 1s - 30ms/step - accuracy: 0.9059 - loss: 0.2620
Epoch 38/45
26/26 - 1s - 34ms/step - accuracy: 0.9144 - loss: 0.2426
Epoch 39/45
26/26 - 1s - 30ms/step - accuracy: 0.9164 - loss: 0.2370
Epoch 40/45
26/26 - 1s - 31ms/step - accuracy: 0.9179 - loss: 0.2360
Epoch 41/45
26/26 - 1s - 31ms/step - accuracy: 0.9219 - loss: 0.2205
Epoch 42/45
26/26 - 1s - 33ms/step - accuracy: 0.9167 - loss: 0.2352
Epoch 43/45
26/26 - 1s - 33ms/step - accuracy: 0.9263 - loss: 0.2137
Epoch 44/45
26/26 - 1s - 33ms/step - accuracy: 0.9293 - loss: 0.2032
Epoch 45/45
26/26 - 1s - 36ms/step - accuracy: 0.9256 - loss: 0.2064
7/7 - 0s - 70ms/step
Epoch 1/45

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 4s - 136ms/step - accuracy: 0.6246 - loss: 1.5009
Epoch 2/45
26/26 - 1s - 30ms/step - accuracy: 0.7049 - loss: 0.8958
Epoch 3/45
26/26 - 1s - 30ms/step - accuracy: 0.7349 - loss: 0.7801
Epoch 4/45
26/26 - 1s - 35ms/step - accuracy: 0.7582 - loss: 0.7116
Epoch 5/45
26/26 - 1s - 30ms/step - accuracy: 0.7723 - loss: 0.6619
Epoch 6/45
26/26 - 1s - 32ms/step - accuracy: 0.7854 - loss: 0.6221
Epoch 7/45
26/26 - 1s - 32ms/step - accuracy: 0.7948 - loss: 0.5922
Epoch 8/45
26/26 - 1s - 32ms/step - accuracy: 0.8040 - loss: 0.5612
Epoch 9/45
26/26 - 1s - 33ms/step - accuracy: 0.8111 - loss: 0.5366
Epoch 10/45
26/26 - 1s - 35ms/step - accuracy: 0.8206 - loss: 0.5141
Epoch 11/45
26/26 - 1s - 32ms/step - accuracy: 0.8245 - loss: 0.4973
Epoch 12/45
26/26 - 1s - 37ms/step - accuracy: 0.8241 - loss: 0.4911
Epoch 13/45
26/26 - 1s - 34ms/step - accuracy: 0.8338 - loss: 0.4674
Epoch 14/45
26/26 - 1s - 34ms/step - accuracy: 0.8362 - loss: 0.4537
Epoch 15/45
26/26 - 1s - 33ms/step - accuracy: 0.8455 - loss: 0.4346
Epoch 16/45
26/26 - 1s - 33ms/step - accuracy: 0.8444 - loss: 0.4342
Epoch 17/45
26/26 - 1s - 34ms/step - accuracy: 0.8487 - loss: 0.4168
Epoch 18/45
26/26 - 1s - 31ms/step - accuracy: 0.8575 - loss: 0.4003
Epoch 19/45
26/26 - 1s - 32ms/step - accuracy: 0.8582 - loss: 0.3901
Epoch 20/45
26/26 - 1s - 32ms/step - accuracy: 0.8636 - loss: 0.3835
Epoch 21/45
26/26 - 1s - 32ms/step - accuracy: 0.8694 - loss: 0.3659
Epoch 22/45
26/26 - 1s - 33ms/step - accuracy: 0.8701 - loss: 0.3585
Epoch 23/45
26/26 - 1s - 32ms/step - accuracy: 0.8718 - loss: 0.3506
Epoch 24/45
26/26 - 1s - 31ms/step - accuracy: 0.8793 - loss: 0.3373
Epoch 25/45
26/26 - 1s - 32ms/step - accuracy: 0.8794 - loss: 0.3296
Epoch 26/45
26/26 - 1s - 32ms/step - accuracy: 0.8828 - loss: 0.3210
Epoch 27/45
26/26 - 1s - 34ms/step - accuracy: 0.8866 - loss: 0.3174
Epoch 28/45
26/26 - 1s - 33ms/step - accuracy: 0.8841 - loss: 0.3222
Epoch 29/45
26/26 - 1s - 31ms/step - accuracy: 0.8953 - loss: 0.2942
Epoch 30/45
26/26 - 1s - 32ms/step - accuracy: 0.8956 - loss: 0.2854
Epoch 31/45
26/26 - 1s - 32ms/step - accuracy: 0.9046 - loss: 0.2743
Epoch 32/45
26/26 - 1s - 32ms/step - accuracy: 0.8985 - loss: 0.2799
Epoch 33/45
26/26 - 1s - 32ms/step - accuracy: 0.9046 - loss: 0.2667
Epoch 34/45
26/26 - 1s - 32ms/step - accuracy: 0.9062 - loss: 0.2599
Epoch 35/45
26/26 - 1s - 35ms/step - accuracy: 0.9135 - loss: 0.2494
Epoch 36/45
26/26 - 1s - 33ms/step - accuracy: 0.9118 - loss: 0.2488
Epoch 37/45
26/26 - 1s - 34ms/step - accuracy: 0.9113 - loss: 0.2512
Epoch 38/45
26/26 - 1s - 33ms/step - accuracy: 0.9176 - loss: 0.2341
Epoch 39/45
26/26 - 1s - 32ms/step - accuracy: 0.9224 - loss: 0.2229
Epoch 40/45
26/26 - 1s - 30ms/step - accuracy: 0.9272 - loss: 0.2117
Epoch 41/45
26/26 - 1s - 31ms/step - accuracy: 0.9240 - loss: 0.2158
Epoch 42/45
26/26 - 1s - 32ms/step - accuracy: 0.9256 - loss: 0.2132
Epoch 43/45
26/26 - 1s - 33ms/step - accuracy: 0.9257 - loss: 0.2098
Epoch 44/45
26/26 - 1s - 29ms/step - accuracy: 0.9235 - loss: 0.2168
Epoch 45/45
26/26 - 1s - 32ms/step - accuracy: 0.9290 - loss: 0.2016
7/7 - 0s - 61ms/step
Epoch 1/45

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

26/26 - 4s - 141ms/step - accuracy: 0.5902 - loss: 1.5144
Epoch 2/45
26/26 - 1s - 30ms/step - accuracy: 0.6967 - loss: 0.9164
Epoch 3/45
26/26 - 1s - 30ms/step - accuracy: 0.7193 - loss: 0.8053
Epoch 4/45
26/26 - 1s - 31ms/step - accuracy: 0.7458 - loss: 0.7402
Epoch 5/45
26/26 - 1s - 35ms/step - accuracy: 0.7598 - loss: 0.6918
Epoch 6/45
26/26 - 1s - 34ms/step - accuracy: 0.7749 - loss: 0.6503
Epoch 7/45
26/26 - 1s - 36ms/step - accuracy: 0.7840 - loss: 0.6184
Epoch 8/45
26/26 - 1s - 30ms/step - accuracy: 0.7951 - loss: 0.5841
Epoch 9/45
26/26 - 1s - 30ms/step - accuracy: 0.8028 - loss: 0.5625
Epoch 10/45
26/26 - 1s - 31ms/step - accuracy: 0.8094 - loss: 0.5367
Epoch 11/45
26/26 - 1s - 30ms/step - accuracy: 0.8175 - loss: 0.5182
Epoch 12/45
26/26 - 1s - 30ms/step - accuracy: 0.8211 - loss: 0.4980
Epoch 13/45
26/26 - 1s - 29ms/step - accuracy: 0.8267 - loss: 0.4826
Epoch 14/45
26/26 - 1s - 30ms/step - accuracy: 0.8346 - loss: 0.4579
Epoch 15/45
26/26 - 1s - 30ms/step - accuracy: 0.8402 - loss: 0.4498
Epoch 16/45
26/26 - 1s - 30ms/step - accuracy: 0.8471 - loss: 0.4292
Epoch 17/45
26/26 - 1s - 31ms/step - accuracy: 0.8455 - loss: 0.4285
Epoch 18/45
26/26 - 1s - 30ms/step - accuracy: 0.8567 - loss: 0.4063
Epoch 19/45
26/26 - 1s - 31ms/step - accuracy: 0.8580 - loss: 0.3983
Epoch 20/45
26/26 - 1s - 34ms/step - accuracy: 0.8645 - loss: 0.3788
Epoch 21/45
26/26 - 1s - 35ms/step - accuracy: 0.8683 - loss: 0.3632
Epoch 22/45
26/26 - 1s - 36ms/step - accuracy: 0.8688 - loss: 0.3655
Epoch 23/45
26/26 - 1s - 40ms/step - accuracy: 0.8760 - loss: 0.3423
Epoch 24/45
26/26 - 1s - 33ms/step - accuracy: 0.8782 - loss: 0.3360
Epoch 25/45
26/26 - 1s - 33ms/step - accuracy: 0.8770 - loss: 0.3446
Epoch 26/45
26/26 - 1s - 31ms/step - accuracy: 0.8759 - loss: 0.3343
Epoch 27/45
26/26 - 1s - 31ms/step - accuracy: 0.8899 - loss: 0.3058
Epoch 28/45
26/26 - 1s - 32ms/step - accuracy: 0.8916 - loss: 0.3036
Epoch 29/45
26/26 - 1s - 35ms/step - accuracy: 0.8937 - loss: 0.3004
Epoch 30/45
26/26 - 1s - 42ms/step - accuracy: 0.8951 - loss: 0.2889
Epoch 31/45
26/26 - 1s - 33ms/step - accuracy: 0.8986 - loss: 0.2850
Epoch 32/45
26/26 - 1s - 32ms/step - accuracy: 0.9028 - loss: 0.2744
Epoch 33/45
26/26 - 1s - 33ms/step - accuracy: 0.9036 - loss: 0.2741
Epoch 34/45
26/26 - 1s - 32ms/step - accuracy: 0.9025 - loss: 0.2742
Epoch 35/45
26/26 - 1s - 35ms/step - accuracy: 0.9064 - loss: 0.2662
Epoch 36/45
26/26 - 1s - 33ms/step - accuracy: 0.9107 - loss: 0.2548
Epoch 37/45
26/26 - 1s - 30ms/step - accuracy: 0.9124 - loss: 0.2494
Epoch 38/45
26/26 - 1s - 31ms/step - accuracy: 0.9129 - loss: 0.2510
Epoch 39/45
26/26 - 1s - 32ms/step - accuracy: 0.9162 - loss: 0.2414
Epoch 40/45
26/26 - 1s - 31ms/step - accuracy: 0.9175 - loss: 0.2358
Epoch 41/45
26/26 - 1s - 39ms/step - accuracy: 0.9195 - loss: 0.2286
Epoch 42/45
26/26 - 1s - 39ms/step - accuracy: 0.9207 - loss: 0.2313
Epoch 43/45
26/26 - 1s - 36ms/step - accuracy: 0.9172 - loss: 0.2389
Epoch 44/45
26/26 - 1s - 31ms/step - accuracy: 0.9285 - loss: 0.2069
Epoch 45/45
26/26 - 1s - 30ms/step - accuracy: 0.9265 - loss: 0.2080
7/7 - 0s - 52ms/step
| 11        | 0.8843816 | 82.669613 | 2.7921825 | 2.8620312 | 0.7703634 | 0.2356558 | 541.68623 | 44.540442 | 2.7214611 | 1.0139042 | 0.5107473 | 0.4174110 | 0.0666323 |
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

19/19 - 2s - 114ms/step - accuracy: 0.6011 - loss: 1.4422
Epoch 2/31
19/19 - 0s - 13ms/step - accuracy: 0.6656 - loss: 1.0523
Epoch 3/31
19/19 - 0s - 16ms/step - accuracy: 0.6747 - loss: 0.9657
Epoch 4/31
19/19 - 0s - 17ms/step - accuracy: 0.6804 - loss: 0.9231
Epoch 5/31
19/19 - 0s - 12ms/step - accuracy: 0.6878 - loss: 0.8992
Epoch 6/31
19/19 - 0s - 16ms/step - accuracy: 0.6949 - loss: 0.8748
Epoch 7/31
19/19 - 0s - 14ms/step - accuracy: 0.6990 - loss: 0.8662
Epoch 8/31
19/19 - 0s - 17ms/step - accuracy: 0.7039 - loss: 0.8467
Epoch 9/31
19/19 - 0s - 15ms/step - accuracy: 0.7059 - loss: 0.8392
Epoch 10/31
19/19 - 0s - 18ms/step - accuracy: 0.7121 - loss: 0.8269
Epoch 11/31
19/19 - 0s - 13ms/step - accuracy: 0.7149 - loss: 0.8158
Epoch 12/31
19/19 - 0s - 16ms/step - accuracy: 0.7195 - loss: 0.8060
Epoch 13/31
19/19 - 0s - 10ms/step - accuracy: 0.7185 - loss: 0.7972
Epoch 14/31
19/19 - 0s - 13ms/step - accuracy: 0.7207 - loss: 0.7884
Epoch 15/31
19/19 - 0s - 15ms/step - accuracy: 0.7241 - loss: 0.7802
Epoch 16/31
19/19 - 0s - 11ms/step - accuracy: 0.7339 - loss: 0.7642
Epoch 17/31
19/19 - 0s - 9ms/step - accuracy: 0.7349 - loss: 0.7538
Epoch 18/31
19/19 - 0s - 11ms/step - accuracy: 0.7414 - loss: 0.7426
Epoch 19/31
19/19 - 0s - 14ms/step - accuracy: 0.7427 - loss: 0.7321
Epoch 20/31
19/19 - 0s - 14ms/step - accuracy: 0.7474 - loss: 0.7251
Epoch 21/31
19/19 - 0s - 17ms/step - accuracy: 0.7496 - loss: 0.7209
Epoch 22/31
19/19 - 0s - 15ms/step - accuracy: 0.7516 - loss: 0.7046
Epoch 23/31
19/19 - 0s - 15ms/step - accuracy: 0.7576 - loss: 0.6880
Epoch 24/31
19/19 - 0s - 16ms/step - accuracy: 0.7603 - loss: 0.6877
Epoch 25/31
19/19 - 0s - 11ms/step - accuracy: 0.7640 - loss: 0.6785
Epoch 26/31
19/19 - 0s - 11ms/step - accuracy: 0.7669 - loss: 0.6660
Epoch 27/31
19/19 - 0s - 10ms/step - accuracy: 0.7709 - loss: 0.6617
Epoch 28/31
19/19 - 0s - 10ms/step - accuracy: 0.7708 - loss: 0.6541
Epoch 29/31
19/19 - 0s - 11ms/step - accuracy: 0.7755 - loss: 0.6355
Epoch 30/31
19/19 - 0s - 11ms/step - accuracy: 0.7775 - loss: 0.6383
Epoch 31/31
19/19 - 0s - 9ms/step - accuracy: 0.7753 - loss: 0.6315
5/5 - 0s - 85ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/31
19/19 - 2s - 116ms/step - accuracy: 0.6118 - loss: 1.4404
Epoch 2/31
19/19 - 0s - 15ms/step - accuracy: 0.6545 - loss: 1.0135
Epoch 3/31
19/19 - 0s - 12ms/step - accuracy: 0.6718 - loss: 0.9572
Epoch 4/31
19/19 - 0s - 13ms/step - accuracy: 0.6871 - loss: 0.9083
Epoch 5/31
19/19 - 0s - 13ms/step - accuracy: 0.7072 - loss: 0.8570
Epoch 6/31
19/19 - 0s - 13ms/step - accuracy: 0.7202 - loss: 0.8250
Epoch 7/31
19/19 - 0s - 14ms/step - accuracy: 0.7297 - loss: 0.7983
Epoch 8/31
19/19 - 0s - 13ms/step - accuracy: 0.7383 - loss: 0.7702
Epoch 9/31
19/19 - 0s - 12ms/step - accuracy: 0.7465 - loss: 0.7537
Epoch 10/31
19/19 - 0s - 15ms/step - accuracy: 0.7518 - loss: 0.7385
Epoch 11/31
19/19 - 0s - 14ms/step - accuracy: 0.7548 - loss: 0.7254
Epoch 12/31
19/19 - 0s - 14ms/step - accuracy: 0.7535 - loss: 0.7161
Epoch 13/31
19/19 - 0s - 14ms/step - accuracy: 0.7620 - loss: 0.6973
Epoch 14/31
19/19 - 0s - 12ms/step - accuracy: 0.7620 - loss: 0.6988
Epoch 15/31
19/19 - 0s - 13ms/step - accuracy: 0.7657 - loss: 0.6865
Epoch 16/31
19/19 - 0s - 16ms/step - accuracy: 0.7669 - loss: 0.6760
Epoch 17/31
19/19 - 0s - 15ms/step - accuracy: 0.7711 - loss: 0.6665
Epoch 18/31
19/19 - 0s - 11ms/step - accuracy: 0.7717 - loss: 0.6570
Epoch 19/31
19/19 - 0s - 13ms/step - accuracy: 0.7722 - loss: 0.6561
Epoch 20/31
19/19 - 0s - 15ms/step - accuracy: 0.7761 - loss: 0.6481
Epoch 21/31
19/19 - 0s - 13ms/step - accuracy: 0.7748 - loss: 0.6447
Epoch 22/31
19/19 - 0s - 15ms/step - accuracy: 0.7750 - loss: 0.6388
Epoch 23/31
19/19 - 0s - 13ms/step - accuracy: 0.7786 - loss: 0.6321
Epoch 24/31
19/19 - 0s - 14ms/step - accuracy: 0.7798 - loss: 0.6254
Epoch 25/31
19/19 - 0s - 15ms/step - accuracy: 0.7821 - loss: 0.6186
Epoch 26/31
19/19 - 0s - 15ms/step - accuracy: 0.7829 - loss: 0.6162
Epoch 27/31
19/19 - 0s - 16ms/step - accuracy: 0.7839 - loss: 0.6109
Epoch 28/31
19/19 - 0s - 12ms/step - accuracy: 0.7848 - loss: 0.6076
Epoch 29/31
19/19 - 0s - 13ms/step - accuracy: 0.7900 - loss: 0.5994
Epoch 30/31
19/19 - 0s - 13ms/step - accuracy: 0.7876 - loss: 0.5986
Epoch 31/31
19/19 - 0s - 13ms/step - accuracy: 0.7892 - loss: 0.5987
5/5 - 0s - 59ms/step
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

19/19 - 2s - 111ms/step - accuracy: 0.4946 - loss: 1.6667
Epoch 2/31
19/19 - 0s - 12ms/step - accuracy: 0.6637 - loss: 1.0390
Epoch 3/31
19/19 - 0s - 11ms/step - accuracy: 0.6825 - loss: 0.9512
Epoch 4/31
19/19 - 0s - 15ms/step - accuracy: 0.6937 - loss: 0.9074
Epoch 5/31
19/19 - 0s - 12ms/step - accuracy: 0.7107 - loss: 0.8618
Epoch 6/31
19/19 - 0s - 11ms/step - accuracy: 0.7210 - loss: 0.8373
Epoch 7/31
19/19 - 0s - 10ms/step - accuracy: 0.7249 - loss: 0.8139
Epoch 8/31
19/19 - 0s - 12ms/step - accuracy: 0.7308 - loss: 0.7984
Epoch 9/31
19/19 - 0s - 11ms/step - accuracy: 0.7310 - loss: 0.7812
Epoch 10/31
19/19 - 0s - 11ms/step - accuracy: 0.7389 - loss: 0.7655
Epoch 11/31
19/19 - 0s - 10ms/step - accuracy: 0.7418 - loss: 0.7493
Epoch 12/31
19/19 - 0s - 10ms/step - accuracy: 0.7457 - loss: 0.7464
Epoch 13/31
19/19 - 0s - 10ms/step - accuracy: 0.7504 - loss: 0.7268
Epoch 14/31
19/19 - 0s - 10ms/step - accuracy: 0.7504 - loss: 0.7204
Epoch 15/31
19/19 - 0s - 9ms/step - accuracy: 0.7521 - loss: 0.7110
Epoch 16/31
19/19 - 0s - 11ms/step - accuracy: 0.7580 - loss: 0.6981
Epoch 17/31
19/19 - 0s - 11ms/step - accuracy: 0.7611 - loss: 0.6900
Epoch 18/31
19/19 - 0s - 10ms/step - accuracy: 0.7638 - loss: 0.6799
Epoch 19/31
19/19 - 0s - 10ms/step - accuracy: 0.7666 - loss: 0.6727
Epoch 20/31
19/19 - 0s - 12ms/step - accuracy: 0.7656 - loss: 0.6672
Epoch 21/31
19/19 - 0s - 11ms/step - accuracy: 0.7688 - loss: 0.6598
Epoch 22/31
19/19 - 0s - 12ms/step - accuracy: 0.7722 - loss: 0.6527
Epoch 23/31
19/19 - 0s - 13ms/step - accuracy: 0.7738 - loss: 0.6437
Epoch 24/31
19/19 - 0s - 14ms/step - accuracy: 0.7785 - loss: 0.6341
Epoch 25/31
19/19 - 0s - 15ms/step - accuracy: 0.7774 - loss: 0.6352
Epoch 26/31
19/19 - 0s - 14ms/step - accuracy: 0.7786 - loss: 0.6244
Epoch 27/31
19/19 - 0s - 14ms/step - accuracy: 0.7810 - loss: 0.6201
Epoch 28/31
19/19 - 0s - 14ms/step - accuracy: 0.7827 - loss: 0.6150
Epoch 29/31
19/19 - 0s - 15ms/step - accuracy: 0.7863 - loss: 0.6112
Epoch 30/31
19/19 - 0s - 14ms/step - accuracy: 0.7871 - loss: 0.6036
Epoch 31/31
19/19 - 0s - 15ms/step - accuracy: 0.7879 - loss: 0.6013
5/5 - 0s - 63ms/step
Epoch 1/31

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

19/19 - 2s - 109ms/step - accuracy: 0.6144 - loss: 1.3285
Epoch 2/31
19/19 - 0s - 14ms/step - accuracy: 0.6653 - loss: 1.0125
Epoch 3/31
19/19 - 0s - 14ms/step - accuracy: 0.6719 - loss: 0.9707
Epoch 4/31
19/19 - 0s - 13ms/step - accuracy: 0.6863 - loss: 0.9299
Epoch 5/31
19/19 - 0s - 16ms/step - accuracy: 0.6904 - loss: 0.9087
Epoch 6/31
19/19 - 0s - 16ms/step - accuracy: 0.7013 - loss: 0.8779
Epoch 7/31
19/19 - 0s - 15ms/step - accuracy: 0.7076 - loss: 0.8554
Epoch 8/31
19/19 - 0s - 14ms/step - accuracy: 0.7097 - loss: 0.8420
Epoch 9/31
19/19 - 0s - 12ms/step - accuracy: 0.7188 - loss: 0.8213
Epoch 10/31
19/19 - 0s - 12ms/step - accuracy: 0.7277 - loss: 0.8004
Epoch 11/31
19/19 - 0s - 14ms/step - accuracy: 0.7259 - loss: 0.7983
Epoch 12/31
19/19 - 0s - 12ms/step - accuracy: 0.7326 - loss: 0.7770
Epoch 13/31
19/19 - 0s - 13ms/step - accuracy: 0.7415 - loss: 0.7558
Epoch 14/31
19/19 - 0s - 11ms/step - accuracy: 0.7428 - loss: 0.7547
Epoch 15/31
19/19 - 0s - 14ms/step - accuracy: 0.7524 - loss: 0.7313
Epoch 16/31
19/19 - 0s - 15ms/step - accuracy: 0.7469 - loss: 0.7404
Epoch 17/31
19/19 - 0s - 14ms/step - accuracy: 0.7542 - loss: 0.7188
Epoch 18/31
19/19 - 0s - 14ms/step - accuracy: 0.7606 - loss: 0.7051
Epoch 19/31
19/19 - 0s - 13ms/step - accuracy: 0.7575 - loss: 0.7051
Epoch 20/31
19/19 - 0s - 15ms/step - accuracy: 0.7611 - loss: 0.6926
Epoch 21/31
19/19 - 0s - 15ms/step - accuracy: 0.7654 - loss: 0.6871
Epoch 22/31
19/19 - 0s - 16ms/step - accuracy: 0.7628 - loss: 0.6862
Epoch 23/31
19/19 - 0s - 15ms/step - accuracy: 0.7682 - loss: 0.6740
Epoch 24/31
19/19 - 0s - 11ms/step - accuracy: 0.7715 - loss: 0.6691
Epoch 25/31
19/19 - 0s - 14ms/step - accuracy: 0.7692 - loss: 0.6642
Epoch 26/31
19/19 - 0s - 16ms/step - accuracy: 0.7749 - loss: 0.6539
Epoch 27/31
19/19 - 0s - 14ms/step - accuracy: 0.7727 - loss: 0.6566
Epoch 28/31
19/19 - 0s - 15ms/step - accuracy: 0.7751 - loss: 0.6489
Epoch 29/31
19/19 - 0s - 13ms/step - accuracy: 0.7777 - loss: 0.6387
Epoch 30/31
19/19 - 0s - 10ms/step - accuracy: 0.7783 - loss: 0.6363
Epoch 31/31
19/19 - 0s - 9ms/step - accuracy: 0.7819 - loss: 0.6316
5/5 - 0s - 70ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/31
19/19 - 2s - 116ms/step - accuracy: 0.5100 - loss: 1.6569
Epoch 2/31
19/19 - 0s - 13ms/step - accuracy: 0.6503 - loss: 1.0628
Epoch 3/31
19/19 - 0s - 11ms/step - accuracy: 0.6541 - loss: 1.0002
Epoch 4/31
19/19 - 0s - 13ms/step - accuracy: 0.6633 - loss: 0.9552
Epoch 5/31
19/19 - 0s - 11ms/step - accuracy: 0.6656 - loss: 0.9288
Epoch 6/31
19/19 - 0s - 14ms/step - accuracy: 0.6784 - loss: 0.8978
Epoch 7/31
19/19 - 0s - 15ms/step - accuracy: 0.6885 - loss: 0.8768
Epoch 8/31
19/19 - 0s - 16ms/step - accuracy: 0.6969 - loss: 0.8549
Epoch 9/31
19/19 - 0s - 13ms/step - accuracy: 0.7001 - loss: 0.8358
Epoch 10/31
19/19 - 0s - 10ms/step - accuracy: 0.7063 - loss: 0.8165
Epoch 11/31
19/19 - 0s - 11ms/step - accuracy: 0.7108 - loss: 0.8079
Epoch 12/31
19/19 - 0s - 15ms/step - accuracy: 0.7182 - loss: 0.7851
Epoch 13/31
19/19 - 0s - 13ms/step - accuracy: 0.7209 - loss: 0.7763
Epoch 14/31
19/19 - 0s - 16ms/step - accuracy: 0.7261 - loss: 0.7589
Epoch 15/31
19/19 - 0s - 13ms/step - accuracy: 0.7306 - loss: 0.7524
Epoch 16/31
19/19 - 0s - 15ms/step - accuracy: 0.7347 - loss: 0.7407
Epoch 17/31
19/19 - 0s - 15ms/step - accuracy: 0.7365 - loss: 0.7318
Epoch 18/31
19/19 - 0s - 14ms/step - accuracy: 0.7429 - loss: 0.7165
Epoch 19/31
19/19 - 0s - 15ms/step - accuracy: 0.7460 - loss: 0.7112
Epoch 20/31
19/19 - 0s - 11ms/step - accuracy: 0.7486 - loss: 0.6963
Epoch 21/31
19/19 - 0s - 12ms/step - accuracy: 0.7571 - loss: 0.6861
Epoch 22/31
19/19 - 0s - 13ms/step - accuracy: 0.7562 - loss: 0.6803
Epoch 23/31
19/19 - 0s - 11ms/step - accuracy: 0.7617 - loss: 0.6662
Epoch 24/31
19/19 - 0s - 13ms/step - accuracy: 0.7647 - loss: 0.6626
Epoch 25/31
19/19 - 0s - 12ms/step - accuracy: 0.7640 - loss: 0.6560
Epoch 26/31
19/19 - 0s - 13ms/step - accuracy: 0.7731 - loss: 0.6429
Epoch 27/31
19/19 - 0s - 13ms/step - accuracy: 0.7723 - loss: 0.6418
Epoch 28/31
19/19 - 0s - 14ms/step - accuracy: 0.7711 - loss: 0.6382
Epoch 29/31
19/19 - 0s - 15ms/step - accuracy: 0.7752 - loss: 0.6330
Epoch 30/31
19/19 - 0s - 13ms/step - accuracy: 0.7811 - loss: 0.6237
Epoch 31/31
19/19 - 0s - 14ms/step - accuracy: 0.7821 - loss: 0.6162
5/5 - 0s - 65ms/step
| 12        | 0.7585411 | 20.787883 | 1.6752303 | 8.4861873 | 2.2624205 | 0.5236027 | 762.41516 | 30.908888 | 2.9435641 | 2.9248945 | 0.2517822 | 0.4972485 | 0.0902634 |
Epoch 1/47

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

33/33 - 1s - 42ms/step - accuracy: 0.4170 - loss: 3.2090
Epoch 2/47
33/33 - 0s - 9ms/step - accuracy: 0.5585 - loss: 1.8011
Epoch 3/47
33/33 - 0s - 8ms/step - accuracy: 0.5866 - loss: 1.6249
Epoch 4/47
33/33 - 0s - 10ms/step - accuracy: 0.5934 - loss: 1.5338
Epoch 5/47
33/33 - 0s - 11ms/step - accuracy: 0.5962 - loss: 1.4611
Epoch 6/47
33/33 - 0s - 9ms/step - accuracy: 0.6023 - loss: 1.3993
Epoch 7/47
33/33 - 0s - 10ms/step - accuracy: 0.6041 - loss: 1.3576
Epoch 8/47
33/33 - 0s - 11ms/step - accuracy: 0.6070 - loss: 1.3508
Epoch 9/47
33/33 - 0s - 12ms/step - accuracy: 0.6053 - loss: 1.3125
Epoch 10/47
33/33 - 0s - 9ms/step - accuracy: 0.6107 - loss: 1.2971
Epoch 11/47
33/33 - 0s - 7ms/step - accuracy: 0.6115 - loss: 1.2767
Epoch 12/47
33/33 - 0s - 7ms/step - accuracy: 0.6147 - loss: 1.2592
Epoch 13/47
33/33 - 0s - 7ms/step - accuracy: 0.6191 - loss: 1.2396
Epoch 14/47
33/33 - 0s - 7ms/step - accuracy: 0.6168 - loss: 1.2336
Epoch 15/47
33/33 - 0s - 7ms/step - accuracy: 0.6159 - loss: 1.2185
Epoch 16/47
33/33 - 0s - 6ms/step - accuracy: 0.6175 - loss: 1.2143
Epoch 17/47
33/33 - 0s - 8ms/step - accuracy: 0.6241 - loss: 1.1935
Epoch 18/47
33/33 - 0s - 7ms/step - accuracy: 0.6242 - loss: 1.1783
Epoch 19/47
33/33 - 0s - 8ms/step - accuracy: 0.6226 - loss: 1.1677
Epoch 20/47
33/33 - 0s - 9ms/step - accuracy: 0.6268 - loss: 1.1657
Epoch 21/47
33/33 - 0s - 8ms/step - accuracy: 0.6300 - loss: 1.1575
Epoch 22/47
33/33 - 0s - 9ms/step - accuracy: 0.6275 - loss: 1.1454
Epoch 23/47
33/33 - 0s - 11ms/step - accuracy: 0.6289 - loss: 1.1336
Epoch 24/47
33/33 - 0s - 9ms/step - accuracy: 0.6366 - loss: 1.1231
Epoch 25/47
33/33 - 0s - 9ms/step - accuracy: 0.6303 - loss: 1.1185
Epoch 26/47
33/33 - 0s - 9ms/step - accuracy: 0.6327 - loss: 1.1148
Epoch 27/47
33/33 - 0s - 10ms/step - accuracy: 0.6329 - loss: 1.1070
Epoch 28/47
33/33 - 0s - 8ms/step - accuracy: 0.6364 - loss: 1.1020
Epoch 29/47
33/33 - 0s - 9ms/step - accuracy: 0.6315 - loss: 1.0989
Epoch 30/47
33/33 - 0s - 11ms/step - accuracy: 0.6390 - loss: 1.1026
Epoch 31/47
33/33 - 0s - 11ms/step - accuracy: 0.6441 - loss: 1.0717
Epoch 32/47
33/33 - 0s - 10ms/step - accuracy: 0.6406 - loss: 1.0770
Epoch 33/47
33/33 - 0s - 9ms/step - accuracy: 0.6419 - loss: 1.0732
Epoch 34/47
33/33 - 0s - 11ms/step - accuracy: 0.6457 - loss: 1.0636
Epoch 35/47
33/33 - 0s - 11ms/step - accuracy: 0.6453 - loss: 1.0651
Epoch 36/47
33/33 - 0s - 10ms/step - accuracy: 0.6462 - loss: 1.0658
Epoch 37/47
33/33 - 0s - 10ms/step - accuracy: 0.6457 - loss: 1.0566
Epoch 38/47
33/33 - 0s - 11ms/step - accuracy: 0.6497 - loss: 1.0422
Epoch 39/47
33/33 - 0s - 11ms/step - accuracy: 0.6454 - loss: 1.0508
Epoch 40/47
33/33 - 0s - 9ms/step - accuracy: 0.6491 - loss: 1.0371
Epoch 41/47
33/33 - 0s - 8ms/step - accuracy: 0.6489 - loss: 1.0451
Epoch 42/47
33/33 - 0s - 11ms/step - accuracy: 0.6488 - loss: 1.0370
Epoch 43/47
33/33 - 0s - 11ms/step - accuracy: 0.6482 - loss: 1.0363
Epoch 44/47
33/33 - 0s - 9ms/step - accuracy: 0.6489 - loss: 1.0284
Epoch 45/47
33/33 - 0s - 9ms/step - accuracy: 0.6479 - loss: 1.0263
Epoch 46/47
33/33 - 0s - 11ms/step - accuracy: 0.6525 - loss: 1.0229
Epoch 47/47
33/33 - 0s - 11ms/step - accuracy: 0.6583 - loss: 1.0146
9/9 - 0s - 27ms/step
Epoch 1/47

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

33/33 - 1s - 41ms/step - accuracy: 0.3981 - loss: 2.3288
Epoch 2/47
33/33 - 0s - 10ms/step - accuracy: 0.5634 - loss: 1.5587
Epoch 3/47
33/33 - 0s - 11ms/step - accuracy: 0.5836 - loss: 1.4592
Epoch 4/47
33/33 - 0s - 10ms/step - accuracy: 0.5900 - loss: 1.4088
Epoch 5/47
33/33 - 0s - 7ms/step - accuracy: 0.5979 - loss: 1.3591
Epoch 6/47
33/33 - 0s - 7ms/step - accuracy: 0.5992 - loss: 1.3243
Epoch 7/47
33/33 - 0s - 7ms/step - accuracy: 0.6055 - loss: 1.2943
Epoch 8/47
33/33 - 0s - 9ms/step - accuracy: 0.6096 - loss: 1.2733
Epoch 9/47
33/33 - 0s - 10ms/step - accuracy: 0.6118 - loss: 1.2513
Epoch 10/47
33/33 - 0s - 10ms/step - accuracy: 0.6139 - loss: 1.2264
Epoch 11/47
33/33 - 0s - 9ms/step - accuracy: 0.6167 - loss: 1.2022
Epoch 12/47
33/33 - 0s - 7ms/step - accuracy: 0.6224 - loss: 1.1823
Epoch 13/47
33/33 - 0s - 7ms/step - accuracy: 0.6250 - loss: 1.1633
Epoch 14/47
33/33 - 0s - 7ms/step - accuracy: 0.6243 - loss: 1.1508
Epoch 15/47
33/33 - 0s - 8ms/step - accuracy: 0.6273 - loss: 1.1367
Epoch 16/47
33/33 - 0s - 7ms/step - accuracy: 0.6249 - loss: 1.1348
Epoch 17/47
33/33 - 0s - 7ms/step - accuracy: 0.6295 - loss: 1.1205
Epoch 18/47
33/33 - 0s - 7ms/step - accuracy: 0.6331 - loss: 1.1118
Epoch 19/47
33/33 - 0s - 7ms/step - accuracy: 0.6343 - loss: 1.1014
Epoch 20/47
33/33 - 0s - 7ms/step - accuracy: 0.6378 - loss: 1.0916
Epoch 21/47
33/33 - 0s - 7ms/step - accuracy: 0.6408 - loss: 1.0833
Epoch 22/47
33/33 - 0s - 8ms/step - accuracy: 0.6391 - loss: 1.0795
Epoch 23/47
33/33 - 0s - 8ms/step - accuracy: 0.6387 - loss: 1.0821
Epoch 24/47
33/33 - 0s - 8ms/step - accuracy: 0.6422 - loss: 1.0635
Epoch 25/47
33/33 - 0s - 9ms/step - accuracy: 0.6429 - loss: 1.0643
Epoch 26/47
33/33 - 0s - 8ms/step - accuracy: 0.6439 - loss: 1.0559
Epoch 27/47
33/33 - 0s - 8ms/step - accuracy: 0.6491 - loss: 1.0492
Epoch 28/47
33/33 - 0s - 7ms/step - accuracy: 0.6454 - loss: 1.0437
Epoch 29/47
33/33 - 0s - 9ms/step - accuracy: 0.6482 - loss: 1.0347
Epoch 30/47
33/33 - 0s - 9ms/step - accuracy: 0.6473 - loss: 1.0314
Epoch 31/47
33/33 - 0s - 13ms/step - accuracy: 0.6551 - loss: 1.0258
Epoch 32/47
33/33 - 0s - 7ms/step - accuracy: 0.6526 - loss: 1.0224
Epoch 33/47
33/33 - 0s - 9ms/step - accuracy: 0.6496 - loss: 1.0217
Epoch 34/47
33/33 - 0s - 8ms/step - accuracy: 0.6571 - loss: 1.0107
Epoch 35/47
33/33 - 0s - 8ms/step - accuracy: 0.6520 - loss: 1.0169
Epoch 36/47
33/33 - 0s - 8ms/step - accuracy: 0.6551 - loss: 1.0052
Epoch 37/47
33/33 - 0s - 12ms/step - accuracy: 0.6581 - loss: 1.0028
Epoch 38/47
33/33 - 0s - 12ms/step - accuracy: 0.6584 - loss: 0.9969
Epoch 39/47
33/33 - 0s - 9ms/step - accuracy: 0.6635 - loss: 0.9827
Epoch 40/47
33/33 - 0s - 8ms/step - accuracy: 0.6564 - loss: 0.9916
Epoch 41/47
33/33 - 0s - 9ms/step - accuracy: 0.6613 - loss: 0.9940
Epoch 42/47
33/33 - 0s - 10ms/step - accuracy: 0.6601 - loss: 0.9832
Epoch 43/47
33/33 - 0s - 12ms/step - accuracy: 0.6641 - loss: 0.9843
Epoch 44/47
33/33 - 0s - 9ms/step - accuracy: 0.6661 - loss: 0.9795
Epoch 45/47
33/33 - 0s - 7ms/step - accuracy: 0.6658 - loss: 0.9789
Epoch 46/47
33/33 - 0s - 7ms/step - accuracy: 0.6681 - loss: 0.9696
Epoch 47/47
33/33 - 0s - 8ms/step - accuracy: 0.6691 - loss: 0.9691
9/9 - 0s - 34ms/step
Epoch 1/47

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

33/33 - 2s - 50ms/step - accuracy: 0.3485 - loss: 2.5394
Epoch 2/47
33/33 - 0s - 7ms/step - accuracy: 0.5744 - loss: 1.4656
Epoch 3/47
33/33 - 0s - 7ms/step - accuracy: 0.6032 - loss: 1.3259
Epoch 4/47
33/33 - 0s - 10ms/step - accuracy: 0.6160 - loss: 1.2492
Epoch 5/47
33/33 - 0s - 7ms/step - accuracy: 0.6247 - loss: 1.2170
Epoch 6/47
33/33 - 0s - 7ms/step - accuracy: 0.6312 - loss: 1.1873
Epoch 7/47
33/33 - 0s - 9ms/step - accuracy: 0.6318 - loss: 1.1630
Epoch 8/47
33/33 - 0s - 9ms/step - accuracy: 0.6373 - loss: 1.1407
Epoch 9/47
33/33 - 0s - 9ms/step - accuracy: 0.6391 - loss: 1.1277
Epoch 10/47
33/33 - 0s - 9ms/step - accuracy: 0.6380 - loss: 1.1135
Epoch 11/47
33/33 - 0s - 11ms/step - accuracy: 0.6439 - loss: 1.1014
Epoch 12/47
33/33 - 0s - 10ms/step - accuracy: 0.6484 - loss: 1.0885
Epoch 13/47
33/33 - 0s - 11ms/step - accuracy: 0.6474 - loss: 1.0900
Epoch 14/47
33/33 - 0s - 7ms/step - accuracy: 0.6455 - loss: 1.0701
Epoch 15/47
33/33 - 0s - 7ms/step - accuracy: 0.6487 - loss: 1.0719
Epoch 16/47
33/33 - 0s - 8ms/step - accuracy: 0.6469 - loss: 1.0643
Epoch 17/47
33/33 - 0s - 6ms/step - accuracy: 0.6487 - loss: 1.0625
Epoch 18/47
33/33 - 0s - 8ms/step - accuracy: 0.6530 - loss: 1.0588
Epoch 19/47
33/33 - 0s - 7ms/step - accuracy: 0.6542 - loss: 1.0465
Epoch 20/47
33/33 - 0s - 8ms/step - accuracy: 0.6534 - loss: 1.0442
Epoch 21/47
33/33 - 0s - 8ms/step - accuracy: 0.6553 - loss: 1.0402
Epoch 22/47
33/33 - 0s - 9ms/step - accuracy: 0.6530 - loss: 1.0324
Epoch 23/47
33/33 - 0s - 11ms/step - accuracy: 0.6564 - loss: 1.0304
Epoch 24/47
33/33 - 0s - 11ms/step - accuracy: 0.6552 - loss: 1.0299
Epoch 25/47
33/33 - 0s - 10ms/step - accuracy: 0.6576 - loss: 1.0229
Epoch 26/47
33/33 - 0s - 8ms/step - accuracy: 0.6534 - loss: 1.0254
Epoch 27/47
33/33 - 0s - 9ms/step - accuracy: 0.6554 - loss: 1.0181
Epoch 28/47
33/33 - 0s - 8ms/step - accuracy: 0.6550 - loss: 1.0147
Epoch 29/47
33/33 - 0s - 7ms/step - accuracy: 0.6572 - loss: 1.0127
Epoch 30/47
33/33 - 0s - 10ms/step - accuracy: 0.6571 - loss: 1.0055
Epoch 31/47
33/33 - 0s - 8ms/step - accuracy: 0.6613 - loss: 1.0016
Epoch 32/47
33/33 - 0s - 8ms/step - accuracy: 0.6594 - loss: 1.0023
Epoch 33/47
33/33 - 0s - 10ms/step - accuracy: 0.6611 - loss: 0.9981
Epoch 34/47
33/33 - 0s - 9ms/step - accuracy: 0.6611 - loss: 0.9964
Epoch 35/47
33/33 - 0s - 8ms/step - accuracy: 0.6633 - loss: 0.9915
Epoch 36/47
33/33 - 0s - 8ms/step - accuracy: 0.6607 - loss: 0.9920
Epoch 37/47
33/33 - 0s - 8ms/step - accuracy: 0.6614 - loss: 0.9871
Epoch 38/47
33/33 - 0s - 8ms/step - accuracy: 0.6611 - loss: 0.9904
Epoch 39/47
33/33 - 0s - 7ms/step - accuracy: 0.6635 - loss: 0.9816
Epoch 40/47
33/33 - 0s - 8ms/step - accuracy: 0.6664 - loss: 0.9832
Epoch 41/47
33/33 - 0s - 7ms/step - accuracy: 0.6615 - loss: 0.9806
Epoch 42/47
33/33 - 0s - 7ms/step - accuracy: 0.6649 - loss: 0.9789
Epoch 43/47
33/33 - 0s - 9ms/step - accuracy: 0.6671 - loss: 0.9686
Epoch 44/47
33/33 - 0s - 11ms/step - accuracy: 0.6691 - loss: 0.9713
Epoch 45/47
33/33 - 0s - 12ms/step - accuracy: 0.6655 - loss: 0.9704
Epoch 46/47
33/33 - 0s - 10ms/step - accuracy: 0.6670 - loss: 0.9715
Epoch 47/47
33/33 - 0s - 12ms/step - accuracy: 0.6679 - loss: 0.9675
9/9 - 0s - 32ms/step
Epoch 1/47

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

33/33 - 2s - 47ms/step - accuracy: 0.3897 - loss: 2.4370
Epoch 2/47
33/33 - 0s - 9ms/step - accuracy: 0.5821 - loss: 1.5180
Epoch 3/47
33/33 - 0s - 9ms/step - accuracy: 0.5933 - loss: 1.4353
Epoch 4/47
33/33 - 0s - 10ms/step - accuracy: 0.6017 - loss: 1.3783
Epoch 5/47
33/33 - 0s - 11ms/step - accuracy: 0.5998 - loss: 1.3592
Epoch 6/47
33/33 - 0s - 11ms/step - accuracy: 0.6016 - loss: 1.3127
Epoch 7/47
33/33 - 0s - 8ms/step - accuracy: 0.6062 - loss: 1.2978
Epoch 8/47
33/33 - 0s - 7ms/step - accuracy: 0.6116 - loss: 1.2690
Epoch 9/47
33/33 - 0s - 7ms/step - accuracy: 0.6086 - loss: 1.2445
Epoch 10/47
33/33 - 0s - 9ms/step - accuracy: 0.6137 - loss: 1.2315
Epoch 11/47
33/33 - 0s - 9ms/step - accuracy: 0.6166 - loss: 1.2147
Epoch 12/47
33/33 - 0s - 13ms/step - accuracy: 0.6147 - loss: 1.2027
Epoch 13/47
33/33 - 0s - 11ms/step - accuracy: 0.6168 - loss: 1.1905
Epoch 14/47
33/33 - 0s - 11ms/step - accuracy: 0.6248 - loss: 1.1704
Epoch 15/47
33/33 - 0s - 12ms/step - accuracy: 0.6231 - loss: 1.1684
Epoch 16/47
33/33 - 0s - 7ms/step - accuracy: 0.6256 - loss: 1.1502
Epoch 17/47
33/33 - 0s - 7ms/step - accuracy: 0.6330 - loss: 1.1273
Epoch 18/47
33/33 - 0s - 7ms/step - accuracy: 0.6310 - loss: 1.1283
Epoch 19/47
33/33 - 0s - 7ms/step - accuracy: 0.6309 - loss: 1.1261
Epoch 20/47
33/33 - 0s - 7ms/step - accuracy: 0.6283 - loss: 1.1104
Epoch 21/47
33/33 - 0s - 6ms/step - accuracy: 0.6389 - loss: 1.0932
Epoch 22/47
33/33 - 0s - 7ms/step - accuracy: 0.6351 - loss: 1.0989
Epoch 23/47
33/33 - 0s - 8ms/step - accuracy: 0.6372 - loss: 1.0902
Epoch 24/47
33/33 - 0s - 11ms/step - accuracy: 0.6356 - loss: 1.0900
Epoch 25/47
33/33 - 0s - 9ms/step - accuracy: 0.6418 - loss: 1.0850
Epoch 26/47
33/33 - 0s - 11ms/step - accuracy: 0.6442 - loss: 1.0690
Epoch 27/47
33/33 - 0s - 7ms/step - accuracy: 0.6440 - loss: 1.0555
Epoch 28/47
33/33 - 0s - 9ms/step - accuracy: 0.6419 - loss: 1.0609
Epoch 29/47
33/33 - 0s - 9ms/step - accuracy: 0.6528 - loss: 1.0459
Epoch 30/47
33/33 - 0s - 6ms/step - accuracy: 0.6524 - loss: 1.0409
Epoch 31/47
33/33 - 0s - 7ms/step - accuracy: 0.6505 - loss: 1.0386
Epoch 32/47
33/33 - 0s - 7ms/step - accuracy: 0.6556 - loss: 1.0273
Epoch 33/47
33/33 - 0s - 6ms/step - accuracy: 0.6524 - loss: 1.0312
Epoch 34/47
33/33 - 0s - 6ms/step - accuracy: 0.6593 - loss: 1.0174
Epoch 35/47
33/33 - 0s - 6ms/step - accuracy: 0.6606 - loss: 1.0122
Epoch 36/47
33/33 - 0s - 8ms/step - accuracy: 0.6572 - loss: 1.0189
Epoch 37/47
33/33 - 0s - 10ms/step - accuracy: 0.6581 - loss: 1.0081
Epoch 38/47
33/33 - 0s - 8ms/step - accuracy: 0.6601 - loss: 1.0052
Epoch 39/47
33/33 - 0s - 6ms/step - accuracy: 0.6622 - loss: 0.9967
Epoch 40/47
33/33 - 0s - 7ms/step - accuracy: 0.6612 - loss: 1.0038
Epoch 41/47
33/33 - 0s - 8ms/step - accuracy: 0.6678 - loss: 0.9832
Epoch 42/47
33/33 - 0s - 8ms/step - accuracy: 0.6644 - loss: 0.9916
Epoch 43/47
33/33 - 0s - 8ms/step - accuracy: 0.6702 - loss: 0.9820
Epoch 44/47
33/33 - 0s - 7ms/step - accuracy: 0.6653 - loss: 0.9837
Epoch 45/47
33/33 - 0s - 7ms/step - accuracy: 0.6702 - loss: 0.9750
Epoch 46/47
33/33 - 0s - 8ms/step - accuracy: 0.6697 - loss: 0.9677
Epoch 47/47
33/33 - 0s - 7ms/step - accuracy: 0.6735 - loss: 0.9762
9/9 - 0s - 25ms/step
Epoch 1/47

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

33/33 - 1s - 43ms/step - accuracy: 0.2889 - loss: 2.7657
Epoch 2/47
33/33 - 0s - 9ms/step - accuracy: 0.5202 - loss: 1.6015
Epoch 3/47
33/33 - 0s - 14ms/step - accuracy: 0.5752 - loss: 1.4145
Epoch 4/47
33/33 - 0s - 9ms/step - accuracy: 0.5932 - loss: 1.3347
Epoch 5/47
33/33 - 0s - 8ms/step - accuracy: 0.6116 - loss: 1.2789
Epoch 6/47
33/33 - 0s - 10ms/step - accuracy: 0.6195 - loss: 1.2395
Epoch 7/47
33/33 - 0s - 10ms/step - accuracy: 0.6215 - loss: 1.2160
Epoch 8/47
33/33 - 0s - 8ms/step - accuracy: 0.6257 - loss: 1.1875
Epoch 9/47
33/33 - 0s - 7ms/step - accuracy: 0.6357 - loss: 1.1665
Epoch 10/47
33/33 - 0s - 8ms/step - accuracy: 0.6382 - loss: 1.1444
Epoch 11/47
33/33 - 0s - 7ms/step - accuracy: 0.6359 - loss: 1.1374
Epoch 12/47
33/33 - 0s - 7ms/step - accuracy: 0.6429 - loss: 1.1194
Epoch 13/47
33/33 - 0s - 6ms/step - accuracy: 0.6431 - loss: 1.1128
Epoch 14/47
33/33 - 0s - 8ms/step - accuracy: 0.6404 - loss: 1.0952
Epoch 15/47
33/33 - 0s - 8ms/step - accuracy: 0.6504 - loss: 1.0872
Epoch 16/47
33/33 - 0s - 8ms/step - accuracy: 0.6516 - loss: 1.0845
Epoch 17/47
33/33 - 0s - 8ms/step - accuracy: 0.6524 - loss: 1.0759
Epoch 18/47
33/33 - 0s - 8ms/step - accuracy: 0.6511 - loss: 1.0699
Epoch 19/47
33/33 - 0s - 7ms/step - accuracy: 0.6529 - loss: 1.0615
Epoch 20/47
33/33 - 0s - 7ms/step - accuracy: 0.6532 - loss: 1.0578
Epoch 21/47
33/33 - 0s - 11ms/step - accuracy: 0.6525 - loss: 1.0549
Epoch 22/47
33/33 - 0s - 8ms/step - accuracy: 0.6538 - loss: 1.0528
Epoch 23/47
33/33 - 0s - 7ms/step - accuracy: 0.6546 - loss: 1.0402
Epoch 24/47
33/33 - 0s - 9ms/step - accuracy: 0.6606 - loss: 1.0292
Epoch 25/47
33/33 - 0s - 8ms/step - accuracy: 0.6608 - loss: 1.0279
Epoch 26/47
33/33 - 0s - 6ms/step - accuracy: 0.6575 - loss: 1.0254
Epoch 27/47
33/33 - 0s - 7ms/step - accuracy: 0.6619 - loss: 1.0223
Epoch 28/47
33/33 - 0s - 7ms/step - accuracy: 0.6622 - loss: 1.0171
Epoch 29/47
33/33 - 0s - 7ms/step - accuracy: 0.6629 - loss: 1.0119
Epoch 30/47
33/33 - 0s - 7ms/step - accuracy: 0.6651 - loss: 1.0091
Epoch 31/47
33/33 - 0s - 7ms/step - accuracy: 0.6651 - loss: 1.0110
Epoch 32/47
33/33 - 0s - 7ms/step - accuracy: 0.6672 - loss: 1.0012
Epoch 33/47
33/33 - 0s - 8ms/step - accuracy: 0.6653 - loss: 1.0019
Epoch 34/47
33/33 - 0s - 8ms/step - accuracy: 0.6710 - loss: 0.9963
Epoch 35/47
33/33 - 0s - 8ms/step - accuracy: 0.6693 - loss: 0.9912
Epoch 36/47
33/33 - 0s - 10ms/step - accuracy: 0.6712 - loss: 0.9880
Epoch 37/47
33/33 - 0s - 7ms/step - accuracy: 0.6676 - loss: 0.9888
Epoch 38/47
33/33 - 0s - 9ms/step - accuracy: 0.6715 - loss: 0.9842
Epoch 39/47
33/33 - 0s - 10ms/step - accuracy: 0.6725 - loss: 0.9820
Epoch 40/47
33/33 - 0s - 8ms/step - accuracy: 0.6718 - loss: 0.9786
Epoch 41/47
33/33 - 0s - 9ms/step - accuracy: 0.6742 - loss: 0.9735
Epoch 42/47
33/33 - 0s - 8ms/step - accuracy: 0.6731 - loss: 0.9761
Epoch 43/47
33/33 - 0s - 8ms/step - accuracy: 0.6758 - loss: 0.9682
Epoch 44/47
33/33 - 0s - 10ms/step - accuracy: 0.6756 - loss: 0.9738
Epoch 45/47
33/33 - 0s - 7ms/step - accuracy: 0.6790 - loss: 0.9650
Epoch 46/47
33/33 - 0s - 10ms/step - accuracy: 0.6784 - loss: 0.9685
Epoch 47/47
33/33 - 0s - 9ms/step - accuracy: 0.6773 - loss: 0.9626
9/9 - 0s - 31ms/step
| 13        | 0.6916695 | 35.635644 | 1.0737738 | 5.4860790 | 3.5187531 | 0.0609639 | 422.91717 | 47.247976 | 1.4791237 | 1.2897897 | 0.4894527 | 0.9856504 | 0.0726165 |
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 143ms/step - accuracy: 0.6083 - loss: 1.2049
Epoch 2/39
20/20 - 1s - 35ms/step - accuracy: 0.6559 - loss: 1.0092
Epoch 3/39
20/20 - 1s - 36ms/step - accuracy: 0.6750 - loss: 0.9584
Epoch 4/39
20/20 - 1s - 36ms/step - accuracy: 0.6888 - loss: 0.9189
Epoch 5/39
20/20 - 1s - 31ms/step - accuracy: 0.7004 - loss: 0.8846
Epoch 6/39
20/20 - 1s - 36ms/step - accuracy: 0.7100 - loss: 0.8571
Epoch 7/39
20/20 - 1s - 31ms/step - accuracy: 0.7189 - loss: 0.8322
Epoch 8/39
20/20 - 1s - 30ms/step - accuracy: 0.7285 - loss: 0.8096
Epoch 9/39
20/20 - 1s - 31ms/step - accuracy: 0.7337 - loss: 0.7867
Epoch 10/39
20/20 - 1s - 31ms/step - accuracy: 0.7428 - loss: 0.7657
Epoch 11/39
20/20 - 1s - 32ms/step - accuracy: 0.7497 - loss: 0.7452
Epoch 12/39
20/20 - 1s - 35ms/step - accuracy: 0.7555 - loss: 0.7252
Epoch 13/39
20/20 - 1s - 40ms/step - accuracy: 0.7632 - loss: 0.7091
Epoch 14/39
20/20 - 1s - 35ms/step - accuracy: 0.7619 - loss: 0.6979
Epoch 15/39
20/20 - 1s - 34ms/step - accuracy: 0.7697 - loss: 0.6827
Epoch 16/39
20/20 - 1s - 32ms/step - accuracy: 0.7718 - loss: 0.6722
Epoch 17/39
20/20 - 1s - 36ms/step - accuracy: 0.7759 - loss: 0.6609
Epoch 18/39
20/20 - 1s - 34ms/step - accuracy: 0.7784 - loss: 0.6508
Epoch 19/39
20/20 - 1s - 30ms/step - accuracy: 0.7819 - loss: 0.6416
Epoch 20/39
20/20 - 1s - 30ms/step - accuracy: 0.7859 - loss: 0.6331
Epoch 21/39
20/20 - 1s - 30ms/step - accuracy: 0.7900 - loss: 0.6231
Epoch 22/39
20/20 - 1s - 39ms/step - accuracy: 0.7903 - loss: 0.6151
Epoch 23/39
20/20 - 1s - 37ms/step - accuracy: 0.7903 - loss: 0.6099
Epoch 24/39
20/20 - 1s - 37ms/step - accuracy: 0.7922 - loss: 0.6028
Epoch 25/39
20/20 - 1s - 32ms/step - accuracy: 0.7922 - loss: 0.5963
Epoch 26/39
20/20 - 1s - 37ms/step - accuracy: 0.7978 - loss: 0.5863
Epoch 27/39
20/20 - 1s - 34ms/step - accuracy: 0.7976 - loss: 0.5816
Epoch 28/39
20/20 - 1s - 33ms/step - accuracy: 0.8024 - loss: 0.5735
Epoch 29/39
20/20 - 1s - 42ms/step - accuracy: 0.8041 - loss: 0.5682
Epoch 30/39
20/20 - 1s - 31ms/step - accuracy: 0.8033 - loss: 0.5646
Epoch 31/39
20/20 - 1s - 33ms/step - accuracy: 0.8059 - loss: 0.5558
Epoch 32/39
20/20 - 1s - 30ms/step - accuracy: 0.8071 - loss: 0.5503
Epoch 33/39
20/20 - 1s - 37ms/step - accuracy: 0.8087 - loss: 0.5469
Epoch 34/39
20/20 - 1s - 37ms/step - accuracy: 0.8110 - loss: 0.5412
Epoch 35/39
20/20 - 1s - 34ms/step - accuracy: 0.8130 - loss: 0.5344
Epoch 36/39
20/20 - 1s - 35ms/step - accuracy: 0.8133 - loss: 0.5298
Epoch 37/39
20/20 - 1s - 34ms/step - accuracy: 0.8158 - loss: 0.5237
Epoch 38/39
20/20 - 1s - 40ms/step - accuracy: 0.8184 - loss: 0.5176
Epoch 39/39
20/20 - 1s - 37ms/step - accuracy: 0.8202 - loss: 0.5137
5/5 - 0s - 75ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 147ms/step - accuracy: 0.6153 - loss: 1.2334
Epoch 2/39
20/20 - 1s - 35ms/step - accuracy: 0.6600 - loss: 1.0132
Epoch 3/39
20/20 - 1s - 35ms/step - accuracy: 0.6754 - loss: 0.9583
Epoch 4/39
20/20 - 1s - 34ms/step - accuracy: 0.6894 - loss: 0.9184
Epoch 5/39
20/20 - 1s - 33ms/step - accuracy: 0.6977 - loss: 0.8807
Epoch 6/39
20/20 - 1s - 33ms/step - accuracy: 0.7043 - loss: 0.8498
Epoch 7/39
20/20 - 1s - 34ms/step - accuracy: 0.7163 - loss: 0.8271
Epoch 8/39
20/20 - 1s - 31ms/step - accuracy: 0.7234 - loss: 0.8084
Epoch 9/39
20/20 - 1s - 37ms/step - accuracy: 0.7316 - loss: 0.7914
Epoch 10/39
20/20 - 1s - 36ms/step - accuracy: 0.7377 - loss: 0.7760
Epoch 11/39
20/20 - 1s - 46ms/step - accuracy: 0.7412 - loss: 0.7633
Epoch 12/39
20/20 - 1s - 62ms/step - accuracy: 0.7442 - loss: 0.7502
Epoch 13/39
20/20 - 1s - 41ms/step - accuracy: 0.7525 - loss: 0.7371
Epoch 14/39
20/20 - 1s - 38ms/step - accuracy: 0.7574 - loss: 0.7241
Epoch 15/39
20/20 - 1s - 38ms/step - accuracy: 0.7589 - loss: 0.7131
Epoch 16/39
20/20 - 1s - 41ms/step - accuracy: 0.7651 - loss: 0.6980
Epoch 17/39
20/20 - 1s - 42ms/step - accuracy: 0.7682 - loss: 0.6890
Epoch 18/39
20/20 - 1s - 42ms/step - accuracy: 0.7728 - loss: 0.6771
Epoch 19/39
20/20 - 1s - 43ms/step - accuracy: 0.7751 - loss: 0.6655
Epoch 20/39
20/20 - 1s - 39ms/step - accuracy: 0.7784 - loss: 0.6567
Epoch 21/39
20/20 - 1s - 34ms/step - accuracy: 0.7828 - loss: 0.6442
Epoch 22/39
20/20 - 1s - 34ms/step - accuracy: 0.7844 - loss: 0.6328
Epoch 23/39
20/20 - 1s - 33ms/step - accuracy: 0.7868 - loss: 0.6254
Epoch 24/39
20/20 - 1s - 36ms/step - accuracy: 0.7901 - loss: 0.6191
Epoch 25/39
20/20 - 1s - 34ms/step - accuracy: 0.7923 - loss: 0.6078
Epoch 26/39
20/20 - 1s - 38ms/step - accuracy: 0.7929 - loss: 0.5997
Epoch 27/39
20/20 - 1s - 37ms/step - accuracy: 0.7953 - loss: 0.5933
Epoch 28/39
20/20 - 1s - 34ms/step - accuracy: 0.7968 - loss: 0.5879
Epoch 29/39
20/20 - 1s - 43ms/step - accuracy: 0.8022 - loss: 0.5773
Epoch 30/39
20/20 - 1s - 36ms/step - accuracy: 0.8002 - loss: 0.5716
Epoch 31/39
20/20 - 1s - 33ms/step - accuracy: 0.8035 - loss: 0.5643
Epoch 32/39
20/20 - 1s - 30ms/step - accuracy: 0.8054 - loss: 0.5567
Epoch 33/39
20/20 - 1s - 35ms/step - accuracy: 0.8077 - loss: 0.5510
Epoch 34/39
20/20 - 1s - 33ms/step - accuracy: 0.8075 - loss: 0.5473
Epoch 35/39
20/20 - 1s - 35ms/step - accuracy: 0.8102 - loss: 0.5408
Epoch 36/39
20/20 - 1s - 37ms/step - accuracy: 0.8137 - loss: 0.5353
Epoch 37/39
20/20 - 1s - 39ms/step - accuracy: 0.8123 - loss: 0.5295
Epoch 38/39
20/20 - 1s - 46ms/step - accuracy: 0.8168 - loss: 0.5267
Epoch 39/39
20/20 - 1s - 41ms/step - accuracy: 0.8163 - loss: 0.5227
5/5 - 0s - 88ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 4s - 212ms/step - accuracy: 0.6081 - loss: 1.2669
Epoch 2/39
20/20 - 1s - 30ms/step - accuracy: 0.6635 - loss: 1.0233
Epoch 3/39
20/20 - 1s - 32ms/step - accuracy: 0.6821 - loss: 0.9643
Epoch 4/39
20/20 - 1s - 30ms/step - accuracy: 0.6932 - loss: 0.9241
Epoch 5/39
20/20 - 1s - 30ms/step - accuracy: 0.7023 - loss: 0.8868
Epoch 6/39
20/20 - 1s - 29ms/step - accuracy: 0.7105 - loss: 0.8508
Epoch 7/39
20/20 - 1s - 32ms/step - accuracy: 0.7243 - loss: 0.8194
Epoch 8/39
20/20 - 1s - 31ms/step - accuracy: 0.7320 - loss: 0.7916
Epoch 9/39
20/20 - 1s - 32ms/step - accuracy: 0.7446 - loss: 0.7693
Epoch 10/39
20/20 - 1s - 31ms/step - accuracy: 0.7502 - loss: 0.7508
Epoch 11/39
20/20 - 1s - 34ms/step - accuracy: 0.7561 - loss: 0.7359
Epoch 12/39
20/20 - 1s - 31ms/step - accuracy: 0.7581 - loss: 0.7244
Epoch 13/39
20/20 - 1s - 32ms/step - accuracy: 0.7630 - loss: 0.7132
Epoch 14/39
20/20 - 1s - 34ms/step - accuracy: 0.7675 - loss: 0.6984
Epoch 15/39
20/20 - 1s - 37ms/step - accuracy: 0.7690 - loss: 0.6883
Epoch 16/39
20/20 - 1s - 38ms/step - accuracy: 0.7726 - loss: 0.6793
Epoch 17/39
20/20 - 1s - 36ms/step - accuracy: 0.7770 - loss: 0.6682
Epoch 18/39
20/20 - 1s - 38ms/step - accuracy: 0.7769 - loss: 0.6603
Epoch 19/39
20/20 - 1s - 35ms/step - accuracy: 0.7816 - loss: 0.6520
Epoch 20/39
20/20 - 1s - 34ms/step - accuracy: 0.7808 - loss: 0.6444
Epoch 21/39
20/20 - 1s - 36ms/step - accuracy: 0.7853 - loss: 0.6340
Epoch 22/39
20/20 - 1s - 36ms/step - accuracy: 0.7874 - loss: 0.6247
Epoch 23/39
20/20 - 1s - 36ms/step - accuracy: 0.7919 - loss: 0.6192
Epoch 24/39
20/20 - 1s - 40ms/step - accuracy: 0.7898 - loss: 0.6136
Epoch 25/39
20/20 - 1s - 37ms/step - accuracy: 0.7920 - loss: 0.6050
Epoch 26/39
20/20 - 1s - 46ms/step - accuracy: 0.7938 - loss: 0.5984
Epoch 27/39
20/20 - 1s - 38ms/step - accuracy: 0.7976 - loss: 0.5907
Epoch 28/39
20/20 - 1s - 41ms/step - accuracy: 0.7993 - loss: 0.5852
Epoch 29/39
20/20 - 1s - 43ms/step - accuracy: 0.7993 - loss: 0.5786
Epoch 30/39
20/20 - 1s - 36ms/step - accuracy: 0.8023 - loss: 0.5718
Epoch 31/39
20/20 - 1s - 35ms/step - accuracy: 0.8034 - loss: 0.5635
Epoch 32/39
20/20 - 1s - 39ms/step - accuracy: 0.8045 - loss: 0.5581
Epoch 33/39
20/20 - 1s - 43ms/step - accuracy: 0.8037 - loss: 0.5566
Epoch 34/39
20/20 - 1s - 40ms/step - accuracy: 0.8063 - loss: 0.5519
Epoch 35/39
20/20 - 1s - 38ms/step - accuracy: 0.8109 - loss: 0.5423
Epoch 36/39
20/20 - 1s - 41ms/step - accuracy: 0.8096 - loss: 0.5393
Epoch 37/39
20/20 - 1s - 44ms/step - accuracy: 0.8136 - loss: 0.5325
Epoch 38/39
20/20 - 1s - 43ms/step - accuracy: 0.8133 - loss: 0.5285
Epoch 39/39
20/20 - 1s - 40ms/step - accuracy: 0.8132 - loss: 0.5277
5/5 - 0s - 86ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 155ms/step - accuracy: 0.5804 - loss: 1.4119
Epoch 2/39
20/20 - 1s - 36ms/step - accuracy: 0.6588 - loss: 1.0316
Epoch 3/39
20/20 - 1s - 66ms/step - accuracy: 0.6743 - loss: 0.9767
Epoch 4/39
20/20 - 1s - 39ms/step - accuracy: 0.6892 - loss: 0.9347
Epoch 5/39
20/20 - 1s - 37ms/step - accuracy: 0.7013 - loss: 0.8967
Epoch 6/39
20/20 - 1s - 39ms/step - accuracy: 0.7089 - loss: 0.8662
Epoch 7/39
20/20 - 1s - 44ms/step - accuracy: 0.7174 - loss: 0.8423
Epoch 8/39
20/20 - 1s - 40ms/step - accuracy: 0.7211 - loss: 0.8215
Epoch 9/39
20/20 - 1s - 40ms/step - accuracy: 0.7286 - loss: 0.8036
Epoch 10/39
20/20 - 1s - 38ms/step - accuracy: 0.7344 - loss: 0.7845
Epoch 11/39
20/20 - 1s - 45ms/step - accuracy: 0.7428 - loss: 0.7670
Epoch 12/39
20/20 - 1s - 42ms/step - accuracy: 0.7473 - loss: 0.7503
Epoch 13/39
20/20 - 1s - 63ms/step - accuracy: 0.7530 - loss: 0.7369
Epoch 14/39
20/20 - 1s - 45ms/step - accuracy: 0.7580 - loss: 0.7206
Epoch 15/39
20/20 - 1s - 39ms/step - accuracy: 0.7633 - loss: 0.7079
Epoch 16/39
20/20 - 1s - 37ms/step - accuracy: 0.7656 - loss: 0.6963
Epoch 17/39
20/20 - 1s - 36ms/step - accuracy: 0.7700 - loss: 0.6848
Epoch 18/39
20/20 - 1s - 36ms/step - accuracy: 0.7732 - loss: 0.6744
Epoch 19/39
20/20 - 1s - 41ms/step - accuracy: 0.7763 - loss: 0.6670
Epoch 20/39
20/20 - 1s - 38ms/step - accuracy: 0.7772 - loss: 0.6565
Epoch 21/39
20/20 - 1s - 39ms/step - accuracy: 0.7813 - loss: 0.6484
Epoch 22/39
20/20 - 1s - 47ms/step - accuracy: 0.7832 - loss: 0.6400
Epoch 23/39
20/20 - 1s - 37ms/step - accuracy: 0.7835 - loss: 0.6325
Epoch 24/39
20/20 - 1s - 37ms/step - accuracy: 0.7871 - loss: 0.6271
Epoch 25/39
20/20 - 1s - 37ms/step - accuracy: 0.7901 - loss: 0.6172
Epoch 26/39
20/20 - 1s - 50ms/step - accuracy: 0.7931 - loss: 0.6099
Epoch 27/39
20/20 - 1s - 38ms/step - accuracy: 0.7929 - loss: 0.6036
Epoch 28/39
20/20 - 1s - 44ms/step - accuracy: 0.7961 - loss: 0.5955
Epoch 29/39
20/20 - 1s - 40ms/step - accuracy: 0.7984 - loss: 0.5883
Epoch 30/39
20/20 - 1s - 42ms/step - accuracy: 0.7964 - loss: 0.5857
Epoch 31/39
20/20 - 1s - 39ms/step - accuracy: 0.7993 - loss: 0.5805
Epoch 32/39
20/20 - 1s - 39ms/step - accuracy: 0.8022 - loss: 0.5701
Epoch 33/39
20/20 - 1s - 42ms/step - accuracy: 0.8028 - loss: 0.5673
Epoch 34/39
20/20 - 1s - 44ms/step - accuracy: 0.8025 - loss: 0.5613
Epoch 35/39
20/20 - 1s - 41ms/step - accuracy: 0.8069 - loss: 0.5556
Epoch 36/39
20/20 - 1s - 62ms/step - accuracy: 0.8091 - loss: 0.5471
Epoch 37/39
20/20 - 1s - 37ms/step - accuracy: 0.8070 - loss: 0.5438
Epoch 38/39
20/20 - 1s - 41ms/step - accuracy: 0.8129 - loss: 0.5363
Epoch 39/39
20/20 - 1s - 38ms/step - accuracy: 0.8095 - loss: 0.5359
5/5 - 0s - 83ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 - 3s - 152ms/step - accuracy: 0.5855 - loss: 1.3453
Epoch 2/39
20/20 - 1s - 36ms/step - accuracy: 0.6534 - loss: 1.0222
Epoch 3/39
20/20 - 1s - 53ms/step - accuracy: 0.6716 - loss: 0.9675
Epoch 4/39
20/20 - 1s - 39ms/step - accuracy: 0.6928 - loss: 0.9148
Epoch 5/39
20/20 - 1s - 41ms/step - accuracy: 0.7069 - loss: 0.8668
Epoch 6/39
20/20 - 1s - 42ms/step - accuracy: 0.7221 - loss: 0.8294
Epoch 7/39
20/20 - 1s - 41ms/step - accuracy: 0.7349 - loss: 0.7966
Epoch 8/39
20/20 - 1s - 42ms/step - accuracy: 0.7407 - loss: 0.7744
Epoch 9/39
20/20 - 1s - 45ms/step - accuracy: 0.7489 - loss: 0.7568
Epoch 10/39
20/20 - 1s - 47ms/step - accuracy: 0.7537 - loss: 0.7403
Epoch 11/39
20/20 - 1s - 39ms/step - accuracy: 0.7576 - loss: 0.7253
Epoch 12/39
20/20 - 1s - 38ms/step - accuracy: 0.7626 - loss: 0.7124
Epoch 13/39
20/20 - 1s - 36ms/step - accuracy: 0.7647 - loss: 0.7010
Epoch 14/39
20/20 - 1s - 36ms/step - accuracy: 0.7691 - loss: 0.6909
Epoch 15/39
20/20 - 1s - 44ms/step - accuracy: 0.7727 - loss: 0.6796
Epoch 16/39
20/20 - 1s - 42ms/step - accuracy: 0.7760 - loss: 0.6681
Epoch 17/39
20/20 - 1s - 36ms/step - accuracy: 0.7771 - loss: 0.6597
Epoch 18/39
20/20 - 1s - 35ms/step - accuracy: 0.7808 - loss: 0.6488
Epoch 19/39
20/20 - 1s - 33ms/step - accuracy: 0.7836 - loss: 0.6411
Epoch 20/39
20/20 - 1s - 32ms/step - accuracy: 0.7858 - loss: 0.6310
Epoch 21/39
20/20 - 1s - 33ms/step - accuracy: 0.7875 - loss: 0.6238
Epoch 22/39
20/20 - 1s - 32ms/step - accuracy: 0.7897 - loss: 0.6158
Epoch 23/39
20/20 - 1s - 36ms/step - accuracy: 0.7909 - loss: 0.6066
Epoch 24/39
20/20 - 1s - 45ms/step - accuracy: 0.7965 - loss: 0.5990
Epoch 25/39
20/20 - 1s - 47ms/step - accuracy: 0.7984 - loss: 0.5886
Epoch 26/39
20/20 - 1s - 40ms/step - accuracy: 0.7988 - loss: 0.5810
Epoch 27/39
20/20 - 1s - 40ms/step - accuracy: 0.8013 - loss: 0.5763
Epoch 28/39
20/20 - 1s - 52ms/step - accuracy: 0.8052 - loss: 0.5687
Epoch 29/39
20/20 - 1s - 47ms/step - accuracy: 0.8060 - loss: 0.5628
Epoch 30/39
20/20 - 1s - 44ms/step - accuracy: 0.8104 - loss: 0.5554
Epoch 31/39
20/20 - 1s - 40ms/step - accuracy: 0.8120 - loss: 0.5473
Epoch 32/39
20/20 - 1s - 38ms/step - accuracy: 0.8110 - loss: 0.5424
Epoch 33/39
20/20 - 1s - 43ms/step - accuracy: 0.8142 - loss: 0.5357
Epoch 34/39
20/20 - 1s - 43ms/step - accuracy: 0.8141 - loss: 0.5294
Epoch 35/39
20/20 - 1s - 41ms/step - accuracy: 0.8175 - loss: 0.5251
Epoch 36/39
20/20 - 1s - 42ms/step - accuracy: 0.8195 - loss: 0.5201
Epoch 37/39
20/20 - 1s - 37ms/step - accuracy: 0.8215 - loss: 0.5117
Epoch 38/39
20/20 - 1s - 36ms/step - accuracy: 0.8221 - loss: 0.5070
Epoch 39/39
20/20 - 1s - 46ms/step - accuracy: 0.8241 - loss: 0.5009
5/5 - 0s - 99ms/step
| 14        | 0.8026380 | 70.492199 | 2.5232392 | 2.1387378 | 5.0975144 | 0.3741053 | 705.84466 | 39.005891 | 2.0715493 | 1.1805795 | 0.8353024 | 0.3207800 | 0.0559555 |
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

37/37 - 1s - 31ms/step - accuracy: 0.5631 - loss: 1.5292
Epoch 2/39
37/37 - 0s - 10ms/step - accuracy: 0.6406 - loss: 1.1368
Epoch 3/39
37/37 - 0s - 11ms/step - accuracy: 0.6599 - loss: 1.0468
Epoch 4/39
37/37 - 0s - 9ms/step - accuracy: 0.6640 - loss: 1.0121
Epoch 5/39
37/37 - 0s - 11ms/step - accuracy: 0.6752 - loss: 0.9748
Epoch 6/39
37/37 - 0s - 8ms/step - accuracy: 0.6795 - loss: 0.9546
Epoch 7/39
37/37 - 0s - 6ms/step - accuracy: 0.6849 - loss: 0.9382
Epoch 8/39
37/37 - 0s - 6ms/step - accuracy: 0.6883 - loss: 0.9211
Epoch 9/39
37/37 - 0s - 7ms/step - accuracy: 0.6913 - loss: 0.9085
Epoch 10/39
37/37 - 0s - 7ms/step - accuracy: 0.6910 - loss: 0.9013
Epoch 11/39
37/37 - 0s - 7ms/step - accuracy: 0.6916 - loss: 0.8991
Epoch 12/39
37/37 - 0s - 6ms/step - accuracy: 0.6973 - loss: 0.8872
Epoch 13/39
37/37 - 0s - 6ms/step - accuracy: 0.6992 - loss: 0.8852
Epoch 14/39
37/37 - 0s - 6ms/step - accuracy: 0.7008 - loss: 0.8756
Epoch 15/39
37/37 - 0s - 5ms/step - accuracy: 0.7008 - loss: 0.8694
Epoch 16/39
37/37 - 0s - 10ms/step - accuracy: 0.7037 - loss: 0.8632
Epoch 17/39
37/37 - 0s - 10ms/step - accuracy: 0.7028 - loss: 0.8623
Epoch 18/39
37/37 - 0s - 11ms/step - accuracy: 0.7022 - loss: 0.8601
Epoch 19/39
37/37 - 0s - 8ms/step - accuracy: 0.7054 - loss: 0.8522
Epoch 20/39
37/37 - 0s - 9ms/step - accuracy: 0.7093 - loss: 0.8464
Epoch 21/39
37/37 - 0s - 9ms/step - accuracy: 0.7107 - loss: 0.8480
Epoch 22/39
37/37 - 0s - 12ms/step - accuracy: 0.7083 - loss: 0.8409
Epoch 23/39
37/37 - 0s - 6ms/step - accuracy: 0.7115 - loss: 0.8366
Epoch 24/39
37/37 - 0s - 11ms/step - accuracy: 0.7078 - loss: 0.8323
Epoch 25/39
37/37 - 0s - 8ms/step - accuracy: 0.7145 - loss: 0.8294
Epoch 26/39
37/37 - 0s - 9ms/step - accuracy: 0.7109 - loss: 0.8279
Epoch 27/39
37/37 - 0s - 8ms/step - accuracy: 0.7158 - loss: 0.8234
Epoch 28/39
37/37 - 0s - 11ms/step - accuracy: 0.7165 - loss: 0.8167
Epoch 29/39
37/37 - 0s - 11ms/step - accuracy: 0.7155 - loss: 0.8174
Epoch 30/39
37/37 - 0s - 11ms/step - accuracy: 0.7153 - loss: 0.8152
Epoch 31/39
37/37 - 0s - 11ms/step - accuracy: 0.7143 - loss: 0.8115
Epoch 32/39
37/37 - 0s - 11ms/step - accuracy: 0.7171 - loss: 0.8075
Epoch 33/39
37/37 - 0s - 8ms/step - accuracy: 0.7223 - loss: 0.8033
Epoch 34/39
37/37 - 0s - 6ms/step - accuracy: 0.7208 - loss: 0.7999
Epoch 35/39
37/37 - 0s - 11ms/step - accuracy: 0.7215 - loss: 0.7979
Epoch 36/39
37/37 - 0s - 6ms/step - accuracy: 0.7250 - loss: 0.7945
Epoch 37/39
37/37 - 0s - 9ms/step - accuracy: 0.7237 - loss: 0.7907
Epoch 38/39
37/37 - 0s - 12ms/step - accuracy: 0.7258 - loss: 0.7892
Epoch 39/39
37/37 - 0s - 11ms/step - accuracy: 0.7253 - loss: 0.7832
10/10 - 0s - 31ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

37/37 - 1s - 33ms/step - accuracy: 0.5877 - loss: 1.3397
Epoch 2/39
37/37 - 0s - 9ms/step - accuracy: 0.6402 - loss: 1.1001
Epoch 3/39
37/37 - 0s - 6ms/step - accuracy: 0.6539 - loss: 1.0492
Epoch 4/39
37/37 - 0s - 8ms/step - accuracy: 0.6615 - loss: 1.0226
Epoch 5/39
37/37 - 0s - 9ms/step - accuracy: 0.6748 - loss: 0.9893
Epoch 6/39
37/37 - 0s - 9ms/step - accuracy: 0.6825 - loss: 0.9712
Epoch 7/39
37/37 - 0s - 7ms/step - accuracy: 0.6852 - loss: 0.9529
Epoch 8/39
37/37 - 0s - 7ms/step - accuracy: 0.6917 - loss: 0.9410
Epoch 9/39
37/37 - 0s - 7ms/step - accuracy: 0.6942 - loss: 0.9246
Epoch 10/39
37/37 - 0s - 10ms/step - accuracy: 0.6982 - loss: 0.9150
Epoch 11/39
37/37 - 0s - 11ms/step - accuracy: 0.7049 - loss: 0.9031
Epoch 12/39
37/37 - 0s - 10ms/step - accuracy: 0.7083 - loss: 0.8921
Epoch 13/39
37/37 - 0s - 7ms/step - accuracy: 0.7088 - loss: 0.8853
Epoch 14/39
37/37 - 0s - 5ms/step - accuracy: 0.7107 - loss: 0.8763
Epoch 15/39
37/37 - 0s - 6ms/step - accuracy: 0.7132 - loss: 0.8719
Epoch 16/39
37/37 - 0s - 6ms/step - accuracy: 0.7174 - loss: 0.8621
Epoch 17/39
37/37 - 0s - 6ms/step - accuracy: 0.7197 - loss: 0.8553
Epoch 18/39
37/37 - 0s - 7ms/step - accuracy: 0.7201 - loss: 0.8498
Epoch 19/39
37/37 - 0s - 5ms/step - accuracy: 0.7209 - loss: 0.8393
Epoch 20/39
37/37 - 0s - 6ms/step - accuracy: 0.7210 - loss: 0.8388
Epoch 21/39
37/37 - 0s - 6ms/step - accuracy: 0.7266 - loss: 0.8288
Epoch 22/39
37/37 - 0s - 6ms/step - accuracy: 0.7237 - loss: 0.8311
Epoch 23/39
37/37 - 0s - 8ms/step - accuracy: 0.7291 - loss: 0.8205
Epoch 24/39
37/37 - 0s - 7ms/step - accuracy: 0.7264 - loss: 0.8183
Epoch 25/39
37/37 - 0s - 9ms/step - accuracy: 0.7296 - loss: 0.8136
Epoch 26/39
37/37 - 0s - 9ms/step - accuracy: 0.7303 - loss: 0.8125
Epoch 27/39
37/37 - 0s - 8ms/step - accuracy: 0.7315 - loss: 0.8063
Epoch 28/39
37/37 - 0s - 8ms/step - accuracy: 0.7311 - loss: 0.8014
Epoch 29/39
37/37 - 0s - 7ms/step - accuracy: 0.7354 - loss: 0.7981
Epoch 30/39
37/37 - 0s - 8ms/step - accuracy: 0.7299 - loss: 0.7971
Epoch 31/39
37/37 - 0s - 7ms/step - accuracy: 0.7369 - loss: 0.7918
Epoch 32/39
37/37 - 0s - 7ms/step - accuracy: 0.7330 - loss: 0.7909
Epoch 33/39
37/37 - 0s - 8ms/step - accuracy: 0.7366 - loss: 0.7862
Epoch 34/39
37/37 - 0s - 8ms/step - accuracy: 0.7359 - loss: 0.7808
Epoch 35/39
37/37 - 0s - 7ms/step - accuracy: 0.7361 - loss: 0.7834
Epoch 36/39
37/37 - 0s - 9ms/step - accuracy: 0.7380 - loss: 0.7770
Epoch 37/39
37/37 - 0s - 7ms/step - accuracy: 0.7371 - loss: 0.7809
Epoch 38/39
37/37 - 0s - 9ms/step - accuracy: 0.7419 - loss: 0.7702
Epoch 39/39
37/37 - 0s - 8ms/step - accuracy: 0.7388 - loss: 0.7674
10/10 - 0s - 31ms/step

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/39
37/37 - 1s - 37ms/step - accuracy: 0.5805 - loss: 1.4535
Epoch 2/39
37/37 - 0s - 8ms/step - accuracy: 0.6412 - loss: 1.1072
Epoch 3/39
37/37 - 0s - 8ms/step - accuracy: 0.6588 - loss: 1.0371
Epoch 4/39
37/37 - 0s - 8ms/step - accuracy: 0.6707 - loss: 0.9940
Epoch 5/39
37/37 - 0s - 7ms/step - accuracy: 0.6712 - loss: 0.9819
Epoch 6/39
37/37 - 0s - 8ms/step - accuracy: 0.6807 - loss: 0.9582
Epoch 7/39
37/37 - 0s - 9ms/step - accuracy: 0.6870 - loss: 0.9384
Epoch 8/39
37/37 - 0s - 7ms/step - accuracy: 0.6967 - loss: 0.9205
Epoch 9/39
37/37 - 0s - 11ms/step - accuracy: 0.6983 - loss: 0.9068
Epoch 10/39
37/37 - 0s - 9ms/step - accuracy: 0.7048 - loss: 0.8940
Epoch 11/39
37/37 - 0s - 10ms/step - accuracy: 0.7033 - loss: 0.8928
Epoch 12/39
37/37 - 0s - 10ms/step - accuracy: 0.7110 - loss: 0.8728
Epoch 13/39
37/37 - 0s - 9ms/step - accuracy: 0.7058 - loss: 0.8812
Epoch 14/39
37/37 - 0s - 9ms/step - accuracy: 0.7166 - loss: 0.8618
Epoch 15/39
37/37 - 0s - 7ms/step - accuracy: 0.7162 - loss: 0.8528
Epoch 16/39
37/37 - 0s - 7ms/step - accuracy: 0.7211 - loss: 0.8444
Epoch 17/39
37/37 - 0s - 7ms/step - accuracy: 0.7174 - loss: 0.8498
Epoch 18/39
37/37 - 0s - 7ms/step - accuracy: 0.7197 - loss: 0.8425
Epoch 19/39
37/37 - 0s - 8ms/step - accuracy: 0.7210 - loss: 0.8349
Epoch 20/39
37/37 - 0s - 9ms/step - accuracy: 0.7226 - loss: 0.8264
Epoch 21/39
37/37 - 0s - 6ms/step - accuracy: 0.7234 - loss: 0.8260
Epoch 22/39
37/37 - 0s - 8ms/step - accuracy: 0.7227 - loss: 0.8242
Epoch 23/39
37/37 - 0s - 7ms/step - accuracy: 0.7219 - loss: 0.8253
Epoch 24/39
37/37 - 0s - 6ms/step - accuracy: 0.7272 - loss: 0.8139
Epoch 25/39
37/37 - 0s - 5ms/step - accuracy: 0.7257 - loss: 0.8137
Epoch 26/39
37/37 - 0s - 6ms/step - accuracy: 0.7269 - loss: 0.8096
Epoch 27/39
37/37 - 0s - 7ms/step - accuracy: 0.7293 - loss: 0.8033
Epoch 28/39
37/37 - 0s - 7ms/step - accuracy: 0.7300 - loss: 0.7985
Epoch 29/39
37/37 - 0s - 6ms/step - accuracy: 0.7311 - loss: 0.7972
Epoch 30/39
37/37 - 0s - 6ms/step - accuracy: 0.7324 - loss: 0.7928
Epoch 31/39
37/37 - 0s - 6ms/step - accuracy: 0.7324 - loss: 0.7947
Epoch 32/39
37/37 - 0s - 7ms/step - accuracy: 0.7334 - loss: 0.7917
Epoch 33/39
37/37 - 0s - 6ms/step - accuracy: 0.7359 - loss: 0.7850
Epoch 34/39
37/37 - 0s - 8ms/step - accuracy: 0.7365 - loss: 0.7822
Epoch 35/39
37/37 - 0s - 8ms/step - accuracy: 0.7336 - loss: 0.7814
Epoch 36/39
37/37 - 0s - 7ms/step - accuracy: 0.7359 - loss: 0.7756
Epoch 37/39
37/37 - 0s - 5ms/step - accuracy: 0.7380 - loss: 0.7766
Epoch 38/39
37/37 - 0s - 6ms/step - accuracy: 0.7378 - loss: 0.7742
Epoch 39/39
37/37 - 0s - 6ms/step - accuracy: 0.7362 - loss: 0.7771
10/10 - 0s - 32ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

37/37 - 1s - 35ms/step - accuracy: 0.5816 - loss: 1.4305
Epoch 2/39
37/37 - 0s - 7ms/step - accuracy: 0.6539 - loss: 1.0848
Epoch 3/39
37/37 - 0s - 6ms/step - accuracy: 0.6550 - loss: 1.0303
Epoch 4/39
37/37 - 0s - 7ms/step - accuracy: 0.6643 - loss: 0.9971
Epoch 5/39
37/37 - 0s - 10ms/step - accuracy: 0.6731 - loss: 0.9749
Epoch 6/39
37/37 - 0s - 7ms/step - accuracy: 0.6806 - loss: 0.9521
Epoch 7/39
37/37 - 0s - 8ms/step - accuracy: 0.6794 - loss: 0.9365
Epoch 8/39
37/37 - 0s - 7ms/step - accuracy: 0.6854 - loss: 0.9207
Epoch 9/39
37/37 - 0s - 8ms/step - accuracy: 0.6901 - loss: 0.9126
Epoch 10/39
37/37 - 0s - 6ms/step - accuracy: 0.6946 - loss: 0.8967
Epoch 11/39
37/37 - 0s - 7ms/step - accuracy: 0.7005 - loss: 0.8859
Epoch 12/39
37/37 - 0s - 8ms/step - accuracy: 0.7033 - loss: 0.8752
Epoch 13/39
37/37 - 0s - 5ms/step - accuracy: 0.7072 - loss: 0.8664
Epoch 14/39
37/37 - 0s - 6ms/step - accuracy: 0.7081 - loss: 0.8534
Epoch 15/39
37/37 - 0s - 11ms/step - accuracy: 0.7133 - loss: 0.8493
Epoch 16/39
37/37 - 0s - 6ms/step - accuracy: 0.7179 - loss: 0.8385
Epoch 17/39
37/37 - 0s - 5ms/step - accuracy: 0.7191 - loss: 0.8349
Epoch 18/39
37/37 - 0s - 7ms/step - accuracy: 0.7226 - loss: 0.8242
Epoch 19/39
37/37 - 0s - 8ms/step - accuracy: 0.7184 - loss: 0.8253
Epoch 20/39
37/37 - 0s - 10ms/step - accuracy: 0.7260 - loss: 0.8144
Epoch 21/39
37/37 - 0s - 10ms/step - accuracy: 0.7264 - loss: 0.8148
Epoch 22/39
37/37 - 0s - 11ms/step - accuracy: 0.7264 - loss: 0.8057
Epoch 23/39
37/37 - 0s - 8ms/step - accuracy: 0.7282 - loss: 0.8025
Epoch 24/39
37/37 - 0s - 10ms/step - accuracy: 0.7315 - loss: 0.7967
Epoch 25/39
37/37 - 0s - 11ms/step - accuracy: 0.7327 - loss: 0.7951
Epoch 26/39
37/37 - 0s - 8ms/step - accuracy: 0.7346 - loss: 0.7880
Epoch 27/39
37/37 - 0s - 5ms/step - accuracy: 0.7341 - loss: 0.7873
Epoch 28/39
37/37 - 0s - 11ms/step - accuracy: 0.7339 - loss: 0.7820
Epoch 29/39
37/37 - 0s - 10ms/step - accuracy: 0.7354 - loss: 0.7781
Epoch 30/39
37/37 - 0s - 8ms/step - accuracy: 0.7370 - loss: 0.7742
Epoch 31/39
37/37 - 0s - 12ms/step - accuracy: 0.7402 - loss: 0.7715
Epoch 32/39
37/37 - 0s - 7ms/step - accuracy: 0.7383 - loss: 0.7657
Epoch 33/39
37/37 - 0s - 11ms/step - accuracy: 0.7432 - loss: 0.7587
Epoch 34/39
37/37 - 0s - 10ms/step - accuracy: 0.7453 - loss: 0.7580
Epoch 35/39
37/37 - 0s - 9ms/step - accuracy: 0.7449 - loss: 0.7539
Epoch 36/39
37/37 - 0s - 7ms/step - accuracy: 0.7436 - loss: 0.7517
Epoch 37/39
37/37 - 0s - 6ms/step - accuracy: 0.7477 - loss: 0.7466
Epoch 38/39
37/37 - 0s - 5ms/step - accuracy: 0.7471 - loss: 0.7491
Epoch 39/39
37/37 - 0s - 6ms/step - accuracy: 0.7487 - loss: 0.7394
10/10 - 0s - 25ms/step
Epoch 1/39

C:\Users\daxma\anaconda3\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

37/37 - 1s - 38ms/step - accuracy: 0.6078 - loss: 1.4229
Epoch 2/39
37/37 - 0s - 10ms/step - accuracy: 0.6511 - loss: 1.0932
Epoch 3/39
37/37 - 0s - 10ms/step - accuracy: 0.6599 - loss: 1.0441
Epoch 4/39
37/37 - 0s - 6ms/step - accuracy: 0.6662 - loss: 1.0099
Epoch 5/39
37/37 - 0s - 8ms/step - accuracy: 0.6755 - loss: 0.9815
Epoch 6/39
37/37 - 0s - 8ms/step - accuracy: 0.6801 - loss: 0.9617
Epoch 7/39
37/37 - 0s - 6ms/step - accuracy: 0.6801 - loss: 0.9463
Epoch 8/39
37/37 - 0s - 7ms/step - accuracy: 0.6866 - loss: 0.9288
Epoch 9/39
37/37 - 0s - 9ms/step - accuracy: 0.6880 - loss: 0.9182
Epoch 10/39
37/37 - 0s - 5ms/step - accuracy: 0.6914 - loss: 0.9058
Epoch 11/39
37/37 - 0s - 8ms/step - accuracy: 0.6935 - loss: 0.8963
Epoch 12/39
37/37 - 0s - 6ms/step - accuracy: 0.6997 - loss: 0.8841
Epoch 13/39
37/37 - 0s - 6ms/step - accuracy: 0.6996 - loss: 0.8794
Epoch 14/39
37/37 - 0s - 8ms/step - accuracy: 0.7029 - loss: 0.8681
Epoch 15/39
37/37 - 0s - 8ms/step - accuracy: 0.6991 - loss: 0.8626
Epoch 16/39
37/37 - 0s - 10ms/step - accuracy: 0.7020 - loss: 0.8549
Epoch 17/39
37/37 - 0s - 6ms/step - accuracy: 0.7077 - loss: 0.8453
Epoch 18/39
37/37 - 0s - 9ms/step - accuracy: 0.7099 - loss: 0.8418
Epoch 19/39
37/37 - 0s - 7ms/step - accuracy: 0.7129 - loss: 0.8331
Epoch 20/39
37/37 - 0s - 5ms/step - accuracy: 0.7140 - loss: 0.8292
Epoch 21/39
37/37 - 0s - 8ms/step - accuracy: 0.7146 - loss: 0.8238
Epoch 22/39
37/37 - 0s - 5ms/step - accuracy: 0.7142 - loss: 0.8212
Epoch 23/39
37/37 - 0s - 8ms/step - accuracy: 0.7150 - loss: 0.8159
Epoch 24/39
37/37 - 0s - 8ms/step - accuracy: 0.7166 - loss: 0.8118
Epoch 25/39
37/37 - 0s - 7ms/step - accuracy: 0.7180 - loss: 0.8075
Epoch 26/39
37/37 - 0s - 6ms/step - accuracy: 0.7211 - loss: 0.8010
Epoch 27/39
37/37 - 0s - 8ms/step - accuracy: 0.7230 - loss: 0.7985
Epoch 28/39
37/37 - 0s - 10ms/step - accuracy: 0.7228 - loss: 0.7961
Epoch 29/39
37/37 - 0s - 9ms/step - accuracy: 0.7233 - loss: 0.7927
Epoch 30/39
37/37 - 0s - 11ms/step - accuracy: 0.7269 - loss: 0.7855
Epoch 31/39
37/37 - 0s - 7ms/step - accuracy: 0.7248 - loss: 0.7828
Epoch 32/39
37/37 - 0s - 11ms/step - accuracy: 0.7297 - loss: 0.7789
Epoch 33/39
37/37 - 0s - 10ms/step - accuracy: 0.7255 - loss: 0.7805
Epoch 34/39
37/37 - 0s - 8ms/step - accuracy: 0.7276 - loss: 0.7721
Epoch 35/39
37/37 - 0s - 11ms/step - accuracy: 0.7321 - loss: 0.7690
Epoch 36/39
37/37 - 0s - 10ms/step - accuracy: 0.7316 - loss: 0.7664
Epoch 37/39
37/37 - 0s - 8ms/step - accuracy: 0.7338 - loss: 0.7667
Epoch 38/39
37/37 - 0s - 11ms/step - accuracy: 0.7325 - loss: 0.7628
Epoch 39/39
37/37 - 0s - 9ms/step - accuracy: 0.7340 - loss: 0.7574
10/10 - 0s - 23ms/step
| 15        | 0.7207205 | 13.669762 | 2.1817858 | 6.0980792 | 0.1161148 | 0.5169721 | 381.19662 | 39.355183 | 1.3487328 | 2.3818754 | 0.3867353 | 0.9367299 | 0.0412562 |

ValueError: Input y contains NaN.

In [44]:
optimum = nn_opt.max['params']
learning_rate = optimum['learning_rate']

activationL = ['relu', 'sigmoid', 'softplus', 'softsign', 'tanh', 'selu', 'elu', 'exponential', LeakyReLU, 'relu']
optimum['activation'] = activationL[round(optimum['activation'])]

optimum['batch_size'] = round(optimum['batch_size'])
optimum['epochs'] = round(optimum['epochs'])
optimum['layers1'] = round(optimum['layers1'])
optimum['layers2'] = round(optimum['layers2'])
optimum['neurons'] = round(optimum['neurons'])

optimizerL = ['Adam', 'SGD', 'RMSprop', 'Adadelta', 'Adagrad', 'Adamax', 'Nadam', 'Ftrl', 'Adam']
optimizerD = {
    'Adam': Adam(learning_rate=learning_rate),
    'SGD': SGD(learning_rate=learning_rate),
    'RMSprop': RMSprop(learning_rate=learning_rate),
    'Adadelta': Adadelta(learning_rate=learning_rate),
    'Adagrad': Adagrad(learning_rate=learning_rate),
    'Adamax': Adamax(learning_rate=learning_rate),
    'Nadam': Nadam(learning_rate=learning_rate),
    'Ftrl': Ftrl(learning_rate=learning_rate)
}
optimum['optimizer'] = optimizerD[optimizerL[round(optimum['optimizer'])]]
optimum

{'neurons': 37,
 'kernel': 1.1953442280127677,
 'activation': 'elu',
 'optimizer': <keras.src.optimizers.adadelta.Adadelta at 0x2438c7f93a0>,
 'learning_rate': 0.13081785249633104,
 'batch_size': 596,
 'epochs': 21,
 'layers1': 3,
 'layers2': 2,
 'normalization': 0.662522284353982,
 'dropout': 0.31171107608941095,
 'dropout_rate': 0.15602040635334324}

## 5. CNN with Optimised Hyperparamters

In [66]:
# Set the model with optimized hyperparameters

epochs = 21
batch_size = 256

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = 15

layers1 = 3
layers2 = 2
activation = 'elu'
kernel = int(round(1.1953442280127677))  # Rounded kernel size for Conv1D
neurons = 37
normalization = 0.662522284353982
dropout = 0.31171107608941095
dropout_rate = 0.15602040635334324
optimizer = Adadelta(learning_rate=0.130817852496331045)  # Instantiate RMSprop with learning rate

model = Sequential()
model.add(Conv1D(neurons, kernel_size=kernel, activation=activation, input_shape=(timesteps, input_dim)))

if normalization > 0.5:
    model.add(BatchNormalization())

for i in range(layers1):
    model.add(Dense(neurons, activation=activation))

if dropout > 0.5:
    model.add(Dropout(dropout_rate))

for i in range(layers2):
    model.add(Dense(neurons, activation=activation))

model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(n_classes, activation='softmax')) 

model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

C:\Users\daxma\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [68]:
model.summary()

Model: "sequential_76"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_76 (Conv1D)              │ (None, 15, 37)         │           370 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_41          │ (None, 15, 37)         │           148 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_391 (Dense)               │ (None, 15, 37)         │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_392 (Dense)               │ (None, 15, 37)         │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_393 (Dense)               │ (None, 15, 37)         │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_394 (Dense)               │ (None, 15, 37)         │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_395 (Dense)               │ (None, 15, 37)         │         1,406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_76 (MaxPooling1D) │ (None, 7, 37)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_76 (Flatten)            │ (None, 259)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_396 (Dense)               │ (None, 15)             │         3,900 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,448 (44.72 KB)

 Trainable params: 11,374 (44.43 KB)

 Non-trainable params: 74 (296.00 B)

In [69]:
# Put the y_test set back into a one-hot configuration

y_train_one_hot = to_categorical(y_train, num_classes=15)

In [70]:
# Check shapes

print(f'X_train shape: {X_train.shape}')
print(f'y_train_one_hot shape: {y_train_one_hot.shape}')

X_train shape: (17212, 15, 9)
y_train_one_hot shape: (17212, 15)

In [71]:
# Compile the model with categorical_crossentropy

model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

In [72]:
# Fit the model to the data

model.fit(X_train, y_train_one_hot, batch_size=batch_size, epochs=epochs, verbose=2)

Epoch 1/21
68/68 - 4s - 59ms/step - accuracy: 0.5087 - loss: 1.7003
Epoch 2/21
68/68 - 1s - 11ms/step - accuracy: 0.6692 - loss: 1.0236
Epoch 3/21
68/68 - 1s - 10ms/step - accuracy: 0.6904 - loss: 0.9180
Epoch 4/21
68/68 - 1s - 9ms/step - accuracy: 0.7130 - loss: 0.8467
Epoch 5/21
68/68 - 1s - 10ms/step - accuracy: 0.7293 - loss: 0.7976
Epoch 6/21
68/68 - 1s - 11ms/step - accuracy: 0.7392 - loss: 0.7648
Epoch 7/21
68/68 - 1s - 10ms/step - accuracy: 0.7471 - loss: 0.7412
Epoch 8/21
68/68 - 1s - 8ms/step - accuracy: 0.7543 - loss: 0.7204
Epoch 9/21
68/68 - 1s - 9ms/step - accuracy: 0.7585 - loss: 0.7033
Epoch 10/21
68/68 - 1s - 10ms/step - accuracy: 0.7637 - loss: 0.6874
Epoch 11/21
68/68 - 1s - 13ms/step - accuracy: 0.7664 - loss: 0.6735
Epoch 12/21
68/68 - 1s - 11ms/step - accuracy: 0.7705 - loss: 0.6597
Epoch 13/21
68/68 - 1s - 11ms/step - accuracy: 0.7746 - loss: 0.6465
Epoch 14/21
68/68 - 1s - 9ms/step - accuracy: 0.7788 - loss: 0.6341
Epoch 15/21
68/68 - 1s - 12ms/step - accuracy: 0.7826 - loss: 0.6203
Epoch 16/21
68/68 - 1s - 9ms/step - accuracy: 0.7890 - loss: 0.6036
Epoch 17/21
68/68 - 1s - 10ms/step - accuracy: 0.7924 - loss: 0.5883
Epoch 18/21
68/68 - 1s - 10ms/step - accuracy: 0.7974 - loss: 0.5740
Epoch 19/21
68/68 - 0s - 7ms/step - accuracy: 0.8007 - loss: 0.5568
Epoch 20/21
68/68 - 1s - 8ms/step - accuracy: 0.8087 - loss: 0.5405
Epoch 21/21
68/68 - 0s - 6ms/step - accuracy: 0.8155 - loss: 0.5226

## 7. Confusion Matrix

In [74]:
# Define list of stations names

stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'
}

In [75]:
def confusion_matrix(y_true, y_pred, stations):
    # Check if y_true and y_pred are one-hot encoded or already class indices
    if y_true.ndim == 1:
        y_true_labels = y_true
    else:
        y_true_labels = np.argmax(y_true, axis=1)
    
    if y_pred.ndim == 1:
        y_pred_labels = y_pred
    else:
        y_pred_labels = np.argmax(y_pred, axis=1)
        
    # Map numeric labels to activity names
    y_true_series = pd.Series([stations[y] for y in y_true_labels])
    y_pred_series = pd.Series([stations[y] for y in y_pred_labels])
    
    return pd.crosstab(y_true_series, y_pred_series, rownames=['True'], colnames=['Pred'])

In [76]:
y_pred = model.predict(X_test)

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

In [77]:
# Evaluate

print(confusion_matrix(y_test, y_pred, stations))

Pred        BASEL  BELGRADE  BUDAPEST  DEBILT  HEATHROW  LJUBLJANA  MADRID
True
BASEL        3391       171        42       6        14          1      57
BELGRADE      244       796        17       1         4          0      30
BUDAPEST       40        54        91       3         5          3      18
DEBILT         21         8        18      22        10          1       2
DUSSELDORF      9         2         6       0         9          0       3
HEATHROW       22         2         5       3        33          0      17
KASSEL          6         2         2       0         0          1       0
LJUBLJANA      19         8         4       0         1         11      18
MAASTRICHT      5         0         1       0         1          0       2
MADRID         54        28        16       0        13          1     346
MUNCHENB        8         0         0       0         0          0       0
OSLO            2         0         0       0         1          0       2
STOCKHOLM       1         3         0       0         0          0       0
VALENTIA        1         0         0       0         0          0       0